### ISSUE TITLE
Admission - complétion profil - inscription antérieure

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#100]
Dans l'écran pour compléter le profil, dans le dernier cadre, il y a une erreur (pas d'institution définie)

"Avez-vous déjà été inscrit, antérieurement, à l'institution suivante: **<font style='color:red'>Aucune institution de définie</font"**

**Comment by htmfilho** [comment]
@verpoorten c'est vrais que le donnée ne se trouve pas dans la base de donnée pour faire fonctionné ce parti là, mais il faut traiter l'absence de donnée de toute façon.

**Comment by verpoorten** [comment]
Si pas de données je masque le div concernant une inscription antérieure à une institution
