### ISSUE TITLE
(103417) Adapter des urls pour l'affichage des horaires

### ISSUE THREAD

**Issue by mahianth** [uclouvain/osis-portal#1001]
Bonjour,

Pourrais-je demander de bien vouloir prendre en considération les adaptations suivantes dans la consultation de l'horaire des professeurs via leur bv:
 - via mon métier – mon horaire, l’url générée est la suivante: http://horairev6.uclouvain.be/direct/index.jsp?displayConfName=WebProf&showTree=false&showOptions=false&login=enseignant&password=prof&projectId=9&code=00001169. Le code du projet (projectId) n’est pas correct: le code du projet actuel est le 21;
 - via ma charge d’enseignement, icône horloge en regard des cours, l’url générée est la suivante: http://horairev6.uclouvain.be/direct/index.jsp?displayConfName=WEB&showTree=false&showOptions=false&weeks=0&login=enseignant&password=prof&projectId=21&code=ldrop2103. Merci de retirer le paramètre weeks=0 afin de se positionner par défaut sur la semaine courante, et non la première semaine de l’année académique. La même modification est à faire dans la rubrique « horaire d’un ou plusieurs cours spécifiques » en bas de page: les url générées par le lien « cliquez ici » et par le bouton « ok » contienne également le paramètre weeks=0 qu’il est préférable de supprimer.

Merci déjà,

Fabrice

**Comment by glamarca** [comment]
Il n'y a aucun commit à faire pour ce ticket dans Osis-Portal.

- Le premier lien est sur le portail, à transfèrer à l'équipe portail.
- L'url utilisé dans le deuxième lien est définit dans les settings des serveurs.
