### ISSUE TITLE
Créer une application pour les memoires

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#104]
Les étudiants ne peuvent pas accéder directement OSIS. L'accès pour les étudiants devra se faire via OSIS-Portal.

L'application « Mémoires » permet aux étudiants d'accéder, dès la rentrée de septembre 2016, les info relative aux mémoires en cours. Il faut faire les tests durant juillet/août.

**Comment by chfivet** [comment]
Issue#216 existe pour la création de dissertation dans Osis-Portal
