### ISSUE TITLE
Liens dans l'administration de Attestation et  Encodage des notes

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#1045]
Lorsqu'on visualise les attestion ou les points des étudiants, le breadcrumb doit suivre le chemin emprunté : 
- Administration Facultaire/ Publication ou attestation : depuis l'admin facultaire
- Mes points / Mes attestations : depuis le dashboard des étudiants

![image](https://cloud.githubusercontent.com/assets/11191415/25342129/4f2980da-290b-11e7-8f7b-735a20898407.png)

**Comment by glamarca** [comment]
Test en Dev : 
* Mes notes et attestations en tant que student : 
![Mes notes](https://cloud.githubusercontent.com/assets/11191415/26118999/089cb750-3a6c-11e7-84d4-37db42727c2c.png)

![Mes notes/Resultats](https://cloud.githubusercontent.com/assets/11191415/26118897/c36d69a4-3a6b-11e7-8aff-d0f0d4d7de39.png)

![Attestation](https://cloud.githubusercontent.com/assets/11191415/26118991/026b78e4-3a6c-11e7-8a9b-e9cc3a3dc453.png)

* Notes et attestations en tant que gestionnaire facultaire:
![capture du 2017-05-16 19-22-29](https://cloud.githubusercontent.com/assets/11191415/26119511/bab1b50c-3a6d-11e7-9bc7-d841ab169a7b.png)

![capture du 2017-05-16 19-22-46](https://cloud.githubusercontent.com/assets/11191415/26119516/bd6dffc6-3a6d-11e7-9bec-9cfceffb350f.png)

![capture du 2017-05-16 19-23-34](https://cloud.githubusercontent.com/assets/11191415/26119519/c0ffcca0-3a6d-11e7-914b-6d3f0761f2c2.png)

Corrections à faire : 
- [ ] Traduction manquante
- [ ] Mes Notes d'examen => Notes d'examen dans ecran admin

PR :

**Comment by glamarca** [comment]
![image](https://cloud.githubusercontent.com/assets/11191415/26144520/77c02432-3ae9-11e7-8d8b-1cb6e2f8e355.png)

![image](https://cloud.githubusercontent.com/assets/11191415/26144533/8647d5fe-3ae9-11e7-9260-48e105edffab.png)

Dev OK.

**Comment by thuyhanghoang** [comment]
Parfait! Merci!
