### ISSUE TITLE
[Infra] Modifier le port de connexion du serveur couchbase pour l'indexation

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#105]
le port (9102) utilisé par CouchBase pour l'indexation est le même que celui utilisé par le programme de backup de l'infrastructure.
Vérifier comment modifier le port , et le faire sur tous les serveurs.

Topic sur forum developeur : https://forums.couchbase.com/t/custom-indexer-port/7848

**Comment by glamarca** [comment]
Pas de solution pour le moment , je dois aller voir dans le code de lancement de couchbase , car ça me parait fou que ce n'est pas modifiable.

**Comment by htmfilho** [comment]
Couchbase ne sera plus utilisé
