### ISSUE TITLE
Problème sur des feuilles de notes imprimées à partir du bureau virtuel des profs

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#1069]
![image](https://cloud.githubusercontent.com/assets/6651769/25948528/28df918e-3654-11e7-8cdb-01471769cf22.png)

**Comment by albrugnetti** [comment]
Issue moved to [uclouvain/osis-common #178](https://github.com/uclouvain/osis-common/issues/178) via [**ZenHub**](https://www.zenhub.com/)
