### ISSUE TITLE
Ajouter le lien vers l'encodage de notes sur le bureau virtuel des enseignants

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#1070]
![image](https://cloud.githubusercontent.com/assets/6651769/25948855/cb1a8e80-3655-11e7-8bfe-83e7a54a3f50.png)
A la place de "Mes feuilles de notes", on met "Encodage de notes" avec une description: Obtenir mes feuilles de notes et encoder les notes de mes étudiants.
Et quand ils cliquent sur ce lien, il va avoir 2 choix: 
- Obtenir mes feuilles de notes
- Encoder mes notes avec une description nécessite un accès VPN en dehors du réseau de l'UCL

**Comment by albrugnetti** [comment]
@htmfilho Pour ce que cela fonctionne, peux-tu ajouter la variable OSIS_SCORE_ENCODING_URL = "XXX" dans le fichier .env où XXX = URL 'NAME_SERVER_ADRESS/assessments/scores_encoding'

**Comment by albrugnetti** [comment]
@thuyhanghoang  Ok pour moi en dev. Peux-tu valider? Merci
![dashboard](https://cloud.githubusercontent.com/assets/19836473/26099005/bccfd876-3a29-11e7-9422-737ecb21e23b.png)

**Comment by thuyhanghoang** [comment]
@albrugnetti  tu as centralisé les icones?

**Comment by albrugnetti** [comment]
@thuyhanghoang  Oui, c'est moche? :dancing_women:  Je peux revenir à l'état précédent si tu préfères :)

**Comment by thuyhanghoang** [comment]
@albrugnetti Je mets en Test Failed pourque tu remets des icones à gauche

**Comment by albrugnetti** [comment]
@thuyhanghoang Je viens de corriger l'affichage :) Peux-tu vérifier que c'est ok? merci

**Comment by thuyhanghoang** [comment]
ok en Dev, il reste encore le problème pour obtenir la feuille de notes (lié à https://github.com/uclouvain/osis/issues/2276)
