### ISSUE TITLE
Fichier Excel des inscrits au cours et examens  :  2 + 2 corrections (Titre et légende)

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#1072]
@bmjmoreau commented on [Fri May 12 2017](https://github.com/uclouvain/osis/issues/2256)

1. Dashboard : 

Remplacer
"Liste des étudiants inscrits à mes examens"
par 
"Listes des étudiants inscrits à mes cours et examens"
(le mot Listes au pluriel)

2. Écran de la foncitonnalité : idem

3. Légende : 
  a. supprimer ligne "Email | Email"  (après "Nom, Prénom1")
  b. Insérer après la ligne "Etat courts  |  Type d'inscription au cours (... etc)"
une ligne 
"Antic préreQu  | Statut spécial d'inscription au cours : A = anticipé, Q = préreQuis ; H = Hors programme)"

NB tenir Christine informée de la fin du travail

---

@verpoorten commented on [Fri May 12 2017](https://github.com/uclouvain/osis/issues/2256#issuecomment-301037839)

@bmjmoreau Je pense que tu t'es trompé et que c'est plutôt un ticket osis_portal

**Comment by bmjmoreau** [comment]
OK !
