### ISSUE TITLE
Move paper_sheet translation to osis-common

### ISSUE THREAD

**Issue by albrugnetti** [uclouvain/osis-portal#1074]
Move all translation used in paper_sheet (osis-common) in order to have consistency between osis / osis-portal

**Comment by albrugnetti** [comment]
@thuyhanghoang De mon coté, la génération du PDF produit le même résultat Osis/ Osis portal. Peux-tu confirmer? Merci :+1:

**Comment by thuyhanghoang** [comment]
ok en Dev
