### ISSUE TITLE
(106721) Des notes de janvier sont affichées en septembre

### ISSUE THREAD

**Issue by mahianth** [uclouvain/osis-portal#1077]
Concerne le cours LANGL1330 dans la liste disponible dans le bureau de l'enseignant.

**Comment by verpoorten** [comment]
@mahianth C'est pour tous les étudiants ou seulement 1?

**Comment by mahianth** [comment]
Quelques étudiants sont concernés ; il suffit de demander la liste pour le constater.
Je ne place aucune liste dans le ticket, étant donné qu'OSIS est ouvert au public.

**Comment by htmfilho** [comment]
Salut @mahianth , peux-tu tester en dev ? Merci.

**Comment by mahianth** [comment]
ok en DEV : il n'y a plus de note affichée en septembre.

**Comment by htmfilho** [comment]
Salut @mahianth , c'est en prod.
