### ISSUE TITLE
Remplacer l'utilisation de la queue RPC 'rpc_exam_enrollment_form' par deux queues asynchrone

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#1082]
Lié à https://github.com/uclouvain/epc/issues/1429
Actuellement , le formulaire d'inscription aux examens est récupéré depuis epc par une queue rpc (synchrone).
Si une erreur se produit , ou si epc n'est pas actif lors de l'envoi d'un message, lorsqu'il se reconnecte il ne sait plus renvoyer la réponse (queue de retour temporaire n'existe plus) => plante toute la queue.

Osis-portal enverra désormais sa requête dans la queue 'EXAM_ENROLLMENT_FORM_REQUEST'.
La reponse arrivera dans une autre queue 'EXAM_ENROLLMENT_FORM_RESPONSE' et sera enregistrée dans la db.
Pendant un laps de temps déterminé (10 s ? ), juste après l'envoie du request_message, le processus utilisateur interrogera la DB toute les 1s pour voir si la reponse est revenue.
Si Le timeout est dépassé, un message demande à l'utilisateur de réessayer plus tard.

Le workflow est le suivant :

- L'utilisateur clique sur le bouton
 - Le message de demande de document est envoyée dans la queue 'EXAM_ENROLLMENT_FORM_REQUEST'
Une boucle de recherche dans la table 'exam_enrollment_form' est lancée, toute les sec on regarde si le document est dans la table
Pendant ce temps l'écoute de la Queue 'EXAM_ENROLLMENT_FORM_RESPONSE' est actif, et lorsque le message de retour est consommé, le pdf est enregistré dans la DB
=> Résultat : si la réponse reviens dans le temps imparti, le pdf est affiché, sinon un message demande à l'utilisateur de réessayé.

**Comment by htmfilho** [comment]
@matgerard , peux-tu expliquer à @verpoorten comme tu as fait pour l'encodage de note? @verpoorten , c'est attribué à toi parce que il y a des modifications a faire dans EPC. Tu peux demander à @glamarca quoi faire du coté EPC. Merdi d'avance.

**Comment by matgerard** [comment]
Pour info, références de ce qui a été fait pour le remplacement de la queue RPC paper_sheet : 
- code principal dans osis-portal : https://github.com/uclouvain/osis-portal/pull/1131/files 
- petite correction supplémentaire dans osis-portal : https://github.com/uclouvain/osis-portal/pull/1133/files
- code principal dans osis : https://github.com/uclouvain/osis/pull/2606/files
- complément pour la gestion d'exceptions dans osis : https://github.com/uclouvain/osis/pull/2613/files 

Toute modification dans le fichier wsgi doit être refaite par @glamarca sur les serveurs.

**Comment by chfivet** [comment]
@htmfilho le ticket a été transféré dans Jira.
Puis-je le fermer ?

**Comment by htmfilho** [comment]
https://uclouvain-sips.atlassian.net/projects/OSIS/issues/OSIS-29
