### ISSUE TITLE
Déplacer la définission des signaux de création/update user dans osis-common

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#1083]
- Lié à : https://github.com/uclouvain/osis-common/issues/183

- [x] Maj reference osis-common
- [x] Supprimer références à osis-louvain-auth
- [x] Lier les import à osis-common

**Comment by htmfilho** [comment]
@glamarca peux-tu tester ce ticket ? Merci.

**Comment by glamarca** [comment]
Ok en Dev
