### ISSUE TITLE
Corriger le texte sur le dashboard des enseignants

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#1093]
@thuyhanghoang commented on [Fri May 19 2017](https://github.com/uclouvain/osis/issues/2321)

![image](https://cloud.githubusercontent.com/assets/6651769/26240368/189b78b4-3c81-11e7-8c07-ae1bd2446212.png)
Mes feuilles de notes => Encodage de notes
Encodage de notes => Encoder des notes

**Comment by matgerard** [comment]
@thuyhanghoang ok pour moi, testable en qa.

**Comment by thuyhanghoang** [comment]
@matgerard @htmfilho ok en QA, n'oubliez-pas de merger en Dev
