### ISSUE TITLE
[Infra] Configuration plus en détail des serveurs couchbase

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#111]
- [ ] Mise en place du backup
- [ ] Configuration diverses
- [x] Mise en cluster des deux prod

**Comment by glamarca** [comment]
Tant qu'il n'y a pas de données dnas la DB , je ne peux pas mettre en plca le backup , car il faut donner le nom du "shema" (je ne me souviens plus du nom exactement sous couchbase) , et pour l'instant il n'y en a pas.

**Comment by htmfilho** [comment]
Couchbase ne sera plus utilisé.
