### ISSUE TITLE
Avertir Sentry dans le cas où il n'y a pas de template html trouvé pour envoyer un mail aux utilisateurs

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#1110]
Lié à uclouvain/osis-common#189.
- [x] Créer un logger dans les settings d'Osis

**Comment by basmot** [comment]
@matgerard Pourrais-tu me montrer comment faire un envoi d'email dans Dissertation pour que je puisse tester le "send_mail" dans Osis-portal?

**Comment by matgerard** [comment]
@basmot c'est testé sur dev avec dissertation : une action d'envoi de mail crée bien un record dans la table message history.
