### ISSUE TITLE
Modification de la publication des notes

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#1114]
- [x] Ajout de l'avancement dans le cycle
- [x] Gestion des légende de crédits ( r = Réussi, R = Reporté)

![capture du 2017-06-12 16-31-12](https://user-images.githubusercontent.com/11191415/27039067-1d3bf3d4-4f8d-11e7-9e4b-54bc1f8d9602.png)

![capture du 2017-06-12 16-31-30](https://user-images.githubusercontent.com/11191415/27039072-2408996a-4f8d-11e7-98b5-f7b9a45edcf9.png)

**Comment by htmfilho** [comment]
@glamarca c'est bon en dev ?

**Comment by htmfilho** [comment]
@glamarca, qu'est-ce qu'on fait avec ce ticket?
