### ISSUE TITLE
Afficher plus clairement le message qui indique la nécessité d'un VPN pour accéder à l'ancodage des notes dans Osis

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#1122]
Des appels au support sont effectués régulièrement pour dire qu'Osis n'est pas disponible/down/inaccessible, alors que la cause vient du fait qu'ils n'ont pas de VPN.
- [ ] Mettre le message en gras et en warning, avec un icone qui attire l'attention sur le besoin du VPN

**Comment by matgerard** [comment]
Testé en qa et dev.
@thuyhanghoang peux-tu vérifier et fermer le ticket si c'est ok ?
