### ISSUE TITLE
Compléter diplômes et examens - Liaison entre les examens spécials d'admission et les offres FSA1BA ou ARCH1BA

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#113]
Dans l'écran 33 (pour les études secondaires)

Dans la documentation "Si le candidat fait une demande à un offre Ingénieur civil" (FSA1BA ou ARCH1BA) =>Il est obligé de coché sur le 3e choix => une vérification pour pouvoir passer l'étape suivante, s'il ne choisit pasle 3e examen => il faut avoir un message"

**Comment by basmot** [comment]
Prévoir discussion base de données avec @thuyhanghoang, @htmfilho pour régler cette problématique.
Une proposition : créer une table de liaison entre AdmissionExamType et OfferYear.

**Comment by htmfilho** [comment]
Créer un nouveau modèle `OfferAdmissionExamType`
Permet de gérer le cas spécial de FSA1BA et ARCH1BA pour le type d'examen d'admission.

Champs : 
- offer_year (FK null=False)
- admission_exam_type (FK null=False)

**Comment by thuyhanghoang** [comment]
@verpoorten je ne vois pas du tout le bloc concernant d'examen d'admission.

**Comment by verpoorten** [comment]
@thuyhanghoang ce bloc est affiché/masqué dans certains cas.  De mémoire, je dirais que si tu réponds "non" à la 1ière question, ce bloc apparaitra

**Comment by thuyhanghoang** [comment]
j'ai choisi FSA1BA et puis j'ai choisi 2 examen, et quand je passe "Etape suivante", il me laisse passer, sans message

**Comment by verpoorten** [comment]
@thuyhanghoang Il manquait des données en base de données pour valider le fait que FSA1BA exige un "examen spécial d'admission aux études universitaires de 1er cycle de l'ingénieur (ingénieur civil)".  Néanmoins, actuellement le fait de ne pas cocher l'examen spécial n'empêche pas de passer à l'étape suivante, mais si on clique sur sauveg'arder' on va avoir un message.  N'est-ce pas suffisant?

**Comment by thuyhanghoang** [comment]
le message quand on veut sauvegarder l'onglet si on ne coche pas " Examen spécial d'admission aux études universitaires de 1er cycle de l'ingénieur (ingénieur civil)", par contre on peut passer l'étape suivante.

ok pour ce ticket, mais ll faut assurer que quand on veut soumettre ou valider l'onglet, l'application ne permet pas de le faire s'il ne coche pas " Examen spécial d'admission aux études universitaires de 1er cycle de l'ingénieur (ingénieur civil)"
je vais créer un ticket pour ça.
ok pour
