### ISSUE TITLE
Search learning unit enrollments by student

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#1144]
**En tant que** administrateur
**Je veux** consulter les inscriptions aux cours par étudiant.
**de sorte que** je peux savoir si l'étudiant est inscrit à un cours.

C'est une consultation exactement comme dans osis.

**Comment by htmfilho** [comment]
@matgerard , c'est dans l'admin! Pas besoin de créer des écrans.

**Comment by htmfilho** [comment]
C'est juste ça:

```
search_fields = ['learning_unit_year__acronym', 
                     'offer_enrollment__offer_year__acronym',
                     'offer_enrollment__student__registration_id',
                     'offer_enrollment__student__person__first_name',
                     'offer_enrollment__student__person__last_name']
```

dans `learning_unit_enrollment.py`.

**Comment by matgerard** [comment]
Ok, mal compris, je pensais qu'il fallait des écrans.

**Comment by matgerard** [comment]
OK en dev.

**Comment by matgerard** [comment]
@htmfilho qui peut tester ce ticket, toi ? Merci !
