### ISSUE TITLE
Compléter le profil du candidat pour les tickets concernant "Compléter diplômes et examens" -

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#115]
- Pour l'écran initial, Il est noté dans la doc:

> "Si l'étudiant a déjà l'information d'un de ces blocs dans son profil, ce bloc n'apparait pas"

or pour le moment on n'a pas cette information dans le profil.
- Pour l'écran state 2, dans la doc il est noté:

> "Si l'étudiant a déjà l'information de ses études secondaires dans son profil, ce bloc n'apparait pas"

or pour le moment on n'a pas cette information dans le profil.

**Comment by verpoorten** [comment]
J'ai demandé des explications à Hang.  En fait, ce sont des points qui seront surtout utilisés à partir de l'année prochaine.  En fait, si un étudiant s'inscrit après avoir déjà rempli l'année précédente toutes les infos concernant les études secondaires/diplomes, il ne doit plus repasser par toutes ces étapes.  (Par contre, attention il devrait tout de même ajouter des années dans sont curriculum, pour qu'on sache ce que l'étudiant à fait entre temps)

**Comment by verpoorten** [comment]
@htmfilho Je pense que je commencerai ce ticket quand le ticket 35 sera clotûré

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
