### ISSUE TITLE
When synchronizing person, check if the global id already exists

### ISSUE THREAD

**Issue by albrugnetti** [uclouvain/osis-portal#1150]
If the global id already exists, then update the existing record.

Same as uclouvain/osis#2672

**Comment by glamarca** [comment]
Scénario de test : 
- Supression de l'utilisateur et de l'objet Person correspondant (+ toutes les dépendances)
- Connexion à l'application avec l'utilisateur : -> l'objet Person sera créé avec un external_id
 - Si la 1ère connexion se fait du côté portal, l'objet Person créé doit être migré vers osis 
- Synchronisation de la DB avec EPC -> La personne ne doit pas être créée en double

**Comment by htmfilho** [comment]
Salut @glamarca , peux-tu tester ce ticket s'il te plaît ?
