### ISSUE TITLE
Create a admin page to print a scoresheet as a professor

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#1156]
**En tant que** administrator

**Je veux** demander l'impression de feuille de notes à la place d'un prof.

**de sorte que** simuler la difficulté d'utilisation d'un prof.

**Comment by matgerard** [comment]
Ok en QA. 
@mahianth : pourrais-tu tester ceci ? En QA, sur la page gestionnaire. Merci !

**Comment by mahianth** [comment]
Testé : ok.
