### ISSUE TITLE
Charge d'enseignement

### ISSUE THREAD

**Issue by edd19** [uclouvain/osis-portal#1175]
Il a été décidé de rechercher les volumes de la charge d'enseignement directement dans EPC.
Il est donc nécessaire:
a) de développer un web service dans EPC (web service qui recevra le global id de l'enseignant ainsi que l'année académique)
b) de modifier les écrans correspondants dans OSIS-Portal
Il s'agit d'une solution temporaire en attendant que l'analyse de cette fonctionnalité dans OSIS soit finalisée et implémentée.

**Comment by htmfilho** [comment]
Lié à uclouvain/epc#1759
