### ISSUE TITLE
( 115110) Message d'erreur pour les inscriptions aux examens

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#1176]
Contexte : Nous sommes en 2016-17 (début septembre). Un nouvel étudiant s'est inscrit pour l'année académique 2017-18. S'il clique sur "m'inscrire aux examens" début septembre, il réçoit le messag d'erreur suivant : "Vous n'êtes inscrit à aucun programme d'étude pour cette année académique.".
En effet, début septembre, on est encore en 2016-17 (pas encore sur l'année académique 2017-18).

- [x] Modifier le message et préciser l'année académique en cours dans le message d'erreur : `Vous n'êtes inscrit à aucun programme d'étude pour l'année académique en cours (2016-17).`

**Comment by matgerard** [comment]
Entre le 15/09 et le 30/09, on n'est pas certains du retour de `current_academic_year()` : 
```
def current_academic_year():
    academic_yr = AcademicYear.objects.filter(start_date__lte=timezone.now()) \
                                      .filter(end_date__gte=timezone.now()).first()
    if academic_yr:
        return academic_yr
    else:
        return None
```
Il est préférable de corriger en ajoutant des tests.

**Comment by htmfilho** [comment]
Le code de `academic_year` dans osis est plus propre que dans osis-portal. Peux-tu le prendre comme référence ?

**Comment by matgerard** [comment]
OK en dev.

**Comment by matgerard** [comment]
@basmot @mahianth : l'un de vous deux peut-il tester ce ticket ?
Il faut être student en sur osis-portal en dev et cliquer sur le lien _Inscription aux examens_
Merci !

**Comment by basmot** [comment]
Testé et ok en Dev (dans le cas où il y a 2 academic_year ou une seule + cas où pas student, student mais pas d'inscription et inscrit).
