### ISSUE TITLE
Lors de l'activation d'un compte on envoit un email d'activation il faudra utiliser les modèles messages

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#120]
Lors de l'activation d'un compte on envoit un email d'activation il faudra utiliser les modèles messages

**Comment by verpoorten** [comment]
@htmfilho dans quel module je place l'entité MessageTemplate : admission, reference, autre part?

**Comment by glamarca** [comment]
@verpoorten MessageTemplate fait partie de osis_common

**Comment by verpoorten** [comment]
@glamarca ce qui veut dire que je peux supprimer le messagetemplate.py qui se trouve dans le module admission

**Comment by glamarca** [comment]
@verpoorten 
Oui , il faut utiliser celui de common.
Il faudra également recrer les template dans la bonne table, via l'admin. (dans chaque environnement)
Ou alors , tu peux faire un ficher de migration pour migrer les données, dans ce cas cela passera sur tous les environnements.

**Comment by verpoorten** [comment]
@glamarca saurais-tu me dire ce que je suis sensée mettre comme donnée dans receiver_id  de message_history.  applicant_id, user.id, person.id?

**Comment by glamarca** [comment]
C'est le person_id qu'il faut mettre.
Mais comme osis-common ne peut pas dépendre du modèle de osis ou osis-portal, ce n'est pas une 'vrai' foreign key.

**Comment by glamarca** [comment]
@verpoorten 
Il y a une erreur dans osis-common , pour la recherche par person des historique de message envoyé.( find_my_messages)
Je corrige cela dans le ticket 7 de osis-common.

**Comment by verpoorten** [comment]
@glamarca Bizarre de mettre un person_id car actuellement je ne crée pas de person à la création d'un compte candidat.  Je crée un user et un applicant???

**Comment by glamarca** [comment]
@verpoorten 
Sorry, j'avais pas vompris que applicant était l'équivalent de person dans admission.
Du coup, c'est applicant_id qu'il faut utiliser.

**Comment by thuyhanghoang** [comment]
@htmfilho peux-tu me dire comment je dois faire pour tester les modèles du message? Merci!

**Comment by htmfilho** [comment]
@thuyhanghoang Une bonne façon de le tester est d'aller dans l'admin (https://dev.studies.uclouvain.be/admin/osis_common/messagetemplate/), changer le modèle de message et voir si l'e-mail qui arrive dans la boîte (team.osis.louvain-at-gmail.com) contient la modification.

**Comment by thuyhanghoang** [comment]
lors que je me connecte sur le lien que tu as donné ci-dessus, il me met le message suivant:
![image](https://cloud.githubusercontent.com/assets/6651769/18386174/724aeabe-7695-11e6-86e0-b2a8b3c24bf4.png)

@htmfilho Sais-tu faire le nécessaire? Merci

**Comment by thuyhanghoang** [comment]
@htmfilho @verpoorten J'ai changé le modèle de message mais je ne sais pas tester pour voir comment le message est généré parce que je ne sais pas passer tous les onglets pour pouvoir "soumettre" la demande pour voir le message. Je suis coincé dans l'onglet "Enquête sociologique".

**Comment by htmfilho** [comment]
@thuyhanghoang le seul modèle de message q'existe c'est l'activation de compte. Pour le tester, il suffit de créer un nouveau compte. C'est inutile d' créer une demande pour cela.

**Comment by thuyhanghoang** [comment]
J'ai testé le changement le message, ça marche bien!

Mais j'ai une question: est-ce que l'on peut avoir la liste des variables quelques parts? Le but c'est pour aider l'utilisateur de configurer le message, ils ne sont pas capables de se souvenir tous les nom de variables. C'est pour faciliter le travail de construire le message.

**Comment by htmfilho** [comment]
Pour le moment, les utilisateurs ne peuvent pas changer le modèle de message. C'est quelque chose pour nous à gérer, faire du changement sans une demande de patch.

Merci.
