### ISSUE TITLE
Forbidden (403)  CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#125]
Il y a un problème lors de la soumission de tout les formulaires dans osis-portal serveur dev:

 
![forbidden-403-osis-portal](https://cloud.githubusercontent.com/assets/200272/15141953/fb58bd5c-16a2-11e6-8eeb-273b0f39e6d6.png)

**Comment by htmfilho** [comment]
@jpminet

**Comment by glamarca** [comment]
Je viens de vérifier les settings du serveur et j'ai bien 
![image](https://cloud.githubusercontent.com/assets/11191415/15148383/42dbab90-16c5-11e6-9ba8-5df85280e995.png)

J'ai également tester le formulaire de creation de compte , et bien que j'ai une erreur du au Country ID qui n'existe as , je n'ai pas eu d'erreur de soumission de recherche (vu qu'il fait la requete dans la DB avec les infos du formulaire).
Est-ce que le navigateur sur lequel c'est testé accepte bien les cookkies? (voir le premier point de l'erreur dans la description du ticket)

**Comment by htmfilho** [comment]
Je utilise le même navigateur pour tester dev.osis et dev.studies. J'ai ne arrive même pas à accéder l'administration. @basmot arrive au même problème sur son poste.

**Comment by glamarca** [comment]
Faudra que je vérifie avec vous , car je n'ai aucun problème à accéder à la partie admin , ni a faire un update.
![image](https://cloud.githubusercontent.com/assets/11191415/15187611/03672bf0-17a2-11e6-9c7e-49474b175d29.png)

![image](https://cloud.githubusercontent.com/assets/11191415/15187648/21ba7ea4-17a2-11e6-9bcf-f8bb1cb1b90a.png)

**Comment by glamarca** [comment]
Ok , j'ai compris!
Je n'ai pas encore fait la redirection http vers https sur le serveur , et vous testez avec http => ça plante car pour le csfr_cookie_secure il faut absolument de l'https.

Je vais règler cela.

**Comment by glamarca** [comment]
@htmfilho 
Voilà , redirection faite sur studies-dev.
Su qa et prod c'était déjà bon.
Maintenant ça ne devrait plus planter
