### ISSUE TITLE
Imprimer la feuille des notes du coté Portal dans l'application dashboard

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#142]

**Comment by glamarca** [comment]
@basmot @htmfilho 
Prevenez moi lorsque vous ferez le merge , car je dois adapter les configurations serveur avec les données de connexion couchbase, et tester le tout.
ça me permettra également de mettre en place le backup de la DB couchbase

**Comment by basmot** [comment]
@htmfilho Je n'ai pas su tester via l'interpreteur python car j'ai besoin de load l'environnement Django (traductions, etc).
Mais normalement cela devrait fonctionner.

**Comment by basmot** [comment]
@glamarca 
C'est @htmfilho qui doit terminer le ticket.

**Comment by glamarca** [comment]
Je n'ai pas trop fait de changements, mais il faudra en discuter , car le bucket est propre à l'encodage , hors un bucket est plus une DB qu'une table (d'ailleurs sur le serveur il faut allouer une partie fixe de la RAM à chaque Bucket).
Il faudrait également centraliser la connexion.
J'ai sorti la connexion des méthodes pour ne par créer une connexion à chaque appel de méthode (c'est ce qui est conseillé sur le site de couchbase dans le tuto), mais elle reste attaché score_encoding.py pour l'instant.

**Comment by glamarca** [comment]
@htmfilho 
Les settings pour dev sont en place, donc si tu merges cela devrait être bon au prochain déploiement.
