### ISSUE TITLE
Admission - bug - complétion profil

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#148]
L'introduction d'une date de naissance erronée (1/20/1950) ou dans un format non attendu (1/10/60) provoque un plantage. 

Il faudrait inclure en-dessous du champ une info à l'utilisateur sur le format attendu de la date (jj/mm/aaaa) et un test de la validité de la date entrée avec gestion de l'erreur.  Ce serait aussi bien de limiter les dates possibles à [année actuelle - 100 ans, année actuelle - 15 ans] (on ne devrait pas avoir de candidat de plus de 100 ans ou de moins de 15 ans, non ?)

**Comment by verpoorten** [comment]
@thuyhanghoang Quand tu testeras tu pourras remarquer que si la date de naissance est erronée un message d'erreur(en rouge) s'affiche en-dessous du champ. (Si la date n'est pas valide elle ne sera bien entendu pas sauvegardée, mais cela ne bloquera pas la sauvegarde du reste des informations)

**Comment by thuyhanghoang** [comment]
La date encodé est bien validée, par contre, il n'y a pas de "Ce serait aussi bien de limiter les dates possibles à année actuelle - 100 ans, année actuelle - 15 ans". C'est une bonne idée, mais ce n'est pas urgent, on le corrigera quand l'utilisateur demandera
