### ISSUE TITLE
Admission - bug - modification profil

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#149]
Quand je modifie un champ d'un profil existant puis que je clique sur "étape suivante", j'observe un comportement différent suivant les champs:
- si je modifie le nom, la modification est perdue
- si je modifie le lieu de naissance, la modification est enregistrée

Dans les deux cas, il n'y a aucune notification à l'utilisateur.

Lorsqu'il y a modification de n"importe quel champ et que l'utilisateur clique "étape suivante", il faudrait une notification l'informant d'une info modifiée non sauvegardée et lui demandant s'il veut sauver ses modifications ou les abandonner ou revenir à l'écran de modification. (du style "save", "discard", "ignore" dans les applications microsoft)

**Comment by verpoorten** [comment]
En fait, le nom n'était jamais sauvegardé.

**Comment by htmfilho** [comment]
@verpoorten le ticket est près a tester en dev. Merci.

**Comment by verpoorten** [comment]
@htmfilho Je ne sais pas tester.  Quand on navigue dans les onglets, cela ne se passe pas bien...il semblerait qu'il manque des urls

**Comment by htmfilho** [comment]
@glamarca je pense qui on as un problème de fichiers static dans le serveur osis-portal dev q'empêche de bon fonctionnement de l'application Admission.

**Comment by htmfilho** [comment]
@glamarca en fait, l'application demande l'authentication Shibboleth pour accéder les fichiers js et css.

**Comment by glamarca** [comment]
@htmfilho @verpoorten Ok , je vais vérifier cela.

**Comment by verpoorten** [comment]
Ne fonctionne de nouveau plus pour le moment, probablement un régression suite au ticket #67.  J'ai résolu le problème dans le #22, mais c'est tj en local chez moi car pas totalement finit.

**Comment by glamarca** [comment]
@htmfilho @verpoorten @basmot 
Je vais devoir cloturer ce ticket, cars il a déjà été mergé en Dev
