### ISSUE TITLE
[Configuration] Mise en place des authentifications multiples sur les serveurs

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#154]
- [x] "/" : pris en charge par Django , pas d'authentification, mais pas d'url correspondante
- [x] "/admission" : pris en charge par Django , authentification Django
- [x] "/admin", "/dasboard" : pris en charge par Django , authentification par shibboleth
- [x] "/catalog" : pris en charge par Django , pas d'authentification (public)
- [x] "/secure" : pris en charge par apache , authentification par shibolleth (UNIQUEMENT DEV php.info)

- [x] Modification du mot de passe dans formulaire admission

**Comment by glamarca** [comment]
@htmfilho 
C'est OK en dev , verifie également de ton côté , mais il faut surtout me prévenir avant la mise en Qa , car je dois adapter les configurations.

**Comment by htmfilho** [comment]
Je constaté que ça fonctionne correctement. Bravo! On va faire une mise en QA demain, pendant la journée. Merci.
