### ISSUE TITLE
[Configuration] Permettre de modifier les urls déployées sur les serveurs

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#157]
Le fichier urls central permet d'inclure ou non les urls des applications.
Il faudrait pouvoir ajouter ou retirer des urls suivants les environements.

**Comment by glamarca** [comment]
@htmfilho 
J'ai remarqué que certaines urls ne fonctionnais pas sans les urls d'admision.
Je vais donc rétablir admission.
Ce ne sera complètement possible qu'une fois les éléments communs sortis du module admission.
Je ne vais pas faire cela maintenant pour éviter autant que possible de rendre moins stable le dasboard. Cela fera partie du ticket de refactoring à faire une fois que l'encodage est terminé.

Par contre , remettre admission ne demande pas de commit supplémentaire sur ce ticket , donc on peut le fermer.
Je vais changer le titre pour correspondre à ce que j'ai faits.

**Comment by glamarca** [comment]
En dev , pour le test, catalog n'est pas accessible , mais le reste oui.
Une fois le test en dev accepté, je ne supprimerai catalog que de prod (en attendant de pouvoir supprimer admission) , dans les autres environnement, je laisserai tout.

**Comment by htmfilho** [comment]
@glamarca ok, mais je préfère parler avec toi en personne pour cette question. A+
