### ISSUE TITLE
Ajouter une notion de site(localisation) pour les offres

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#168]
Besoin arrivé suite au développement de l'écran comptabilité dans osis-portail [issue#53](https://github.com/uclouvain/osis-portal/issues/53)

la notion de campus est basée sur epc_localisation

**Comment by edd19** [comment]
@basmot @htmfilho Est-ce que je devrais ajouter la localisation dans le modèle **admission/offer_year** ou le modèle **base/offer** ?

**Comment by basmot** [comment]
C'est dans OfferYear que la localisation doit se trouver. 
@htmfilho On devrait aussi déplacer OfferYear de Admission vers Base, non ?

**Comment by htmfilho** [comment]
@basmot oui, mais pas dans ce ticket.

**Comment by htmfilho** [comment]
@verpoorten tester le ticket.

**Comment by verpoorten** [comment]
@htmfilho tant que tu n'as pas fait passer le pull request du ticket 34 je ne sais pas tester car il y a une erreur sur dev dès qu'on veut passer sur l'onglet choix de l'offre

**Comment by htmfilho** [comment]
C'est fait.
