### ISSUE TITLE
Comptabilité - Faire varier le lien d'information dans le cadre affiliation sport en fonction du site de l'offre à laquelle l'étudiant s'inscrit

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#169]
Faire varier le lien d'information dans le cadre affiliation sport en fonction du site de l'offre à laquelle l'étudiant s'inscrit

**Ticket à faire après le ticket [168](https://github.com/uclouvain/osis-portal/issues/168)**

**Comment by htmfilho** [comment]
Lié a uclouvain/osis-louvain-documentation#132

**Comment by htmfilho** [comment]
Dupliqué avec le #53
