### ISSUE TITLE
Curriculum supprimer les enregistrements excédentaires

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#176]
- [ ] Quand on enregistre les études secondaires en encodant un diplôme pour une certaine année académique, puis qu'on enregistre des curriculums.
  Si après on change l'année du diplôme d'études secondaires, en la rendant plus récente il faudrait supprimer les éventuels enregistrements curriculum qui n'ont plus raison d'exister.
- [ ] Vérifier que la duplication fonctionne correctement avec plus de 2 cvs

**Comment by basmot** [comment]
Lié à uclouvain/osis-louvain-documentation#135

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
