### ISSUE TITLE
Créer l'app. base pour les fichiers partagés

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#177]
OSIS-Portal ne marche pas si l'application `admission` ne pas disponible. Il faut mettre dans l'application `base` les fichiers partagé par les autres applications pour être independent de l'admission.

**Comment by glamarca** [comment]
Il reste un problème à la création d'un nouvel utilisateur et qui serait déjà dans person et student : il n'est pas ajouté au groupe student.

**Comment by glamarca** [comment]
Ok en dev pour l'ajout dans groupe students   
- A la creation du user (premiere connexion si dejà dans table Student)
- A l'ajout d'une Person dans Student , si Person liée à un utilisateur
