### ISSUE TITLE
Tester la possibilité d'utiliser Jekyll ou JBake pour la partie publique

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#18]
Utilisation de jekyll + bootsrap
* Format supporté : html , markdonw, textile
* Language de template : liquid ( https://github.com/Shopify/liquid )
* Inclusion des librairies bootstrap SASS
* Tuto , install ... : 
  * https://jekyllrb.com/
  * http://kvurd.com/blog/my-jekyll-blog-setup-bootstrap-sass-pygments/
  * https://scotch.io/tutorials/getting-started-with-jekyll-plus-a-free-bootstrap-3-starter-theme

**Comment by glamarca** [comment]
Voir l'utilisation de Django pour générer des pages statiques , qui semblerais plus adapté à ce qu'on veut.
A tester également.

**Comment by glamarca** [comment]
C'est génial Django!
from django.template.loader import render_to_string

**Comment by glamarca** [comment]
La génération via Django semble être la solution la plus pratique dans notre cas, mais je pense que'elle doit se faire du côté backoffice, en tache de fond , car les changements proviennent de changements faits dans backoffice.
On pourrais alors imaginer également une "preview" possible pour l'utilisateur qui met à jour le catalogue de formation.

**Comment by htmfilho** [comment]
Le back office ne connait pas le front office. Donc, la génération de contenu pour le publique extérieur n'est pas sa responsabilité. Le back office ne fournira que des données multi-usage qui devrait être interprété et transformé par le front office.

Si l'utilisateur a besoin d'un preview, il va appuyer sur le bouton "Preview" pour soumettre les modifications au front office tout de suite, ce qui va générer le contenu statique lorsque les messages arrivent.

**Comment by htmfilho** [comment]
Grâce à Django `render`, Jekyll est pas nécessaire.
