### ISSUE TITLE
Empêcher la navigation entre les onglets selon certaines conditions

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#180]
Critères obligatoires dans l'onglet 'profil' pour pouvoir passer à l'étape suivante : 
- Nationalité
- Résidence

Critères obligatoires dans l'onglet 'choix formation' (choix offre) pour pouvoir passer à l'étape suivante  : 
- Choix de l'offre
- Nationalité du diplôme/titre d'accès au programme

**Comment by verpoorten** [comment]
@glamarca @edd19 Je pense que j'ai réussi à trouver pour la traduction des termes se trouvant dans le javascript.  Pour ceux que cela intéresse c'est dans mon dernier commit sur ce ticket

**Comment by verpoorten** [comment]
@htmfilho A première vue on dirait que certaines choses ne sont pas passées en DEV.  Je devrais approfondir mardi ... :{

**Comment by glamarca** [comment]
@verpoorten 
Les modifs sont faites sur les serveurs.
En dev le js fonctionne.

**Comment by thuyhanghoang** [comment]
Je ne peux pas valider ce ticket car:
1. La liste des pays sont pas pas complet
2. Il faut tester quand des cas d'assimilation sera fait, car si le candidat choisit un autre pays que le UE comme nationalité, il faut qu'il réponse Oui ou Non pour des situations d'assimilation

**Comment by htmfilho** [comment]
Pour la liste des pays, @basmot termine le code pour la synchronisation des données entre osis et osis-portal.

C'est possible d'ajouter les critères d'assimilation dans l'administration: https://dev.studies.uclouvain.be/admin/reference/assimilationcriteria/
@verpoorten il faut ajouter dans les fixtures la creation des critères d'assimilation.

**Comment by verpoorten** [comment]
@htmfilho les fixtures sont déjà présentes dans data.json

**Comment by htmfilho** [comment]
@thuyhanghoang Il y'a quelques pays enregistrés. Est-il possible de tester le ticket avec ceux au lieu de tous les pays existants?

**Comment by thuyhanghoang** [comment]
@htmfilho le but d'empêcher la navigation est pour déterminer c'est une demande d'inscription ou demande d'admission. Donc je ne pense pas que on peut tester ce ticket avant de mettre la liste complète des pays et des cas d'assimilation. Merci!

**Comment by htmfilho** [comment]
Je suis d'accord, mais pour déterminer le type de demande, il suffit de savoir se le pays est dans l'union européenne ou pas. Il y'a 2 pays dans l'union (Belgique et France) et 2 dehors de l'union (Brésil et Russie). Donc, c'est possible de tester le ticket.

La liste de pays vient de l'EPC. La synchronisation de la table pays de l'EPC jusqu'à OSIS-Portal est en cours de development.

**Comment by thuyhanghoang** [comment]
J'essaie de tester des tickets en "Done" qui ne sont pas attribués à moi. Mais ca ne va pas.
Par exemple pour ce ticket, je ne sais pas tester car pour valider l'onglet choix de l'offre, il faut que l'on puisse choisir une offre, ici après avoir choisi "Type d'étude" et "Domaine", il ne fait rien.

Merci de m'attribuer des tickets en Done que je peux tester.

@htmfilho pourrais-tu m'envoyer un mail pour me signaler que je peux commencer à tester?

Merci

**Comment by thuyhanghoang** [comment]
je ne sais pas tester car pour valider l'onglet choix de l'offre, il faut que l'on puisse choisir une offre, ici après avoir choisi "Type d'étude" et "Domaine", il ne fait rien => je ne peux pas choisir une offre

**Comment by verpoorten** [comment]
@thuyhanghoang Il ne se passe rien car tu n'as probablement pas choisi une combinaison qui correspond à une offre.(Si je ne me trompe pas la base de données n'est pas complète.)  Choisis bachelier/architecture ou encore master120/ biologie des organismes et écologie

**Comment by htmfilho** [comment]
@thuyhanghoang Peux-tu tester en considérant le commentaire de @verpoorten , s'il te plait?

**Comment by thuyhanghoang** [comment]
il y a encore le problème de sauvegarde, je dois sauvegarder même si je n'ai pas encore répondu à tous les questions obligatoires. je vais créer un autre ticket
