### ISSUE TITLE
Refactoring du modèle d'admission

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#181]
- [x] Admission.Application : renommer 'belgian_degree' vers 'national_degree' 
- [x] Admission.Application : renommer 'started_samestudies' vers 'started_similar_studies'
- [x] Admission.Application : renommer 'lotery_number' vers 'raffle_number'
- [x] Admission.Application : renommer 'solidary_membership' vers 'solidarity_membership'
- [x] Admission.Application :  renommer 'vae' vers 'valuation_possible'
- [x] Admission.Applicant : renommer 'register_number' vers 'registration_id'
- [x] Admission.Applicant : renommer 'ucl_last_year' vers 'last_academic_year'
- [x] Admission.SecondaryEducation : renommer 'secondary_education_diploma' vers 'diploma'
- [x] Admission.SecondaryEducation : renommer 'daes' vers 'dipl_acc_high_educ' (Diplome d'aptitude d'accéder l'enseignement supérieur)
- [x] Déplacer le modèle 'Admission.GradeType' vers 'Reference.GradeType'
- [x] Déplacer le modèle 'Admission.AssimilationCriteria' vers 'Reference.AssimilationCriteria'
- [x] Supprimer le modèle 'Admission.OfferYearCalendar'
- [x] Renommer le modèle 'Admission.Person' vers 'Admission.Applicant'
- [x] Supprimer la colonne 'Admission.Application.doctorate'
- [x] Supprimer les champs suivants dans la modèle 'Admission.SecondaryEducation' : 
    - admission_exam
    - admission_exam_date
    - admission_exam_institution
    - admission_exam_type
    - admission_exam_result
    - professional_exam
    - professional_exam_date
    - professional_exam_institution
    - professional_exam_result
    - local_language_exam
    - local_language_exam_date
    - local_language_exam_institution
    - local_language_exam_result
- [x] Créer nouveau modèle 'ExamSecondaryEducation' dans 'Admission' avec les champs suivants :
    - secondary_education = models.ForeignKey('SecondaryEducation')
    - admission_exam_type = models.ForeignKey('reference.AdmissionExamType')
    - type = models.CharField(max_length=20, choices=['ADMISSION', 'PROFESSIONAL', 'LANGUAGE'])
    - exam_date = models.DateField(blank=True, null=True)
    - institution = models.CharField(max_length=100, blank=True, null=True)
    - result = models.CharField(max_length=20, choices=RESULT_TYPE, blank=True, null=True)

- [x] Communiquer à l'équipe de repartir d'une DB vierge (dropdb) sur leur poste et sur les serveurs

**Comment by basmot** [comment]
- [ ] Redéplacer AdmissionExamType de Reference vers Admission

**Comment by basmot** [comment]
@htmfilho 
Le champs "result" du nouveau modèle "ExamSecondaryEducation" peut ête différent en fonction du type d'examen. 
Pour 'ADMISSION' et 'PROFESSIONAL' : 
    RESULT_TYPE = (('LOW', 'Moins de 65%'),
                                    ('MIDDLE', 'entre 65% et 75%'),
                                    ('HIGH', 'plus de 75%'))

Pour 'LANGUAGE' : 
    LOCAL_LANGUAGE_EXAM_RESULT_TYPE = (('SUCCEED', _('succeeded')),
                                       ('FAILED', _('failed')),
                                       ('ENROLLMENT_IN_PROGRESS', _('demanded_result')))
Comment gérer cela?
Le champs 'result' contiendrait 6 possibilités : LOW, MIDDLE, HIGH, SUCCESS, FAILED, ENROLLMENT_IN_PROGRESS ?

**Comment by basmot** [comment]
@htmfilho 
Le champs 'Admission.Application.doctorate' est utilisé à plusieurs endroits dans le code, je le supprime quand même (ainsi que toutes ses références dans le code)?
