### ISSUE TITLE
Connexion vers le bucket "performance" dans CouchBase et consultation des documents

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#191]

**Comment by edd19** [comment]
Un document test serait : 
{
  "first_name": "Gerard",
  "last_name": "Morgane",
  "academic_year": "2015-2016",
  "programme": "DROI2MS/IU Master [120] en droit, à finalité spécialisée",
  "learning_units": [
    {
      "acronym": "LDROI2100",
      "title": "Séminaire d'accompagnement du mémoire",
      "credits": 2,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2101",
      "title": "Droit fiscal et droit comptable",
      "credits": 7,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2102",
      "title": "Droit International privé",
      "credits": 6,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2104",
      "title": "Droit des sociétés",
      "credits": 4,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2105",
      "title": "Droit patrimonial de la famille",
      "credits": 4,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2106",
      "title": "Droit de la sécurité sociale",
      "credits": 4,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2107",
      "title": "Droit des sûretés",
      "credits": 4,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2072",
      "title": "Individu, famille et État",
      "credits": 5,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    },
    {
      "acronym": "LDROI2073",
      "title": "Pratiques en droit de la familie",
      "credits": 5,
      "exams": [
        {
          "session": "Jan",
          "score": 12
        },
        {
          "session": "Jun",
          "score": 14
        },
        {
          "session": "Sep",
          "score": 16
        }
      ]
    }
  ]
}
