### ISSUE TITLE
Créer un script qui trie par ordre alphabétique les clés (msgid) dans les fichiers de traduction (django.po)

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#194]
Le script doit contenir deux fonctions publiques: (1) une pour générer un fichier trié et (2) un autre pour remplacer le fichier d'origine par le fichier ordonné.

(1) La fonction reçoit le chemin relatif vers le fichier comme argument et génère un autre fichier avec un nom différent avec le contenu trié. Ex.: `django.po -> django_ordered.po`.

(2) La fonction reçoit le chemin relatif vers le repertoire du fichier trié, remplace le fichier `django.po` par le fichier `django_ordered.po`, et supprime le fichier `django_ordered.po`.

Le script doit être situé à la racine du projet, au même niveau de `manage.py`.

**Comment by glamarca** [comment]
@basmot 
Ce ticket est passé dans osis-common non?

**Comment by edd19** [comment]
@glamarca 
Oui je dois mettre mon script dans osis-common.
