### ISSUE TITLE
Développer la section "Mes formations"

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#2]

**Comment by htmfilho** [comment]
![entity-relationship-model](https://cloud.githubusercontent.com/assets/200272/10667916/1e5764be-78da-11e5-8851-c19c1d68460b.png)

**Comment by htmfilho** [comment]
![bureau-virtuel-mes-formations](https://cloud.githubusercontent.com/assets/200272/10669110/7418ab92-78df-11e5-9afa-8bb107bbc243.jpg)

Lorsque l'utilisateur clique sur le sigle:

![bureau-virtuel-mes-formations-2](https://cloud.githubusercontent.com/assets/200272/10669116/7ab097d0-78df-11e5-8d2c-8bd6750cbbbd.jpg)

**Comment by verpoorten** [comment]
Pour visualiser les données de la bd http://127.0.0.1:8000/admin/
Pour voir la 1ière page de  formation http://127.0.0.1:8000/app
Pour voir la 2ième il faut cliquer sur un lien dans la page

**Comment by htmfilho** [comment]
C'est déjà un mode d'emploi :-) Primitive mais efficace.

**Comment by htmfilho** [comment]
![entity-relationship-model](https://cloud.githubusercontent.com/assets/200272/10755048/9d698f60-7c9b-11e5-8042-dfcf3b21cd94.png)
