### ISSUE TITLE
Créer un compte d'accès pour candidat

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#20]
User Story

**En tant que** candidat

**Je veux** me créer un compte

**de sorte que** me connecter.

**lien ver la documentation**: https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
@htmfilho Le mot de passe doit être de mininum 8 caractères dans osis-portal

**Comment by htmfilho** [comment]
:+1:

**Comment by verpoorten** [comment]
@htmfilho qu'est-ce que je met par défaut dans username?  J'avais mis le lastname, mais l'ennui c'est que le username doit être unique.

**Comment by htmfilho** [comment]
@verpoorten  email?

**Comment by htmfilho** [comment]
La validation de la création de compte ne fonctionne pas correctement. Les message d'erreur ne sont pas présent et le formulaire ne utilise pas Bootstrap.

**Comment by verpoorten** [comment]
Je ne comprends pas ce qui ne te va pas.  Pour moi bootstrap est présent?
J'ai des messages d'erreur, sauf pour le mot de passe

**Comment by htmfilho** [comment]
Dans le formulaire de création de compte d'utilisateur, cliquez sur "Valider" sans remplir le formulaire. Voici le résultat en dev.studies.uclouvain.be:

![admission-user-account-form](https://cloud.githubusercontent.com/assets/200272/15066397/1660431e-1369-11e6-8c6c-fa3cf78c4816.png)
 
Cet formulaire n'utilise pas Bootstrap. Regarde la différence entre un champ texte du login à gauche et un champ texte dans le formulaire de création de compte.

**Comment by htmfilho** [comment]
@glamarca Il me semble que les traductions ne sont pas compilé automatiquement du coté osis-portail: http://dev.studies.uclouvain.be/admission/

Peux-tu remplacer le logo demo par le logo UCL du cotê serveur, s'il te plait? Merci à l'avance.

**Comment by glamarca** [comment]
Non effectivement , lorsque j'avais fait la config il n'y avait pas encore de fichier de traduction et compilemessages fait une erreur quand il n'y a pas de .po.
Je rajoute cela , et je change le lien vers le logo

**Comment by htmfilho** [comment]
C'est vrais. @verpoorten a ajouté ça récemment.

Merci

**Comment by glamarca** [comment]
@htmfilho 
Pour le logo , ça ne fonctionnera pas dans le template : 
le code 
    {% static 'img/logo_institution.jpg' %}
renvoi d'office vers les fichiers static , qui sont généré à partir des fichiers dans base/static.
L'utilisation du logo via l'url défini dans settings c'est pour la production de documents , pour lesquels il faut télécharger l'image et l'inclure, ou de mail ou la reference /static/logo.img ne signifie rien une fois envoyé.
Pour les template , il faut soit récupérer l'image dans le code et le passer à la request,
soit (c'est mieux) créer un dossier statique qui contiendra  les fichiers statique propre à l'institution , et le référencé dans les settings du serveur dans static_dirs.
Je me réassigne le ticket et je ferai cela demain (la deuxième solution)

**Comment by glamarca** [comment]
La compilation des messages est OK.

**Comment by glamarca** [comment]
@htmfilho 
Il n'y a pas de modif à faire dans le code , les modifs sont uniquement du côté des fichiers de config serveur.
Par contre , quelle taille doit avoir le logo de l'institution , car comme tu peux le voir en dev actuellement, si je prend la taille réelle de ml'image correspondant au lien ci-dessus , c'est beacoup trop grand!

**Comment by htmfilho** [comment]
Voilà! 

![logo_ucl](https://cloud.githubusercontent.com/assets/200272/15359968/fb10fa34-1d0b-11e6-8e98-1a8b6a9f7bbc.png)

**Comment by glamarca** [comment]
C'est fait , sur tous les environnements.

**Comment by htmfilho** [comment]
Fonctionnelle en Dev.
