### ISSUE TITLE
Synchronisation des données Osis - OsisPortal pour les formulaires dynamiqes (liés aux offres)

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#201]
Les formulaires dynamiques créés côté Osis (selon les spécifications de chaque Offre) doivent pouvoir être affichés dans le formulaire d'inscription côté Osis-Portal (Form - Question - Response)

**Comment by edd19** [comment]
Liée à l'issue #1239 sur osis-portal.

**Comment by chfivet** [comment]
@htmfilho Je ferme le ticket car celui-ci à été réalisé par @verpoorten via un autre ticket
