### ISSUE TITLE
Convertir xml en json pour les résultats des étudiants.

### ISSUE THREAD

**Issue by edd19** [uclouvain/osis-portal#203]
User Story

**En tant que** [rôle d'utilisateur]

**Je veux** [le but]

**de sorte que** [quelque raison].

**lien vers la documentation** :

**Comment by glamarca** [comment]
@edd19 Voici ce que j'ai comme erreur en dev : 

<RC=0x3B[HTTP Operation failed. Inspect status code for details], HTTP Request failed. Examine 'objextra' for full result, Results=1, C Source=(src/http.c,140), OBJ=ViewResult<rc=0x3B[HTTP Operation failed. Inspect status code for details], value={'status': 'fatal', 'errors': [{'code': 4000, 'msg': 'No primary index on keyspace performance. Use CREATE PRIMARY INDEX to create one.'}], 'requestID': '9d797f9d-69c5-41a5-9fff-332e7fa2f5eb', 'metrics': {'elapsedTime': '1.985086ms', 'resultSize': 0, 'errorCount': 1, 'resultCount': 0, 'executionTime': '1.930672ms'}}, http_status=404>>
Request Method:	GET
Request URL:	https://dev.studies.uclouvain.be/performance/
Django Version:	1.9
Exception Type:	HTTPError
Exception Value:	
<RC=0x3B[HTTP Operation failed. Inspect status code for details], HTTP Request failed. Examine 'objextra' for full result, Results=1, C Source=(src/http.c,140), OBJ=ViewResult<rc=0x3B[HTTP Operation failed. Inspect status code for details], value={'status': 'fatal', 'errors': [{'code': 4000, 'msg': 'No primary index on keyspace performance. Use CREATE PRIMARY INDEX to create one.'}], 'requestID': '9d797f9d-69c5-41a5-9fff-332e7fa2f5eb', 'metrics': {'elapsedTime': '1.985086ms', 'resultSize': 0, 'errorCount': 1, 'resultCount': 0, 'executionTime': '1.930672ms'}}, http_status=404>>
Exception Location:	/home/osis/VENV/lib/python3.4/site-packages/couchbase/n1ql.py in __iter__, line 423
Python Executable:	/usr/bin/python3
Python Version:	3.4.2
Python Path:	
['/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/home/osis/VENV/lib/python3.4/site-packages',
 '/home/osis/www/html/osis_portal/frontoffice/..',
 '/home/osis/www/html/osis_portal/frontoffice/../frontoffice']

Je me suis mis comme étudiant , avec comme registration_id , un des noma qu'il y a dans couchbase.

**Comment by glamarca** [comment]
erreur sur serveur : 
```
<RC=0x3B[HTTP Operation failed. Inspect status code for details], HTTP Request failed. Examine 'objextra' for full result, Results=1, C Source=(src/http.c,140), OBJ=ViewResult<rc=0x3B[HTTP Operation failed. Inspect status code for details], value={'status': 'fatal', 'errors': [{'code': 4000, 'msg': 'No primary index on keyspace performance. Use CREATE PRIMARY INDEX to create one.'}], 'requestID': '9d797f9d-69c5-41a5-9fff-332e7fa2f5eb', 'metrics': {'elapsedTime': '1.985086ms', 'resultSize': 0, 'errorCount': 1, 'resultCount': 0, 'executionTime': '1.930672ms'}}, http_status=404>>
Request Method:	GET
Request URL:	https://dev.studies.uclouvain.be/performance/
Django Version:	1.9
Exception Type:	HTTPError
Exception Value:	
<RC=0x3B[HTTP Operation failed. Inspect status code for details], HTTP Request failed. Examine 'objextra' for full result, Results=1, C Source=(src/http.c,140), OBJ=ViewResult<rc=0x3B[HTTP Operation failed. Inspect status code for details], value={'status': 'fatal', 'errors': [{'code': 4000, 'msg': 'No primary index on keyspace performance. Use CREATE PRIMARY INDEX to create one.'}], 'requestID': '9d797f9d-69c5-41a5-9fff-332e7fa2f5eb', 'metrics': {'elapsedTime': '1.985086ms', 'resultSize': 0, 'errorCount': 1, 'resultCount': 0, 'executionTime': '1.930672ms'}}, http_status=404>>
Exception Location:	/home/osis/VENV/lib/python3.4/site-packages/couchbase/n1ql.py in __iter__, line 423
Python Executable:	/usr/bin/python3
Python Version:	3.4.2
Python Path:	
['/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/home/osis/VENV/lib/python3.4/site-packages',
 '/home/osis/www/html/osis_portal/frontoffice/..',
 '/home/osis/www/html/osis_portal/frontoffice/../frontoffice']
```

Peut-être une erreur du serveur lui-même.

Je me co-assigne le ticket.

**Comment by edd19** [comment]
Oui c'est une erreur du serveur couchbase parce que le bucket ne contient pas de primary index. Il faut faire: CREATE PRIMARY INDEX ON `performance` USING GSI;

**Comment by glamarca** [comment]
Je mettrai OK, et fermerai après test en QA
