### ISSUE TITLE
Compléter le profil candidat

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#21]
User Story

**En tant que** Candidat authentifié

**Je veux** compléter mon profil

**de sorte que** faire une demande d'inscription.

**lien ver la documentation**: https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by abdelayadi** [comment]
Le lien vers la documentation ne fonctionne pas.

**Comment by htmfilho** [comment]
Est-il possible de pousser vos commits de temps en temps afin que je puisse vérifier si elle est dans le bon sens avant la date limite?

Dans le cas où vous n'êtes pas encore dans la branche:

    $ git checkout issue#21

Une fois dans la branche:

    $ git push origin issue#21

Merci à l'avance.

**Comment by verpoorten** [comment]
@abdelayadi Auriez-vous déjà un model à partager?

**Comment by abdelayadi** [comment]
Je n’ai pas encore commencé ce ticket. Je réfléchis au plan d’attaque :)

**Comment by verpoorten** [comment]
Ok merci pour la réponse

**Comment by verpoorten** [comment]
@basmot  @htmfilho J'ai l'impression que c'est ok.  Mais je dois avouer que je ne vois pas bien la différence avec le #22

**Comment by basmot** [comment]
@verpoorten Le candidat peut donc remplir son profil et passer à l'étape suivante, tout est bien sauvegardé?

**Comment by thuyhanghoang** [comment]
Je ne sais pas sauvegarder, il me demande de re-remplir mon email. Il faut le pré-remplir avec l'adresse de son compte.
![image](https://cloud.githubusercontent.com/assets/6651769/19801985/c29a3eb0-9d01-11e6-92a5-65a7d51e1d4b.png)

**Comment by verpoorten** [comment]
@thuyhanghoang Normalement, quand tu cliques sur "sauvegarder", cela t'indique que tu dois remplir le champ obligatoire, mais cela n'empêche pas la sauvegarde

**Comment by verpoorten** [comment]
J'ai corrigé le problème avec l'email, mais je dois voir avec @thuyhanghoang l'autre chose qui semble la déranger

**Comment by thuyhanghoang** [comment]
Attention! Il n'y a pas de message en rouge à côté des champs qui ne sont pas valides. Il y a juste le message d'erreur en haut
![image](https://cloud.githubusercontent.com/assets/6651769/20428147/c99b6e8c-ad87-11e6-8424-b6e9bbb9b559.png)

**Comment by thuyhanghoang** [comment]
- [ ] message d'erreur en rouge en dessous du champ qui n'est pas valide
- [ ] S'il y a un changement et cliquer sur Log out sans sauvegarder => alerter

**Comment by verpoorten** [comment]
- [ ] message d'erreur en rouge en dessous du champ qui n'est pas valide
- [ ] S'il y a un changement et cliquer sur Log out sans sauvegarder => alerter 
- [ ] Quand je navigue en utilisant "Etape Précédente" et "Etape Suivant", il sauvegarde bien mais quand je change l'onglet en cliquant sur le menu à gauche, il ne sauvegarde pas
- [ ] il faut griser l'adresse mail, le mail est juste pour l'information, on ne peut pas modifier ici, car il n'y a pas de vérification de mail ici, ce mail ne sert pas. On utilise son compte (le mail à la création du compte) pour envoyer des confirmations. 
- [ ] A faire plus tard dans le ticket #563

**Comment by thuyhanghoang** [comment]
@verpoorten les 4 derniers points sont ok.
Pour le premier, si on ne sait pas résoudre dans ce ticket, on doit créer un autre ticket pour ne pas oublier de le tester. A toi de voir, au moment que l'on a un ticket pour ça, je peux clôturer ce ticket

**Comment by verpoorten** [comment]
@thuyhanghoang Pour moi le 1ier point est ok aussi.  Il faut que tu m'expliques ce qui ne va pas

**Comment by thuyhanghoang** [comment]
quand j'ai testé, il n'y avait pas le message en rouge en dessous 
![image](https://cloud.githubusercontent.com/assets/6651769/20590138/a2df05c6-b221-11e6-966f-5bdb7ed834d5.png)
