### ISSUE TITLE
Ajout de pièces jointes supplémentaires

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#212]
User Story

En tant que candidat

Je veux joindre à mon dossier (=uploader) toutes les pièces qui me paraissent utiles

de sorte que documenter mon dossier d'inscription

**Comment by edd19** [comment]
Résolu dans le pull request #285

**Comment by thuyhanghoang** [comment]
Le ticket n'est pas du tout fait:
- il faut utiliser le même principe que d'autre partie d'uploader le fichier
- le nom du "type" n'est pas traduit
- on ne peut pas sauvegarder
- la zone description n'apparait que quand on choisit "Autre"

**Comment by htmfilho** [comment]
C'est vrais. Merci pour le feedback.

**Comment by htmfilho** [comment]
Salut, @chfivet La version actuel des pièces jointes supplémentaires ne correspond pas a l'expectatif. Il faut discuter avec @thuyhanghoang le fonctionnement correct et le développer selon les bonnes pratiques introduit par @glamarca . Merci à l'avance.

**Comment by htmfilho** [comment]
@chfivet des nouvelles?

**Comment by chfivet** [comment]
@htmfilho J'y regarde car cela ne fonctionne plus depuis les dernières modifications

**Comment by chfivet** [comment]
@htmfilho @basmot C'est corrigé :-)

**Comment by chfivet** [comment]
@thuyhanghoang Peux-tu tester ce ticket s'il te plaît

**Comment by thuyhanghoang** [comment]
J'ai créé la question de type Upload bouton, je l'ai ajouté 1 option, mais il n'affiche pas la question dans le form
![image](https://cloud.githubusercontent.com/assets/6651769/20565954/c511c018-b193-11e6-957c-71a8401a2253.png)

**Comment by thuyhanghoang** [comment]
Comme expliqué dans le manuel, pour l'onglet Pièces jointes supplémentaires, il faut distinguer des demandes d'inscription et des demandes d'admission https://github.com/uclouvain/osis-documentation/blob/master/doc/business/inscription-en-ligne.adoc

**Comment by htmfilho** [comment]
@chfivet les pièces jointes supplémentaires sont obligatoires pour les admissions, mais pas obligatoires pour les inscriptions.

**Comment by htmfilho** [comment]
l’implémentation ne correspond pas a la demande de l’analyse, donc pour ne pas bloquer la release, une nouvelle implémentation sera gérer dans le ticket #1560.

**Comment by thuyhanghoang** [comment]
@htmfilho n'oublie pas de pointer vers le bon ticket, #1560 n'existe pas. Merci!
