### ISSUE TITLE
Création de l'application dissertation

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#216]
**En tant que** [rôle d'utilisateur]

**Je veux** [le but]

**de sorte que** [quelque raison].

**lien vers la documentation** :

**Comment by glamarca** [comment]
@chfivet 
L'application est bien prise en compte en dev , mais comme il n'y a pas d'url "home" (dan sce style là : url(r'^$', common.home, name='home'),), dev.studies.uclouvain.be/dissertation donne une page d'erreur.

**Comment by chfivet** [comment]
@glamarca @htmfilho Je propsoe que vous fermiez l'Issue.
J'ai bien pris note du fait de la page d'erreur

Une prochaine Issue mettra en place une page de type "home" 

Le but de ce ticket était de créer l'application pour permettre de commencer à programmer celle-ci.
