### ISSUE TITLE
Compléter le profil candidat avec des pièces jointes

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#22]
User Story

**En tant que** Candidat authentifié

**Je veux** uploader ma carte d'identité et ma photo

**de sorte que** compléter mon profil.

**lien ver la documentation**: https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
@basmot @htmfilho Selon vous, que se passe-t-il si une personne upload une image (image1.jpg), puis qu'il revient sur son profil et change l'image de profil avec image2.jpg?

Je supprime image1?

**Comment by verpoorten** [comment]
@thuyhanghoang Pour la pièce d'identité on s'attend à voir un apercu du fichier quand on est dans l'onglet profil?

**Comment by basmot** [comment]
@verpoorten Selon moi, je pense que si l'utilisateur upload un nouveau fichier pour sa photo de profil, son ancien fichier doit être supprimé.

**Comment by chfivet** [comment]
@verpoorten Je suis d'accord avec @basmot
ça évitera une surcharge de fichiers inutiles

PS : Il est intéressant de savoir aussi que chaque fichier upload à une durée de vie qui permet d'effacer automatiquement à partir d'une période donc si on efface pas la première photo lors de l'upload de la deuxième. On peut juste lui dire de prendre en compte la dernière photos upload et le storage_duration s'occupera du nettoyage. Je ne sais pas ce que Beto préfère pour ça.

**Comment by thuyhanghoang** [comment]
@verpoorten oui, je pense que c'est bien de voir une petite photo de la pièce d'identité si elle est uploadée (si ça ne coute pas trop cher évidement).

**Comment by verpoorten** [comment]
Je ne parviens pas à afficher un aperçu du pdf.  Donc j'indique une message d'avertissement quand on a fichier autre qu'image.
**Voir s'il faut approfondir la question d'afficher un apercu du pdf ou encore de convertir les pdf en image????**

**Comment by verpoorten** [comment]
@thuyhanghoang  ok pour photo d'identité et papier d'identité

**Comment by verpoorten** [comment]
Inutile de tester ceci maintenant il vaut mieux attendre que le ticket 62 passe

**Comment by thuyhanghoang** [comment]
- Changer le terme du bouton "Sauvegarder" => "Confirmer" et ne plus demander "Etes-vous sûre de vouloir uploader ce fichier?"
- Il y a un bug quand je clique sur "Sauvegarder" et que je n'ai pas encore choisit le fichier
![image](https://cloud.githubusercontent.com/assets/6651769/18268928/371203fe-7426-11e6-8ab4-ed82fd2d020c.png)
- Quand j'essaie de télécharger un fichier .exe => un bug
![image](https://cloud.githubusercontent.com/assets/6651769/18269227/81273e04-7427-11e6-9339-0c41229b539a.png)

**Comment by htmfilho** [comment]
@thuyhanghoang Le ticket #62 est passé. Peux-tu réessayer ? Merci à l'avance.

**Comment by thuyhanghoang** [comment]
La photo n’apparaît plus sur l'écran après voir Uploadé.
![image](https://cloud.githubusercontent.com/assets/6651769/18427674/fc2cd70c-78c9-11e6-8d2c-3ca441843064.png)

**Comment by thuyhanghoang** [comment]
Quand je supprime la photo et j'ajoute une nouvelle, la photo n'apparait pas toute de suite, il faut l'ajouter encore une fois pour qu'elle est affichée.

**Comment by verpoorten** [comment]
@htmfilho Il faudra vraiment qu'on discute ensemble car j'ai plein de problèmes avec mes tickets.  Tout fonctionne toujours très bien en local, mais sur DEV ça plante...Je n'y comprends rien.  Cela m'arrive désormais sur TOUS mes tickets.  Ce qui ne rend pas mon boulot très crédible :{

**Comment by htmfilho** [comment]
D'accord @verpoorten . On verra ça ensemble lundi alors.

**Comment by verpoorten** [comment]
@htmfilho J'ai peut-être trouvé.  Peux-tu accepté mon pull request?

**Comment by htmfilho** [comment]
Voilà.

**Comment by thuyhanghoang** [comment]
testé, ok
