### ISSUE TITLE
Mettre en œuvre des règles d'autorisation dans le dashboard pour l'enseignant et l'étudiant

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#226]
Lorsque l'étudiant est authentifié, il ne peut pas voir plus que l'icône "Performance".
Lorsque l'enseignant est authentifié, il ne peut pas vois plus que l'icône d'encodage des notes.

Gaëtan a dit:

> Les students sont intégrés dans le bon groupe lors du login, mais ils faut encore faire cela pour les tutors.
> Comme pour l'instant il n'y a pas de table tutor, je ne peux pas les ajouter dans le groupe tutors automatiquement, et donc l'accès à encodage de note n'est pas soumis à permission.
> => si un utilisateur se logge en tant que student , ou même applicant (dans admission) , et qu'il tape /dashboard, il voit l'icone de l'encodage des notes. Même si il ne peut pas télécharger de notes (vu qu'il n'en a pas) , c'est dérangeant. (même si on a deux système d'auth , un user authentifier par l'un ou l'autre , l'est sur les deux)
L'icone performance n'apparait que si l'app est installée et que l'utilisateur possède la permission 'is_student'.
> Voici ce qu'il reste à faire du côté permission/admin/config : 
- Sécurisé l'accès pour les tutor.

**Comment by glamarca** [comment]
@edd19 @htmfilho 

- La permission is_tutor et le groupe Tutors sont déjà crées.
- La table Tutors doit être remplie avec les données qui sont dans osis (-> utilisation des queue pour la migration initiale et pour les migration suivantes : si on ajoute un tutors dans osis, il doit arriver dans la table tutors de osis-portal)
- L'ajout dans le groupe doit être automatique : 
  - Dans la méthode __add_person_to_group(person) de base.models.signals (faire le to do) , cette    methode répond au signal envoyé par auth_louvain lors de la création d'un nouveau user (lors de sa première connexion)
  - Création dune methode similaire à add_to_student_group dans base.models/signals , pour répondre à la création d'un nouvel objet 'Student'
  - Si la table "Tutor" est remplie avant la création des méthoide d'ajout automatique , il faut également géré les tutors existant pour les ajouter tous dans le groupe -> fichier de migration

**Comment by glamarca** [comment]
En Dev : 

vue en tant qu'étudiant (is_student perm)
![image](https://cloud.githubusercontent.com/assets/11191415/17133041/a0f3e0d0-5324-11e6-9eae-6ff4475dfec1.png)

Vue en tant que tutor (is_tutor perm)
![image](https://cloud.githubusercontent.com/assets/11191415/17133067/c8f2c3f8-5324-11e6-8796-bd8b149958dc.png)

Vue ni tutor ni student
![image](https://cloud.githubusercontent.com/assets/11191415/17133094/fb64eb54-5324-11e6-85b2-153fb0d39b72.png)

Vue en tant tutor et student
![image](https://cloud.githubusercontent.com/assets/11191415/17133121/19c5de8c-5325-11e6-9d1d-92170d164190.png)
