### ISSUE TITLE
Choisir l'offre d'étude de candidat

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#23]
User Story

**En tant que** Candidat authentifié

**Je veux** choisir mon offre d'étude (sans les critères spécifiques de l'offre)

**de sorte que** faire une demande d'inscription.

**lien ver la documentation**: https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
@htmfilho @thuyhanghoang 
Dans la doc il y a ceci :
Si le candidat choisit une offre contingentée (KINE1BA, VETE1BA, PSP1BA, LOGO1BA, MD1BA, DENT1BA). **Il faut prévoir un champ de l’offre qui détermine si une offre est contingentée ou pas. Pour les offres contingentées, il y a une date déterminée par la communauté française, ça change chaque année (souvent c’est fin Aout).**   

Comment on fait pour les données en gras ci-dessus?

**Comment by htmfilho** [comment]
J'ai l'impression que ça se règle avec le formulaire dynamique (questionnaire), que permettra la création de formulaire spécifique pour chaque offre. Est-tu d'accord avec moi @thuyhanghoang ?

**Comment by thuyhanghoang** [comment]
@verpoorten @htmfilho 
Pour pouvoir identifier l'offre contingentée, il faut un champ "catégorie" de l'offre
Pour la date c'est une date par année académique

**Comment by htmfilho** [comment]
@thuyhanghoang @jpminet  j'ai besoin d'un ticket juste pour traiter cette situation là (offre contingentée). Merci à l'avance.

**Comment by htmfilho** [comment]
Ce ticket fonctionne comme une Epic. L'epic existe déjà dans le projet uclouvain/osis-documentation.
