### ISSUE TITLE
Modifier le mot de passe perdu

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#24]
User Story

**En tant que** Candidat

**Je veux** modifier mon mot de passe perdu

**de sorte que** récupérer mon accès.

**lien ver la documentation**: https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by htmfilho** [comment]
Bonjour @thuyhanghoang ,

Voici le premier ticket OSIS Portal à tester. Il le testable en dev: https://dev.studies.uclouvain.be/admission/

Je crois que vous ne avez pas encore un compte là bas. Donc, il faut d'abord le créer pour être capable de modifier un mot de passe perdu.

Merci à l'avance.

**Comment by thuyhanghoang** [comment]
@htmfilho @basmot 

Est-ce que c'est normal que je vois l'interface comme ca?
![image](https://cloud.githubusercontent.com/assets/6651769/16989314/0930024a-4e94-11e6-8760-859e4fd15907.png)

![image](https://cloud.githubusercontent.com/assets/6651769/16989445/9192da36-4e94-11e6-9d3d-521f1ec92863.png)

**Comment by thuyhanghoang** [comment]
Quand je clique sur le le pour modifier le mot de passe, il pré-remplit le mot de passe, lequel il a rempli?
![image](https://cloud.githubusercontent.com/assets/6651769/16989612/2ccc5392-4e95-11e6-8867-e9be9251c3aa.png)

**Comment by verpoorten** [comment]
Voici mes commentaires suite au commentaire de Hang ci-dessus

Le nouveau mot de passe est proposé car à un moment l'utilisateur est déjà passé par cette page et a demandé de sauver cette information. (Info gérée alors par le navigateur) 
Je ne trouve pas beaucoup de solution évidente.  Une solution serait de 

- changer le type de l'input de "password" à "text" et trouver un css qui simule le look habituel du mot de passe (mais là je n'ai pas trouvé de solution pour le moment)

(Au niveau du fichier forms.py je n'ai rien trouvé non plus qui pouvait aider)
