### ISSUE TITLE
Visualiser le dashbord d'un étudiant en donnant son registration_id

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#254]
- [x] Groupe 'faculty_administrators'
- [x] Uniquement accessible pour utilisateur 'is_administrator'
- [x] Pas de nécéssité is_staff (pas d'accès aux données)
- [x] Permission spécifique 'is_faculty_administrator'
- [x] Placer sus menu dans menu 'administration'

un utilisateur avec suffisamment de droit peut visualiser le dashbord d'un étudiant comme si c'était lui qui s'y connecte.

**Comment by edd19** [comment]
résolu dans le pull request #286

**Comment by glamarca** [comment]
@edd19 
Je n'ai pas très bien expliqué le ticket, et en plus je dois faire une modif dans l'administration.
En fait, is_faculty_administrator est le seul doit à tester , et il doit faire partie des groupes faculty_administrators et administrators.
De la sorte , il suffit de tester la perm is_faculty_administrator, ce qui simplifie les vue et les template.

Je me réattribue le ticket , et fait également les modifs pour l'accès au bouton administration.
