### ISSUE TITLE
Lors de la migration d'un student ou tutor depuis osis , si la personne existe il ne faut la recréer.

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#256]
Lors de la migration des student et des tutor depuis osis, si la personne associée au tutor ou au student existe déjà dans la DB osis-portal, c'est cette personne qui doit être utilisée pour le la personne associée au tutor ou au student.

C'est valable pour la migration initiale , et pour les migration due aux signaux de création d'un student/tutor dans osis.

Sinon il crée deux personnes, dont l'une qui ne sera jamais liée à un user.
Deux personne sont identiques si elles on le même global_ID.

Dans l'exemple ci-dessous , la première occurence est liée à la table student , et la deuxième à l'utilisateur. Elles ont le même global_id.

![capture du 2016-07-29 14 59 40](https://cloud.githubusercontent.com/assets/11191415/17248918/ba772f6e-559d-11e6-8421-5da060e72695.jpg)

**Comment by edd19** [comment]
Je m'y mets maintenant.

**Comment by edd19** [comment]
Le problème devrait être normalement résoud. #261

**Comment by glamarca** [comment]
Ok, j'avais pas vu l'autre ticket.

**Comment by glamarca** [comment]
OK, testé en QA : 
- Suppression de tout les students
- Migration initiale depuis QA
- Les persons (qui n'avaient pas été supprimées) ne sont pas doublées.
