### ISSUE TITLE
Choix offre d'études - critère complémentaire - texte à afficher

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#26]
User Story

**En tant que** système

**Je veux** afficher un texte d'information statique

**de sorte que** le candidat puisse compléter son choix d'offre

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171587/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by verpoorten** [comment]
Prêt en local

**Comment by verpoorten** [comment]
@chfivet  cela semble tj fonctionnel.  Pour trouver où cela apparait Il faut rechercher un div avec l'identifiant pnl_questions et le javascript associé est dans osis-portal.js

**Comment by chfivet** [comment]
@thuyhanghoang Peux-tu tester ce ticket ? Tu peux choisir Master Spécialisé / Ingénieur de gestion / INGE2MS/G ou créer de nouvelles données dans Form/Question/Option. Je reste disponible en cas de questions

**Comment by thuyhanghoang** [comment]
Pour le label, il faut afficher la description, parce le label est trop court

**Comment by chfivet** [comment]
@thuyhanghoang Le label peut faire 255 caractères, par contre je vais faire en sorte que la description ne soit pas obligatoire et l'afficher si elle est utilisée.

**Comment by thuyhanghoang** [comment]
@chfivet dans ce cas là, il faut agrandir la zone du label pour que je puisse voir et taper ma question alors. Je trouve qu'il faut distinguer 2 choses: le code (court qui sert pour identifier le critère) et une zone description qui est plus large

**Comment by thuyhanghoang** [comment]
testé, ok
