### ISSUE TITLE
Prendre en compte les caractères HTML dans l'affichage des performances 

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#264]
Info : http://stackoverflow.com/questions/2080559/disable-html-escaping-in-djangos-textfield

![image](https://cloud.githubusercontent.com/assets/11191415/17253673/05f3b9bc-55b2-11e6-98e9-15ddf37ff101.png)

**Comment by edd19** [comment]
Voila c'est résoud dans le pull request #275

**Comment by glamarca** [comment]
@edd19 
Parfois la phrase * Attention : à partir de juin 2009, la moyenne est exprimée sur un maximum de 20.
est dans le cadre bleu , parfois elle apparaît or du cadre.
Comme c'est une phrase qui apparaît tout le temps, il faut la mettre en dehors du cadre tout le temps , car si la première phrase du cadre est plus longue, les deux se superposent.

![image](https://cloud.githubusercontent.com/assets/11191415/17524707/f8ca6d74-5e5f-11e6-89c1-9802c6022163.png)

![image](https://cloud.githubusercontent.com/assets/11191415/17524724/08dbeada-5e60-11e6-89b4-58803c6ae447.png)

**Comment by basmot** [comment]
@glamarca Ou en est-on pour ce ticket? On peut le fermer?

**Comment by glamarca** [comment]
@basmot 
Il y aura peut-être encore des amélioration à faire, mais pour le moment c'est bon.
