### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher un champ de capture texte court

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#27]
User Story

**En tant que** système

**Je veux** afficher un champ de capture de texte court (une seule ligne)

**de sorte que** le candidat puisse encoder une information textuelle complémentaire

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171588/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by verpoorten** [comment]
Je considère qu'un enregistrement est automatiquement crée dans la table option quand on a un short_input_text

**Comment by htmfilho** [comment]
On utilise l'administration Django pour créer les formulaires dans OSIS. Après, le donnée est transférer vers OSIS-Portal, qui affiche les questions avec des options. Ce ticket est consacrer a l'affichage d'une question du type texte court e la collecte de la réponse. Il n'y a pas des création de donnée. Pendant le développement, tu peux utiliser l'administration pour créer des données de test.

**Comment by verpoorten** [comment]
C'est bien comme ça que je voyais les choses.

Merci

**Comment by htmfilho** [comment]
Super!

**Comment by thuyhanghoang** [comment]
![image](https://cloud.githubusercontent.com/assets/6651769/20342218/daa0b1be-abe9-11e6-8cc4-2a9c7ccbe257.png)
2 remarques:
- Il faut enlever ce qui préremplir dans la zone de texte
- La description doit etre juste après le label

**Comment by thuyhanghoang** [comment]
testé, ok
