### ISSUE TITLE
[Optimisation] Optimisation de l'usage des queues

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#270]
- [ ] Chaque queue utilise une connexion différent. Vérifier le bon usage.
- [ ] Plutôt que d'envoyer un gros message qui contient tous les object à migrer, utiliser plustôt plein de petits messages contenant chaque fois un nombre limité (voir 1 par message) d'objet.
  De cette façon la consomation est plus rapide et il ne faut pas attendre d'avoir gérer tous les objet pour fermer la transaction dans le cas d'un insert.

**Comment by htmfilho** [comment]
Plus nécessaire après les dernières optimisations.
