### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher un champ de capture texte long

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#28]
User Story

**En tant que** système

**Je veux** afficher un champ de capture de texte long (multiligne)

**de sorte que** le candidat puisse encoder une information textuelle longue

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171585/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by thuyhanghoang** [comment]
@chfivet peux-tu ajouter la question dans cette liste pour que je puisse facilement voir? Merci

**Comment by thuyhanghoang** [comment]
c'est bon!
