### ISSUE TITLE
Problème de traduction (voir pièce jointe)

### ISSUE THREAD

**Issue by mahianth** [uclouvain/osis-portal#287]
[traduction.docx](https://github.com/uclouvain/osis-portal/files/414997/traduction.docx)

**Comment by glamarca** [comment]
@mahianth @htmfilho @basmot @verpoorten 
La traduction de institution_identification se trouve dans 'admission', qui n'est pas obligatoirement déployé.
Comme ça change suivant l'institution, cette traduction doit être dans un dossier locale spécifique à l'institution.
Dans le cas de l'ucl , c'est dans osis_louvain_auth , qui est spécifique à l'UCL
Je vais la déplacer dans le bon module , mais comme il n'est pas accessible en local , la traduction n'apparaîtra plus en local.

Je clôture le ticket et le déplace dans osis-louvain-auth.
 https://github.com/uclouvain/osis-louvain-auth/issues/5

**Comment by glamarca** [comment]
J'utilise ce ticket pour supprimer la référence dans admission

**Comment by glamarca** [comment]
ça ne fonctionne pas : comme louvain-auth est ajouté via un pip du package sur github, compilemessages ne passe pas par là.
Je vais changer l'utilisation de louvain-auth sur les serveurs pour ne plus utiliser le package , mais un sous-module afin que le compilemessage fonctionne
