### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher des boutons radio

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#29]
User Story

**En tant que** système

**Je veux** afficher des boutons radio

**de sorte que** l'utilisateur puisse indiquer un choix unique parmi plusieurs options

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171587/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by verpoorten** [comment]
Quand on met des boutons radios.  C'est automatiquement required non?

**Comment by htmfilho** [comment]
Non. Si la question n'est pas `required` c'est possible de lasser tous les radios désélectionné. Il suffit de ne pas les toucher. Mais si l'utilisateur touche un des options radio le champ est sélectionné et il n'y a plus moins de désélectionné.  Qui a créé le formulaire devrait ajouter une option qui invalide les autres options, telles que: "aucune des options ci-dessus".

**Comment by verpoorten** [comment]
ok

**Comment by thuyhanghoang** [comment]
@chfivet je ne peux plus ajouter une Form, à la création, je ne peux plus choisir une offre

**Comment by thuyhanghoang** [comment]
ni pour créer une Option, je vois la loupe, mais je n'arrive pas à cliquer pour chercher la question

**Comment by thuyhanghoang** [comment]
il faut mettre la description juste en dessous le label de la question

**Comment by thuyhanghoang** [comment]
Il y a un gros problème, je ne sais pas c'est lié à quoi ici. Je choisis une offre FILO2MD (Master120 et Philosophie) pour avoir la liste des questions dynamiques.
Et puis j'ai répondu aux questions demandées. J'ai cliqué sur sauvegarder. Et puis je me déconnecte. Et puis je me reconnecte, je vois l'ancienne offre. Mais le problème est que je choisis de nouveau FILO2MD, je vois tous les réponses que j'ai répondu, elles sont bien sauvegardé

**Comment by thuyhanghoang** [comment]
- il n'affiche pas bien la description de la question, ni des options (voir image jointe)
- il faut avoir la possibilité d'enlever le choix qui est déjà fait. (pour les questions qui ne sont pas obligatoires)
![image](https://cloud.githubusercontent.com/assets/6651769/20394161/e2f64770-acde-11e6-8e22-ecb01cbfcf9f.png)

**Comment by chfivet** [comment]
@thuyhanghoang Je ne pense pas que l'on peut décocher un checkbox, je vais regarder de plus près mais je ne trouve rien là dessus actuellement

**Comment by thuyhanghoang** [comment]
testé, ok
