### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher une/des cases à cocher

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#30]
User Story

**En tant que** système

**Je veux** afficher une ou plusieurs cases à cocher

**de sorte que** le candidat puisse sélectionner une ou plusieurs options

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171587/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by verpoorten** [comment]
@htmfilho Comment traiter le fait que la réponses soit required ou non?  Avec du html/javascript ou lors de la validation du code?

**Comment by htmfilho** [comment]
L’idéal c'est via javascript pour eviter un rafraîchissement du formulaire. Si tu as des difficultés, on peut le faire lundi dans un ticket à part.

**Comment by verpoorten** [comment]
Je vais chercher un peu.  Merci pour ta réponse.  Et maintenant : 
profites de tes congés ! ;-)

**Comment by htmfilho** [comment]
Regarde ça http://jqueryvalidation.org

Merci ;-)

**Comment by thuyhanghoang** [comment]
- il n'affiche pas le label de la question de type "Case à cocher"
- Description doit être affiché juste après le label

**Comment by glamarca** [comment]
@chfivet @thuyhanghoang 
c'est en dev

**Comment by thuyhanghoang** [comment]
- Il n'affiche pas de label de la question de type Case à cocher
- Les autres questions qui ne sont pas dans ma form sont affichées
![image](https://cloud.githubusercontent.com/assets/6651769/20480499/0cbf1eea-afe3-11e6-9aec-9f747ca4a2e0.png)

**Comment by chfivet** [comment]
@thuyhanghoang J'ai retesté chez moi je n'ai pa sle même problème je vais venir voir.
Pour le label de la question qui n'apparait pas, c'est qu'il manque order dans l'option.

**Comment by htmfilho** [comment]
@thuyhanghoang c'est important de mettre le ticket en "Test Failed" après avoir constaté un problème. Ce contrôle est très important pour nous. Merci de faire attention.

**Comment by htmfilho** [comment]
@thuyhanghoang j'ai mal vu. Pardon.

**Comment by chfivet** [comment]
@thuyhanghoang Peux-tu tester ce ticket s'il te plaît

**Comment by thuyhanghoang** [comment]
testé, ok
