### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher un menu déroulant

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#31]
User Story

**En tant que** système

**Je veux** afficher un menu déroulant

**de sorte que** le candidat puisse sélectionner un choix dans une liste

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171587/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by thuyhanghoang** [comment]
- Description de la question doit se trouver juste après le label de la question
- Il faut avoir la possibilité de rien choisi si la question n'est pas obligatoire
- Pourrait-on aligner le choix et la liste? (voir la photo)
![image](https://cloud.githubusercontent.com/assets/6651769/20384778/47464790-acb5-11e6-8b15-aad4cb720a02.png)

**Comment by chfivet** [comment]
@thuyhanghoang Peux-tu tester ce ticket s'il te plaît

**Comment by thuyhanghoang** [comment]
testé, ok
