### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher un bouton d'upload

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#32]
User Story

**En tant que** système

**Je veux** afficher un bouton pour uploader un fichier

**de sorte que** le candidat puisse uploader le fichier requis

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171587/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by htmfilho** [comment]
À regarder ensable parce que l'upload est fait d'une façon très particulière.

**Comment by chfivet** [comment]
@thuyhanghoang

Hello,

Peux-tu tester ça et me dire si tout est bien en ordre ?

Bien à toi,
