### ISSUE TITLE
Changement du status du mémoire par les étudiants

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#322]
Les étudiants peuvent soumettre leurs mémoires au professeur auteur du sujet du mémoire
Le changement de status s'accompagne d'une justificatif encodé lors de la soumission

**Comment by chfivet** [comment]
@matgerard Peux-tu tester en dev l'issue et fermer celle-ci après ta validation ?

**Comment by matgerard** [comment]
ok.
