### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher un lien vers un document à télécharger

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#33]
User Story

**En tant que** système

**Je veux** afficher un lien vers un document à télécharger

**de sorte que** le candidat puisse obtenir le document requis

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171587/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by chfivet** [comment]
Je ferme le ticket suite à une discussion avec Hang et Beto.
