### ISSUE TITLE
Modifier le modèle Offer_proposition pour le lié à Offer

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#330]
Afin de respecter la structure du côté Osis, modifier la liaison de Offer-Proposition vers OfferYear en le liant à Offer.

**Comment by chfivet** [comment]
@matgerard  @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

**Comment by matgerard** [comment]
@chfivet Je veux bien tester mais il me faudrait les droits admin sur le serveur dev de osis-portal... Tu peux me les donner (et sur QA tant que tu y es) ?

**Comment by matgerard** [comment]
Tout semble bon c'est bien lié à offer.
