### ISSUE TITLE
Filtrer les sujets de mémoire suivant les OfferEnrollment de l'étudiant connecté

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#332]
L'étudiant ne peut voir que les sujets de mémoire associé à son Offer.

**Comment by chfivet** [comment]
@matgerard  @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

Si on est pas inscrit on ne voit pas le mémoire

**Comment by matgerard** [comment]
ok aussi !
