### ISSUE TITLE
Choix offre d'études - critère complémentaire - afficher un lien http

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#34]
User Story

**En tant que** système

**Je veux** afficher un lien http

**de sorte que** le candidat puisse être dirigé vers de l'information utile

**lien vers la documentation** : 
[Type d'unite d'info - critères offre.pdf](https://github.com/uclouvain/osis-portal/files/171587/Type.d.unite.d.info.-.criteres.offre.pdf)

**Comment by thuyhanghoang** [comment]
- il faut permettre afficher le texte avant le lien ou le texte sur le lien
- il ne va pas à la ligne entre les 2 questions de http_link (voir image)
![image](https://cloud.githubusercontent.com/assets/6651769/20396237/d7ac911a-ace5-11e6-9e0b-774fc584facb.png)

**Comment by chfivet** [comment]
@thuyhanghoang Peux-tu tester ces tickets s'il te plaît
