### ISSUE TITLE
Ne pas permettre l'edition du mémoire suivant certains statuts

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#343]
L'edition du mémoire ne peut se faire que si il est en Draft ou si il est en attente de réception et que la date de modification du mémoire est inférieur à la date du jours. (start_edit_title, end_edit_title)

**Comment by chfivet** [comment]
@matgerard  @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci ! 

PS : Attention que si la date d'edition du titre est True on a accès à l'edition uniquement du titre

**Comment by matgerard** [comment]
ok
