### ISSUE TITLE
Enlever le jury proposé dans les détails du sujet pour les étudiants

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#344]
Les étudiants ne peuvent pas voir le jury des sujets

**Comment by chfivet** [comment]
@matgerard Du coup si on fait enlève le jury dans les détails des sujets, ça ne sert à rien de pouvoir créer le jury chez les profs sur Osis. C'était pas une demande de leur part ?

**Comment by matgerard** [comment]
Non le jury dans les sujets de mémoire n'était pas une demande de leur part. On a extrapolé ça par nous même.
Leur demande = un jury pour un mémoire. La seule chose est que l'auteur du sujet (= le promoteur) devient automatiquement promoteur du mémoire. Cela fonctionne déjà. Côté OSIS j'ai déjà désactivé la visibilité du jury pour le sujet et la possibilité d'en créer un (il y a juste le promoteur qui est créé automatiquement).

Résumé : jury pour un sujet = ne jamais afficher/créer/modifier (sauf pour le promoteur créé automatiquement)

**Comment by chfivet** [comment]
@ldermine @matgerard Oki donc ils n'ont accès que jury du mémoire.

**Comment by matgerard** [comment]
C'est ça. Il faudra juste afficher le promoteur mais pas besoin de faire une section "jury".
Le promoteur devra être récupéré de proposition_role et pas être l'auteur du sujet ([voir autre discussion à ce sujet](https://github.com/uclouvain/osis-portal/issues/346#issuecomment-241978202))

**Comment by chfivet** [comment]
C'est en ordre 
On a modifié le jury et actuellement il est présent comme souhaité par les utilisateurs
