### ISSUE TITLE
Gestion des readers par les étudiants

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#345]
Les étudiants peuvent changer leurs readers si draft, si autorisation dans offer_proposition

**Comment by chfivet** [comment]
@ldermine @matgerard C'est uniquement en Draft qu'ils peuvent le faire ? Pourtant la gestion du jury apparait plus tard donc leurs mamoires seront d'office plus en Draft. Je peux me tromper.

**Comment by matgerard** [comment]
Il y a deux volets : 
- l'étudiant peut **proposer** des lecteurs pour son projet de mémoire (selon le paramètre bool "student_can_manage_readers")
- l'étudiant peut **voir** son jury complet à partir d'une certaine date (selon le paramètre readers_visibility_date_for_students : à voir si on garde un bool ou si on met deux dates, voir la discussion à ce sujet par mail, je réponds juste après)

Les deux ne sont pas incompatibles.
Je propose ceci : 
- si le mémoire est en **draft** : 
    - seul l'étudiant peut rajouter/voir/modifier/supprimer des readers dans le jury (il ne peut pas ajouter/modifier/supprimer le promoteur ni co-promoteur)
    - les managers ne peuvent **pas** modifier/rajouter dans le jury (à coder côté osis)
    - l'étudiant peut donc voir le jury, mais ce n'est pas un souci vu que lui seul peut rajouter des readers dedans à ce moment là
- dès que le mémoire **n'est plus en draft** : 
    - les managers peuvent gérer le jury (rajouter/supprimer/modifier) y compris les readers rajoutés par l'étudiant
    - l'étudiant ne voit plus le jury, sauf si les dates le lui permettent
    - l'étudiant ne peut plus modifier le jury, seulement le voir tel qu'il a été fait par les managers (en ayant gardé éventuellement les readers que l'étudiant a proposés)


Cela permet de gérer tout le bazar sans changer le modèle :-)
OK pour vous ?

**Comment by ldermine** [comment]
oui c'est nickel.

Perso je suis pour le champ date car ça automatise/optimise 
l'administration.
Une case à cocher, c'est trop manuel, il ne faut pas que le secrétariat 
oublie...

**Comment by chfivet** [comment]
@matgerard  @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

**Comment by matgerard** [comment]
ok
