### ISSUE TITLE
Modifier l'auteur d'un sujet en promoteur

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#346]
L'étudiant ne voit plus auteur dans les détails du sujet associé à son mémoire mais promoteur

**Comment by chfivet** [comment]
@ldermine @matgerard L'auteur du sujet peut ne pas être le promoteur d'après moi. Vous en pensez quoi ?

**Comment by matgerard** [comment]
Deux choses à distinguer : 
- la personne qui crée le sujet : cela peut être le prof (qui est promoteur) ou un manager (qui choisit un prof comme promoteur)
- le promoteur : c'est en réalité ce qu'on a appelé "auteur" : c'est le prof lui-même quand il crée un mémoire pour lui, ou c'est celui qui est choisi par le manager qui crée le sujet

Il ne faut pas mélanger les deux notions mais il serait intéressant de garder les deux.
Je propose ceci : 
- le field "auteur" du mémoire est la personne qui a créé le mémoire : 
    - le prof s'il crée un mémoire pour lui-même
    - le manager s'il crée un mémoire pour un prof
- le promoteur du mémoire est créé dans proposition_role comme c'est déjà le cas pour l'instant

Cela permet de gérer les deux notions sans modifier notre modèle.

Pour ce ticket : en fait l'étudiant ne devra pas voir l'auteur du sujet (il ne doit pas savoir si c'est le prof qui a créé le sujet ou un manager) mais il devra voir le promoteur qui vient de proposition_role.
Il y a un truc à coder côté osis : le fait que l'auteur soit la personne qui crée le sujet et non le promoteur d'office. Je m'en charge.

**Comment by chfivet** [comment]
@matgerard Je propose de juste changer la traduction de auteur en promoteur ça irait ça pour toi ?

**Comment by matgerard** [comment]
J'ai mis à jour mon commentaire ci-dessus avec les bonnes infos.

**Comment by chfivet** [comment]
@matgerard  @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

**Comment by matgerard** [comment]
OK.
