### ISSUE TITLE
Placer la limite d'un projet de mémoire soumis à un projet de mémoire soumis par programme de cours

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#347]
Les étudiants peuvent soumettre un mémoire par programme de cours et pas une seule soumission au total.

**Comment by chfivet** [comment]
@matgerard  @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

**Comment by matgerard** [comment]
ok
