### ISSUE TITLE
Compléter diplômes et examens - écran d'entrée (écrans : initial et state2)

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#35]
User Story

**En tant que** candidat

**Je veux** spécifier si j'ai un diplôme secondaire et un examen de maitrise du français

**de sorte que** constituer mon dossier d'inscription

**lien vers la documentation** : https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Base pour la réflexion

A ajouter dans application?  ou ailleurs?  Nouvelle table

BELGIAN_COMMUNITY_TYPES = (
    ('FRENCH', 'Communauté française de Belgique'),
    ('GERMAN', 'Communauté Germanophone'),
    ('NEDERLANDS', 'Communauté Néerlandophone'),
    )

EDUCATION_TYPE =(
  ('GENERAL_TRANSITION', 'Enseignement de formation générale'),
  ('TECHNIQUE_TRANSITION', 'Technique de transition'),
  ('ARTISTIC_TRANSITION', 'Artistique de transition'),
  ('TECHNIQUE', 'Technique de qualification'),
  ('ARTISTIC', 'Artistique de qualifiation'),
  ('PROFESSIONAL', 'Enseignement professionel'),
  ('PROFESSIONAL_MATURITY', 'Enseignement professionel-Examen de maturity'),
)

RESULT_TYPE =(
  ('LESS_65', 'Moins de 65%'),
  ('BETWEEN_65_75', 'Entre 65 et 75%'),
  ('MORE_75', 'Plus de 75%')
)

EXAM_RESULT_TYPE =(
  ('SUCCEED', 'Réussite'),
  ('FAILED', 'Echec'),
  ('ENROLLMENT_IN_PROGRESS', 'En cours d\'inscription à la session mentionnée')
)

BACCALAUREAT_TYPE=(
  ('NATIONAL', 'Baccalauréat national (ou diplôme d'état, ...)'),
  ('EUROPEAN', 'Baccalauréat européen (Schola Europea)'),
  ('INTERNATIONAL', 'Baccalauréat international(IBO)')
)

LANGUAGE_TYPE = (
  ('FRENCH','Français'),
  ('DUTCH','Néerlandais'),
  ('ENGLISH','Anglais'),
  ('GERMAN','Allemand'),
  ('ITALIAN,'Italien'),
  ('SPANISH','Espagnol'),
  ('PORTUGUESE','Portuguais')
)

EQUIVALENCE_TYPE = (
  ('YES','Oui'),
  ('NO','Non'),
  ('IN_PROGRESS','En cours de demande')
)
ADMISSION_EXAM_TYPE = (
('FIRST_CYCLE','Examen d\'admission aux études universitaires de 1er cycle'),
('MATURITY','Examen de maturité(ou d\'aptitude) de la Communauté française de Belgique'),
('FIRST_CYCLE_CIVIL-ENGINEER','Examen spécial d\'admission aux études universitaires de 1er cycle de l\'ingénieur (ingénieur civil)'),
('OTHER_EXAM','Autre examen ou épreuve d\'admission'),
)

sec_obtention_year = models.IntegerField()#belgian #année d'obtention du diplome secondaire
sec_in_belgium = models.BooleanField()#belgian # études effectuées en Belgique ou à l'étranger.  Est-ce vraiment intéressant à stocker?
sec_community  = models.CharField(max_length=20, choices=BELGIAN_COMMUNITY_TYPES)#belgian#la communauté si diplome belge
sec_CESS_school = models.ForeignKey('')??Existe-t-il déjà une table de référnce#belgian
sec_CESS_other_school_name =  models.CharField(max_length=255)#belgian
sec_CESS_other_school_city =  models.CharField(max_length=255)#belgian
sec_CESS_other_school_postal_code = models.CharField(max_length=20)#belgian
sec_education_type =   models.CharField(max_length=25, choices=EDUCATION_TYPE)#belgian
sec_other_education_type =  models.CharField(max_length=255)#belgian
sec_daes = models.BooleanField()#belgian
sec_repeated_grade = models.BooleanField()#belgian
sec_re_orientation = models.BooleanField()#belgian
sec_result =   models.CharField(max_length=25, choices=RESULT_TYPE) #belgian and foreign
sec_diploma_recto = models.FileField()#belgian and foreign
sec_diploma_verso = models.FileField()#belgian and foreign
sec_foreign_baccalaureate_diploma = models.CharField(max_length=25, choices=BACCALAUREAT_TYPE)
sec_host_country_diploma = models.ForeignKey('Country')
sec_language_diploma = models.CharField(max_length=25, choices=LANGUAGE_TYPE)
sec_other_language_diploma = models.ForeignKey('Language')
sec_belgian_equivalence = models.CharField(max_length=25, choices=EQUIVALENCE_TYPE)
sec_equivalence_recto = models.FileField()# foreign
sec_equivalence_translation_verso = models.FileField()# foreign
sec_note_sheet_recto = models.FileField()# foreign
sec_note_sheet_verso = models.FileField()# foreign
sec_diploma_translation_recto = models.FileField()# foreign
sec_diploma_translation_verso = models.FileField()# foreign
sec_note_sheet_translation_recto = models.FileField()# foreign
sec_note_sheet_translation_verso = models.FileField()# foreign

#examen d'admission
admission_exam = models.BooleanField()
admission_exam_date = models.DateField()
admission_exam_school =  models.CharField(max_length=255)
admission_exam_type =  models.CharField(max_length=255, choices=ADMISSION_EXAM_TYPE)
admission_exam_type_other  =  models.CharField(max_length=255)
admission_exam_result =   models.CharField(max_length=25, choices=RESULT_TYPE)
admission_exam_certificat = models.FileField()

#examen de maitrise de la langue française
french_exam_enrollment = models.BooleanField()
french_exam_date = models.DateField()
french_exam_school =  models.CharField(max_length=255)
french_exam_result =   models.CharField(max_length=25, choices=EXAM_RESULT_TYPE)
french_exam_certificat = models.FileField()

**Comment by htmfilho** [comment]
Poison d'avril! :D Bien joué!

**Comment by verpoorten** [comment]
@htmfilho Beto, puis créer ces champs dans le model application.py
(études secondaires en anglais -> secondary education)

Voici les champs que je propose pour ce 1ier écran.  (Dans l'ordre d'apparition de l'écran)

sec_diploma = models.BooleanField()

sec_obtention_year = models.IntegerField()#belgian #année d'obtention du diplome secondaire
ou 
sec_obtention_year = models.ForeignKey('AcademicYear')#va-t-on créer des académic years < à 2015???

sec_in_belgium = models.BooleanField()#belgian # études effectuées en Belgique ou à l'étranger. Est-ce vraiment intéressant à stocker?

**Comment by verpoorten** [comment]
Problèmes encore existant
Dans tous les écrans:

- [ ] les boutons d'upload sont non-fonctionnels

Dans l'écran initial

- [ ] Il est noté dans la doc "Si l'étudiant a déjà l'information d'un de ces blocs dans son profil, ce bloc n'apparait pas" or pour le moment on n'a pas cette information dans le profil

Dans l'écran state 2

- [ ] Dans la doc il est noté que "Si l'étudiant a déjà l'information de ses études 
secondaires dans son profil, ce bloc n'apparait pas" or pour le moment on n'a pas cette information dans le profil

Dans l'écran 33

- [ ] Je ne sais pas trop quoi faire avec cette élt de la documentation "Si le candidat fait une demande à un offre Ingénieur civil" (FSA1BA ou ARCH1BA) =>Il est obligé de coché sur le 3e choix => une vérification pour pouvoir passer l'étape suivante, s'il ne choisit pasle 3e examen => il faut avoir un message".  On a rattacher les infos d'études secondaires à la person(person.py) et non à la demande (application.py)

**Comment by verpoorten** [comment]
@htmfilho Dans le cadre de ce ticket je me demande s'il ne faut pas envisager d'importer depuis epc les données de la table etd_eco_sec

**Comment by verpoorten** [comment]
Remarques avant travail:

Suite aux modifications de la navigation #67, certaines informations ne s'affichent plus très bien faute de place.

**Comment by htmfilho** [comment]
Ticket #50.

**Comment by htmfilho** [comment]
Ce ticket fonctionne comme une epic. L'epic existe déjà: uclouvain/osis-documentation.
