### ISSUE TITLE
Appliquer le Boolean de visibilité des readers d'un mémoire au étudiant

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#352]
readers_visibility_date_for_students = models.BooleanField(default=False)

**Comment by chfivet** [comment]
@ldermine @matgerard Il faut définir si on va utiliser deux dates ou le Bollean.
Moi je suis pour le Bollean et de modifier readers_visibility_date_for_students en readers_visibility_for_students.

Votre avis ?

**Comment by matgerard** [comment]
Deux dates, comme convenu dans la discussion par mail : 
- start_jury_visibility
- end_jury_visibility

**Comment by chfivet** [comment]
@matgerard  @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

PS : on utilise pas un Bolléen mais deux dates

**Comment by matgerard** [comment]
ok !
