### ISSUE TITLE
Problème sur DEV lors de l'upload de fichier avec un caractère accentué dans le nom

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#353]
Lors des tests du ticket #50  j'ai découvert que sur DEV si lors de l'upload d'un fichier je sélectionne un fichier avec un accent dans le nom ça provoque une erreur. (voir ci-dessous). 
Pourtant en local en partant de dev ça fonctionne correctement

UnicodeEncodeError at /admission/upload/

'ascii' codec can't encode character '\xe9' in position 29: ordinal not in range(128)

- [x] dev
- [x] qa
- [x] prod

**Comment by glamarca** [comment]
Additional Tweaking

If you're taking advantage of the great Internationalization features of Django you may come across a curious problem. Namely, uploading of non-ascii filenames with the Django storage system with the default apache settings on most systems will trigger UnicodeEncodeError exceptions when calling functions like os.path(). To avoid these issues, ensure that the following lines are included in your apache envvars file (typically found in /etc/apache2/envvars).

export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
This error likely wont rear its head during development on the test server as, when run from the command line, the ./manage.py script inherits the users language and locale settings.
