### ISSUE TITLE
On dirait que l'affichage des messages d'erreur ne fonctionne pas sur DEV

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#354]
Erreur dans la console web lors des tests sur dev pour le ticket #180  : 
10:04:35.645 SyntaxError: expected expression, got '<'1 jsi18n:1:0

Pourtant en local en partant de dev ça fonctionne correctement

**Pour tester :** 
à partir de l'onglet profil NE PAS spécifier de nationalité, puis cliquer sur le bouton vers l'étape suivante.  Quand tout va bien un message s'affiche dans un cadre jaune en haut de l'écran.

**Comment by glamarca** [comment]
/jsi18n doit être ajouté dans les exception d'authentification shibboleth
![image](https://cloud.githubusercontent.com/assets/11191415/18008290/ccf57aae-6ba7-11e6-87f4-14fdfc13f867.png)
- [x] Dev
- [ ] Qa
- [ ] Prod
