### ISSUE TITLE
Compléter diplômes et examens - infos secondaire belge

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#36]
User Story

**En tant que** candidat

**Je veux** remplir les informations relatives à mes études secondaires en Belgique (CESS)

**de sorte que** constituer mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
@thuyhanghoang Dans la doc de visual paradigm il est noté : 
"_Si c'est une demande d'inscription
on ne demande pas le relevé de note. Si c'est 
une demande d'admission, l'étudiant doit 
joindre le relevé de note de ses études 
secondaires_"
Pourrais-tu me rappeler comment on différencie une demande d'inscription d'une demande d'admission

**Comment by thuyhanghoang** [comment]
Sur le profil du candidat, pour détermine une demande est une demande d'inscription ou une demande d'admission, on se base sur: la nationalité, et le titre d'accès. Et si tu veux voir le détail pour les dates, il est sur le diagram DistinctionEtudiants (Basic Diagram) dans Visual Paradigm
Pour les etudes contingentées et les offres certificats MSP9CE et MSC9CE => c'est un traitement spécial pour savoir si c'est une demande d'inscription ou une demande d'admission.

**Comment by verpoorten** [comment]
@htmfilho Pourrais-tu me rappeler le principe pour le champ adhoc.  adhoc = true quand ce sont des données connues et adhoc = false quand c'est un champ "autre à préciser"

**Comment by htmfilho** [comment]
C'est l’inverse: `adhoc=True` quand c'est un champ "autre à préciser" et `adhoc=False` quand ce sont des données bien connu de l'UCL.

**Comment by verpoorten** [comment]
Bizarre quand on voit la définition ici

**Comment by htmfilho** [comment]
Définition d'ad hoc: "made or done without planning because of an immediate need" (http://www.merriam-webster.com/dictionary/ad%20hoc)

C'est pour ça qui `adhoc=True` quand l'utilisateur informe "autre à préciser". Parce que c'est une valeur non planifié mais de besoin immédiate.

**Comment by verpoorten** [comment]
Finalement j'ai tout fait dans le ticket #35

**Comment by verpoorten** [comment]
Problème encore existant
Dans tous les écrans:

- [ ] les boutons d'upload sont non-fonctionnels

Dans l'écran initial

- [ ] Il est noté dans la doc "Si l'étudiant a déjà l'information d'un de ces blocs dans son profil, ce bloc n'apparait pas" or pour le moment on n'a pas cette information dans le profil

Dans l'écran state 2

- [ ] Dans la doc il est noté que "Si l'étudiant a déjà l'information de ses études 
secondaires dans son profil, ce bloc n'apparait pas" or pour le moment on n'a pas cette information dans le profil

Dans l'écran 33

- [ ] Je ne sais pas trop quoi faire avec cette élt de la documentation "Si le candidat fait une demande à un offre Ingénieur civil" (FSA1BA ou ARCH1BA) =>Il est obligé de coché sur le 3e choix => une vérification pour pouvoir passer l'étape suivante, s'il ne choisit pasle 3e examen => il faut avoir un message".  On a rattacher les infos d'études secondaires à la person(person.py) et non à la demande (application.py)

**Comment by verpoorten** [comment]
@htmfilho @basmot Pour moi tout sera ok avec le ticket #35.  Je ne vais donc rien commiter pour ce ticket et si tout est ok sur le #35 on pourra aussi cloturer celui-ci

**Comment by verpoorten** [comment]
J'encode des études secondaires pour une personne et quand je reviens sur l'onglet c'est la case non de "
Avez-vous obtenu un diplôme de fin d'études secondaires ou allez-vous l'obtenir cette année? " qui est cochée

**Comment by verpoorten** [comment]
Bizarre car en local ça fonctionne bien????

**Comment by verpoorten** [comment]
Je pense que le problème était dût au fait que je m'étais connectée précedemment avec Shibboleth

**Comment by verpoorten** [comment]
@thuyhanghoang Ne pas faire attention à l'affichage de la validation, cela fera l'objet d'un ticket plus tard (voir avec Beto)

**Comment by thuyhanghoang** [comment]
@verpoorten tu veux dire quoi "à l'affichage de la validation"?

**Comment by verpoorten** [comment]
@thuyhanghoang Le fait que les elements du menu deviennent vert ou reste orange, n'est pas toujours au point.  Le style utilisé pour afficher les messages

**Comment by thuyhanghoang** [comment]
Pouvez-vous corriger ce problème pour que je puisse tester?
![image](https://cloud.githubusercontent.com/assets/6651769/18672250/a8555dfa-7f47-11e6-96f7-7d8c5be08942.png)

Merci!

**Comment by verpoorten** [comment]
@thuyhanghoang problème d'hier corrigé

**Comment by verpoorten** [comment]
On dirait que les l type d'enseignement ne sont pas chargés

**Comment by thuyhanghoang** [comment]
Des problèmes à régler:
- La liste "l'année académique d'obtention" n'a que 2 années => on ne sais pas tester d'autres situations (par exemple des questions dans le bloc DAES)
![image](https://cloud.githubusercontent.com/assets/6651769/19146001/d7ab0d40-8bb1-11e6-835d-d7288c9420ce.png)
== =>>> il faut remplir par défaut l'année académique en cours; la liste est trié par l'ordre décroissante
- La liste des localités sont parfois en majuscule par fois en minuscule ===>>> si c'est possible de mettre la première lettre en Majuscule (ex: Court-Saint-Etienne)
- Le menu déroulant pour le code postal n'est pas alligné
- Code postal disparaît quand on choisit une localité ===>>> il faut pré-remplir le code postal. Dans V2, il pré-remplit aussi un établissement. Il faut faire la même chose quand on choisit le code postal. Pourrait-on en discuter?
- La liste des établissements n'est pas triée ===>>> il faut la trier par l'ordre alphabétique
- La partie concernant "Autre établissement" n'est pas évident pour des candidats ===>>> Tous ces champs n’apparaît que quand "Autre établissement" est coché.
- J'ai fait une demande d'admission et il ne me demande pas de joindre le relevé de notes
- Il manque le bloc "Quel type d'enseignement avez-vous suivi?"
- Il faut ajouter le bloc "Parcours"

**Comment by verpoorten** [comment]
Pour le 1ier point : " _La liste "l'année académique d'obtention" n'a que 2 années => on ne sais pas tester d'autres situations (par exemple des questions dans le bloc DAES)_ "
J'utilise les informations existantes dans la table academic_year or il n'y a que 2 années.  Vu que c'est une foreign key dans secondary Education  : academic_year = models.ForeignKey('base.AcademicYear', blank=True, null=True) , je pense que je n'ai d'autre choix que d'ajouter des académicyears sur DEV

**Comment by philbru** [comment]
Le pavé "Quel type d'enseignement avez-vous suivi (ou suivez-vous)? *" doit apparaître dès le choix de la communauté, quand on a choisi étude secondaires en Belgique.
Quand on n'a pas trouvé l'établissement, les champs "Nom de l'établissement", "Localité", "Par code postal" ne sont pas contrôlés en longueur: on ne doit pas pouvoir dépasser la longueur maximale.
Le second choix de communauté n'est pas utile.
"Par code postal" doit être changé en "Code postal"
Il n'y a pas de contrôle de validité du code postal
Le pavé "Quel type d'enseignement avez-vous suivi (ou suivez-vous)? *" est affiché actuellement quand on choisit la communauté dans le second choix de communauté (qui déjà n'est pas utile).
Quand on choisit "Autre enseignement", la longueur du champ "A spécifier" n'est pas contrôlée; on ne doit pas pouvoir dépasser la longueur du champ.
"Quel résultat avez-vous obtenu? * " pouvoir indiquer "résultat non encore disponible".
Si on coche "Autre enseignement", la coche supérieure n'est pas décochée
Si on charge une pièce jointe, l'action n'est pas immédiatement visible.  Le bouton est changé en vert si on change d'onglet.

**Comment by verpoorten** [comment]
@philbru Pour la validation du code postal Beto à suggérer de créer un nouveau ticket #552 pour plus tard

**Comment by htmfilho** [comment]
@philbru le besoin de valider ce champ là doit être présent dans la documentation aussi. Merci à l'avance.

**Comment by thuyhanghoang** [comment]
- [ ] Comme les autres listes dans cette fenêtre sont en verticales, il faut aussi mettre cette liste en verticale
![image](https://cloud.githubusercontent.com/assets/6651769/20431543/d741c67c-ad9a-11e6-9be9-c68bde5c459f.png)
 - [ ] dans la liste des localité, il y a Brussel et Bruxelles
- [ ] quand je choisis Bruxelles, il n'y a qu'un seule choix dans le code postal c'est 1060 => pas normal
- [ ] des caractères bizarres
![image](https://cloud.githubusercontent.com/assets/6651769/20431682/ac8964a2-ad9b-11e6-9900-f54be15ebd5f.png)
- [ ] Nom de l'établissement (quand on veut introduire une établissement)
![image](https://cloud.githubusercontent.com/assets/6651769/20431794/3d34610a-ad9c-11e6-89f6-f009d189c206.png)
- [] Je ne sais toujours pas tester le point sur la validité des localités

**Comment by verpoorten** [comment]
- [ ] Encore a voir
- [ ] C'est des données issues de EPC je ne sais pas y faire grand chose
- [ ] C'est des données issues de EPC je ne sais pas y faire grand chose
- [ ] Les données étaient comme ça en BD.  J'ai corrigé manuellement
- [ ] Encore a voir
- [ ] Ce sera fait dans un autre ticket plus tard
- [ ] Encore a voir

**Comment by verpoorten** [comment]
@basmot @htmfilho Il faudra qu'on discute car on va devoir ajouter des champs dans secondary_education
![40](https://cloud.githubusercontent.com/assets/5947635/20442369/a313e6ae-adc8-11e6-8497-35af43b9d59a.png)

**Comment by htmfilho** [comment]
@verpoorten Ok, mais pas dans ce ticket :-) J'ai déjà fusionné 10 pull requests pour ce lui ci. Incroyable!

**Comment by verpoorten** [comment]
Beto a vérifié le fonctionnement dans epc_V2 il y a aussi Bruxelles et Brussels. Ces données sont issues de epc(etd_eco_sec), on ne peut donc rien y changer.
![40_1](https://cloud.githubusercontent.com/assets/5947635/20476325/b6ef38fe-afd0-11e6-84d5-0ea535da7768.png)

**Comment by thuyhanghoang** [comment]
- [ ] Le caractère bizarre est toujours là
![image](https://cloud.githubusercontent.com/assets/6651769/20569997/4376b874-b1a2-11e6-8fb7-dabadab63fbe.png)
- [ ] Je n'ai pas demandé de changer le texte "Nom de l'établissement", il faut agrandir la zone
![image](https://cloud.githubusercontent.com/assets/6651769/20570067/7a479f9e-b1a2-11e6-8958-39c685e3fbd9.png)

**Comment by thuyhanghoang** [comment]
testé
