### ISSUE TITLE
Utiliser une adresse mail de developpement pour les destinataire lors de l'envoi d'un mail hors environnement de production

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#365]
L'envoi d'un mail à son destinataire rel ne doit se faire qu'en situation de production.
En local, le mail envoyé est enregistré dans un fichier sur le disque.
Pour les environnement serveurs hors production, il faut pouvoir vérifier ce mail, sans aller sur le serveur.
On utilisera pour cela un destinataire de développement auquel seront envoyés les mails, et qui est accessible à l'équipe de développement et aux testeurs.
L'adresse utilisée, ainsi que l'environnement sont définis dans le fichier settings et modifié sur les serveurs.
La logique qui teste l'environnement et modifie le destinataire est placée dans osis-common. 

lié à : https://github.com/uclouvain/osis-common/issues/36

**Comment by glamarca** [comment]
Problème à résoudre : 
l'email d'activation ne fonctionne pas

ex : 
Not Found: /admission/admission/user/88f38d3c-e9fa-49a0-b16f-9fab5b2a5534/activation

**Comment by htmfilho** [comment]
@glamarca , Le `send_mail` en locale ne fonctionne plus. Les fichiers de message ne sont pas stockés dans le dossier `base/tests/sent_emails`. Le `send_mail` fonctionne en `dev` parce que les emails sont envoyé vers la boite Gmail.

**Comment by glamarca** [comment]
@htmfilho 
Je regrde ça

**Comment by glamarca** [comment]
Les templates doivent être chargé, sinon cela ne fonctionne pas : 
```
(VENV)$ python3 manage.py loaddata message_templates
```
