### ISSUE TITLE
Compléter diplômes et examens - infos secondaire étranger

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#37]
User Story

**En tant que** candidat n'ayant pas de CESS (diplôme belge)

**Je veux** compléter les informations d'études secondaires étrangères

**de sorte que** constituer mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Finalement j'ai tout fait dans le ticket #35

**Comment by thuyhanghoang** [comment]
@verpoorten @htmfilho je ne sais toujours pas me connecter pour tester
![image](https://cloud.githubusercontent.com/assets/6651769/18711638/2874f2ac-800b-11e6-96ec-c25180f817d4.png)

**Comment by verpoorten** [comment]
champ Régime linguistique décalé à l'écran

**Comment by thuyhanghoang** [comment]
- La liste des année académique n'est pas complet
- le combo box "si autre régime linguistique" est trop à droite, il faut réduire la taille d'autre parties pour que le checkbox "précisez" reste sur la même ligne.
- La question concernant la décision d'équivalence par les services de la communauté française n’apparaît que quand le candidat choisit un diplôme Baccalauréat national.

**Comment by thuyhanghoang** [comment]
- [] au moment que l'on choisit le "Régime linguistique", on perd le choix de "Pays organisateur" et on ne peut plus choisir le pays
- [] quand je choisis "Autre régime linguistique", je n'ai pas la possibilité de le préciser
- [] Ajouter "pas encore de résultat" dans le bloc "Résultat"

**Comment by verpoorten** [comment]
@thuyhanghoang pour le point 2 c'était un problème dans les bases de données

**Comment by thuyhanghoang** [comment]
@verpoorten mais quand il s agit un autre régime linguistique => le candidat doit préciser le quel (en tapant un régime

**Comment by verpoorten** [comment]
@thuyhanghoang ce n'est pas ce que j'avais compris via la documentation 
![37](https://cloud.githubusercontent.com/assets/5947635/20429878/89b62816-ad91-11e6-96fa-b0b6f6118ccc.png)

**Comment by thuyhanghoang** [comment]
Dans ce cas là, c'est mieux que tu mélanges tous les régimes dans la liste (il ne faut pas séparer en 2).

Pour Autre régime: il faut juste remplacer le menu déroulant par une simple texte. Et garder la logique que si "autre régime linguistique" est coché, il faut faire 3 choses: - supprimer le choix dans le menu déroulant de "Régime linguistique"; - rendre le menu déroulant grisé; - rendre la zone texte éditable. Je mettrais à jour le manuel.

![image](https://cloud.githubusercontent.com/assets/6651769/20430676/023fd968-ad96-11e6-83df-cd07699019e1.png)

**Comment by thuyhanghoang** [comment]
les 2 autres points sont ok

**Comment by verpoorten** [comment]
@htmfilho Suivant les remarques de Hang pour l'autre langue. Comment je fais pour ajouter une nouvelle langue vu qu'il faut que je mette qqch d'unique dans le champ code?

**Comment by verpoorten** [comment]
@thuyhanghoang @htmfilho Puisque Hang dit que les 2 autres points sont ok, je vais fermer ce ticket et en crée un nouveau pour le problème de l'autre régime linguistique car cela demande réflexion
