### ISSUE TITLE
Des améliorations suggérer par Philippe Bruyère dans l'écran du profil

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#377]
- [x] le nom de la localité du domicile n'est pas conservé quand on change d'écran.
- [x] si on ne met pas le nom du pays de domicile, il y a un message d'erreur comme quoi on n'a pas mis
  le nom du pays de résidence.
- [x] si on indique qu'on a une adresse de résidence, puis qu'on indique que ce n'est pas/plus le cas,
  les champs ne sont pas vidés.
- [x] on peut mettre une adresse mail non valide dans le champ email:
  contrôle: pas de blanc avant, pas de blanc après, pas de caractères spéciaux...
- [x] il n'y a pas de bouton pour sauvegarder; la sauvegarde semble se faire quand on change d'onglet;
  si je modifie un champ puis que je clique sur logout, ma dernière modification n'est pas sauvegardée.
- [x] bouton étape suivante à droite.
- [x] flèche bouton étape suivante à droite
- [x] le nombre d'enfants n'est pas conservé
- [x] le nom et prénom du conjoint n'est pas conservé
- [x] le champ nom et prénom du conjoint est trop court

**Comment by philbru** [comment]
Echec du test:
[ ] bouton sauvegarde marche pas
[ ] plus aucun champ conservé quand on change d'onglet, ou quand on clique sur suivant/précédent
[ ] grosse anomalie du traitement de l'email; caractère anormaux ajouté en fin d'email:
email prive be,,,;!&

**Comment by htmfilho** [comment]
@philbru  Merci beaucoup pour avoir pris l'initiative, mais le ticket est toujours dans un état que le développeur doit tester sur le serveur avant de le rendre disponible pour les analystes. Quand le pipeline deviant 'Done' tu peux finalement le tester.

J'ai accepté sa pull request juste avant son départ. Elle n'a pas eu le temps de le tester.

**Comment by philbru** [comment]
Le bouton sauvegarde fonctionne, mais par contre les informations sont perdues sur on navigue avec les boutons précédent/suivant.

Méthologie:
si on change de signet (onglet), les données doivent être conservées
si on change de signet avec les boutons suivant/précédent, les données doivent être conservées
si on clique saur sauvegarder, les données doivent être conservées
si on clique sur logout sans sauvegarder, il serait intéressant d'être invité à sauvegarder avant

Si on ne met pas de commune de domicile, il y a un message d'erreur comme quoi on n'a pas renseigné le code postal.

**Comment by htmfilho** [comment]
@philbru J'ai l'impression que tu as demandez des choses supplémentaires à partir de la liste originale du ticket. Peux-tu créer un autre ticket pour les nouvelles demandes, s'il te plaît? Merci.

**Comment by htmfilho** [comment]
@verpoorten peux-tu cocher les case à cocher dans la description du ticket que correspond au travail qui a été fait? Merci à l'avance.

**Comment by verpoorten** [comment]
Si #21 ok celui-ci ok

**Comment by thuyhanghoang** [comment]
lié à #21, je testerai tous dans #21
