### ISSUE TITLE
Compléter diplômes et examens - pas d'examen secondaire mais examen d'admission

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#38]
User Story

**En tant que** candidat n'ayant pas de diplôme secondaire

**Je veux** encoder les informations relatives à l'examen d'admission me donnant accès à l'offre universitaire choisie

**de sorte que** compléter mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-documentation/blob/master/doc/business/demande-inscription-en-ligne.adoc

**Comment by verpoorten** [comment]
Finalement j'ai tout fait dans le ticket #35

**Comment by verpoorten** [comment]
Faire d'abord le #113

**Comment by philbru** [comment]
Pas de limite de longueur au champ "A quelle session (date)": on ne doit pas pouvoir dépasser la longueur prévue
Pas de limite de longueur au champ "Nom de l'établissement": on ne doit pas pouvoir dépasser la longueur prévue
Taille de la zone de saisie du champ "Nom de l'établissement" trop court à l'écran
Pas de limite de longueur du champ "Préciser le nom ": on ne doit pas pouvoir dépasser la longueur prévue
"Préciser le nom" doit devenir ""Si autre, préciser le nom" (voir documentation)
"Quel résultat avez-vous obtenu?" ajouter une valeur "Pas encore de résultat" (logique si on va seulement passer l'examen)
Si on joint un ficher, l'icône de chargement du fichier laisse croire que ce n'est pas encore chargé.

**Comment by verpoorten** [comment]
Je n'ai pas réussi à reproduire le problème identifié par philbru au dernier point ("Si on joint un ficher, l'icône de chargement du fichier laisse croire que ce n'est pas encore chargé.")

**Comment by philbru** [comment]
Le problème arrive (et est reproductible) sur IE11 Windows 7.

**Comment by philbru** [comment]
L'attachement fonctionne avec Firefox 48 sous Windows 7 et avec Chrome 64 Windows 7.

**Comment by htmfilho** [comment]
@verpoorten , tu ne peux pas fermer le ticket :-(

**Comment by verpoorten** [comment]
Mauvaise manipulation surement...désolée

**Comment by thuyhanghoang** [comment]
- [ ] A quelle date? il faut un calendrier pour choisir

**Comment by thuyhanghoang** [comment]
ok
