### ISSUE TITLE
Mettre le bloc "Examen de maitrise de la langue francaise" dans l'onglet "Prerequis"

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#383]
Comme convenu lors de notre réunion, on déplace la question "Examen de maitrise de la langue francaise" dans l'onglet "Prérequis"
![image](https://cloud.githubusercontent.com/assets/6651769/18266321/608b1d4e-741a-11e6-8727-feefe9d3060a.png)

**Comment by verpoorten** [comment]
Fait dans le ticket #40

**Comment by verpoorten** [comment]
Si #40 ok celui-ci ok

**Comment by thuyhanghoang** [comment]
lié à #40
