### ISSUE TITLE
Compléter diplômes et examens - pas d'examen secondaire mais expérience professionnelle

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#39]
User Story

**En tant que** candidat n'ayant pas de diplôme secondaire ni d'examen d'admission

**Je veux** encoder les informations relatives à mon expérience professionnelle

**de sorte que** compléter mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Finalement j'ai tout fait dans le ticket #35

**Comment by thuyhanghoang** [comment]
- [ ] A quelle date: il faut avoir le calendrier
- [ ] Le champ "Nom de l'établissement" plus long
- [ ] Ajouter "Pas encore de résultat" dans la question "Quel résultat avez-vous obtenu? *"
- [ ] quand j'essaie de joindre un fichier .pdf => se plante

**Comment by verpoorten** [comment]
Les 3 premiers points sont résolus en local.  Mais je n'arrive pas à faire planter avec un pdf....

**Comment by verpoorten** [comment]
@thuyhanghoang Pour moi il est Done.  (Mais je n'ai jamais réussi à faire planter avec le PDF)

**Comment by thuyhanghoang** [comment]
@verpoorten je pense que ce n'était pas du problème de pdf mais c'est le problème de suppression de "applicant" quand on uploade la 2e fois dont Gaetan a parlé
les autres points sont corrigés
