### ISSUE TITLE
Ajout des nouveaux champs pour dissertation créé sur Osis

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#393]
De nouveaux fields ont été ajouté dans les modèles de dissertation, il faut ajouter ceux-ci dans osis-portal si nécessaire

**Comment by chfivet** [comment]
@matgerard @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

**Comment by matgerard** [comment]
ok.
