### ISSUE TITLE
Pouvoir visualiser les informations complètes des sujets proposés par les professeurs suite au nouvelles demandes

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#394]
Les nouvelles demandes souhaite que l'on affiche les informations de jury proposé par les professeurs

**Comment by chfivet** [comment]
@matgerard @ldermine Pouvez-vous tester ce ticket sur serveur dev et le fermer si c'est ok ?
Merci !

**Comment by matgerard** [comment]
ok.
