### ISSUE TITLE
Compléter diplômes et examens - maitrise langue française

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#40]
User Story

**En tant que** candidat

**Je veux** encoder les informations relatives à un examen de maitrise de la langue française (si je l'ai passé/obtenu)

**de sorte que** compléter mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Finalement j'ai tout fait dans le ticket #35

**Comment by verpoorten** [comment]
Test failed car le bloc n'apparait plus nul part

**Comment by verpoorten** [comment]
Il faut d'abord faire le #447

**Comment by htmfilho** [comment]
@verpoorten le #477 est fusionné en dev.

**Comment by thuyhanghoang** [comment]
@htmfilho @verpoorten on ne sait pas tester ce ticket car en fonction de l'offre choisie cette question apparaissent ou pas. Elle n’apparaît que quand s'il s'agit une offre Bachelier, Master Didactique, Agrégation.

Ici, j'ai essayé de chercher des cas, mais je n'ai pas trouvé des cas que la question apparaît.

**Comment by thuyhanghoang** [comment]
- [ ] Il faut que le bloc "Examen de maîtrise de la langue française n’apparaît que pour des demandes aux offres Bachelier, Master Didactique, Agrégation
- [ ] A quelle date? il faut avoir le calendrier pour choisir

**Comment by verpoorten** [comment]
@basmot Pourrais-tu me dire comment identifier un Master Didactique, je suis un peu perdue...Merci

**Comment by basmot** [comment]
@thuyhanghoang Comment peut-on identifier un Master Didactique ? 
Master Didactique est égal à Master de spécialisation ?

Dans GradeType, on a que les types suivants : 
BACHELOR = "BACHELOR"
MASTER_60 = "MASTER_60"
MASTER_120 = "MASTER_120"
MASTER_180_OR_240 = "MASTER_180_OR_240"
ADVANCED_MASTER = "ADVANCED_MASTER" (Master Spécialisation)
TRAINING_CERTIFICATE = "TRAINING_CERTIFICATE" (Agrégation)
CERTIFICATE = "CERTIFICATE"
DOCTORATE = "DOCTORATE"
CAPAES = "CAPAES"

**Comment by thuyhanghoang** [comment]
comme convenu, pour  le point: le bloc "Examen de maîtrise de la langue française n’apparaît que pour des demandes aux offres Bachelier, Master Didactique, Agrégation, on testera tout dans le ticket #568)
