### ISSUE TITLE
Gestion des emails lors de la création d'une soumission d'un mémoire

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#401]
Un email est envoyé au professeur lorsque l'étudiant soumet son mémoire

**Comment by chfivet** [comment]
@matgerard @ldermine Vousme confirmer que de mon coté c'est uniquement lorsque l'étudiant fait une soumission que j'envoi un mail ?

**Comment by matgerard** [comment]
@ldermine a répondu : 

> Wep, dans le modèle Dissertation il y a les appels au fonctions dans les changement d'état.

**Comment by matgerard** [comment]
Je pense aussi que côté osis-portal c'est le seul mail qui doit être envoyé.

**Comment by chfivet** [comment]
C'est en ordre je ferme le ticket
