### ISSUE TITLE
Compléter curriculum - écran initial

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#41]
User Story

**En tant que** système

**Je veux** déterminer la période (entre l'année de l'obtention du titre d'accès et l'année courante) et afficher un bloc pour chaque année

**de sorte que** le candidat puisse compléter son curriculum

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by htmfilho** [comment]
@philippehuynen Cette ticket faire parti du chemin critique du projet parce que il y a des tickets pour la release suivant que besoin de ce lui là. Donc, pour mieux gérer le risque du projet, je préfère attribuer tout les ticket lié au curriculum a @verpoorten , qui travail de mon coté.

Merci pour votre compréhension.

**Comment by verpoorten** [comment]
@htmfilho 
Pour ce sujet je propose de créer une nouvelle entité que voici

Je propose une nouvelle table

class Curriculum(models.Model):

PATH_TYPES = (
        ('LOCAL_UNIVERSITY', _('Université belge')),
        ('FOREIGN_UNIVERSITY', _('Université étrangère')),
        ('LOCAL_HIGH_EDUCATION', _(' Supérieur Non Universitaire belge')),
        ('FOREIGN_HIGH_EDUCATION', _(' Supérieur Non Universitaire étranger')),
        ('ANOTHER_ACTIVITY',_('Autre')),
        )

EDUCATION_TYPES = (
	('FRENCH', 'Communauté française de Belgique'),
	('GERMAN', 'Communauté germanophone'),
	('DUTCH', 'Communauté flamande'),
	)

RESULT_TYPE = (('SUCCEED', _('succeeded')),
                               ('FAILED', _('failed')),
                               ('ENROLLMENT_IN_PROGRESS', _('demanded_result')))

ACTIVITY_TYPES = (
        ('JOB', _('Job')),
        ('STAGE', _('Stage')),
        ('VOLUNTEERING', _('Volunteering')),
        ('UNEMPLOYMENT', _('Unemployment')),
        ('ILLNESS',_('Illness')),
        ('OTHER',_('Other')),
        )

academic_year = models.ForeignKey('AcademicYear', blank=True, null=True)
path_type = models.CharField(max_length=25, choices=PATH_TYPES, blank=True, null=True)
activity_type = models.CharField(max_length=255, choices=ACTIVITY_TYPES_TYPES, blank=True, null=True)
national_education = models.CharField(max_length=20, choices=EDUCATION_TYPES, blank=True, null=True)
language = models.ForeignKey('reference.Language',blank=True, null=True)
national_institution = models.ForeignKey('reference.EducationInstitution', blank=True, null=True)
domain = models.ForeignKey('Domain')
grade_type = models.ForeignKey('GradeType', blank=True, null=True, db_index=True)
diploma = models.BooleanField(default=False)
credits_enrolled = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
credits_obtained = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
diploma_title = models.CharField(max_length=255, choices=EDUCATION_TYPES, blank=True, null=True)
activity = models.CharField(max_length=255, blank=True, null=True)
activity_place = models.CharField(max_length=255, blank=True, null=True)

Qu'en penses-tu?

**Comment by verpoorten** [comment]
@htmfilho On commence avec ça jeudi?

**Comment by htmfilho** [comment]
Oui. La première chose à faire jeudi matin.

**Comment by philippehuynen** [comment]
@htmfilho, ok pour moi, d'autant que je suis sur un problème sans fin ici dans nos "vieilles" applications...

**Comment by chfivet** [comment]
@thuyhanghoang Hello, peux-tu tester ce ticket tout en sachant que la gestion des écrans se fait dans d'autre ticket pour le choix de type de parcours.

Merciiii

**Comment by htmfilho** [comment]
Salut @thuyhanghoang , je sais que l'application Admission ne plus actif, mais pour faire une release aujourd'hui j'ai besoin que tu le test quand même ;-) ça va ?

**Comment by thuyhanghoang** [comment]
@htmfilho je teste ça toute de suite

**Comment by thuyhanghoang** [comment]
@htmfilho quand je clique sur Curriculum, j'ai toute de suite un messages d'erreur
![image](https://cloud.githubusercontent.com/assets/6651769/23610900/dd8dddde-0274-11e7-8d28-d43baf8a96b7.png)

**Comment by chfivet** [comment]
@thuyhanghoang C'est good normalement ;-)

**Comment by thuyhanghoang** [comment]
![image](https://cloud.githubusercontent.com/assets/6651769/23617334/18999bb2-028d-11e7-8f89-a05e5ff14cf3.png)

**Comment by thuyhanghoang** [comment]
Il y a encore beaucoup de choses à corriger, comme convenu avec Beto, on ferme ce ticket. On fera un état de lieu avant de recommencer.
