### ISSUE TITLE
Transformer AssimilationCriteria en Enumeration

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#415]
Supprimer le model AssimilationCriteria et créer une enumeration equivalent.

**Comment by basmot** [comment]
@htmfilho Cela impacte la synchronisation.

**Comment by htmfilho** [comment]
Il faut attendre le ticket uclouvain/osis-legacy-sync#277 .

**Comment by verpoorten** [comment]
!!! **Fonctionne mais il faut pousser sur le bouton 'sauvegarder' car il semblerait que pour le moment le bouton prochaine étape ne fonctionne pas** !!! (voir ticket #461)

**Comment by thuyhanghoang** [comment]
@htmfilho @verpoorten c'est technique ça, je propose de demander Beto de tester ça au niveau de codes, je testerai au niveau fonctionnel avec le ticket #62

**Comment by verpoorten** [comment]
Pour moi si le ticket #62 est closed je pense qu'on peut aussi fermer ce ticket
