### ISSUE TITLE
Compléter curriculum - université belge

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#42]
User Story

**En tant que** candidat

**Je veux** encoder des informations relatives à une année d'étude universitaire belge, année diplomante ou non (2 options)

**de sorte que** compléter mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by htmfilho** [comment]
@philippehuynen Cette ticket faire parti du chemin critique du projet parce que il y a des tickets pour la release suivant que besoin de ce lui là. Donc, pour mieux gérer le risque du projet, je préfère attribuer tout les ticket lié au curriculum a @verpoorten , qui travail de mon coté.

Merci pour votre compréhension.

**Comment by philippehuynen** [comment]
@htmfilho, ok pour moi, d'autant que je suis ici sur un problème sans fin ici dans nos "vieilles" applications...

**Comment by htmfilho** [comment]
Merci @philippehuynen

**Comment by verpoorten** [comment]
@htmfilho Sais-tu à quoi correspond le champ code dans language si c'est un codeiso c'est lequel (639-1 ou 639-2)?
class Language(models.Model):
    code = models.CharField(max_length=4, unique=True)

**Comment by htmfilho** [comment]
C'est le code ISO, mais on prendre comme référence la table équivalent dans l'EPC. Si le 639-1 et le 639-2 sont là, donc, prendre le 639-1.

**Comment by verpoorten** [comment]
@thuyhanghoang Dans visual paradigm on parle de sous-domaine et pas dans la [doc sur github](https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/demande-inscription-en-ligne.adoc)? Quelle est la bonne version?

**Comment by verpoorten** [comment]
@thuyhanghoang Pour le nombre de crédits inscrits/acquis on peut encoder jusqu'à quel chiffre?

**Comment by thuyhanghoang** [comment]
@verpoorten avec le nouveau décret, les étudiants peuvent s’inscrire au maximum 75 crédits et donc aussi 75 crédits acquis au maximum

**Comment by thuyhanghoang** [comment]
@verpoorten c 'est toujours dans visual paradigm qui a la derniere version. Avec l'encodage de notes, je n'ai pas eu le temps de mettre à jour la doc

**Comment by verpoorten** [comment]
@thuyhanghoang Pourrais-tu me préciser ce qu'est le sous-domaine.  Merci

**Comment by jpminet** [comment]
Il m'est impossible d'accéder à l'application, que ce soit par  le login ('j'avais déjà créé un compte) ou en demandant un nouveau mot de passe.  J'ai l'erreur reprise sur la 
![erreur demande mdp](https://cloud.githubusercontent.com/assets/17611560/15395064/95a8f090-1dd6-11e6-8add-7486a49d0c96.png)
capture ci-jointe

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
