### ISSUE TITLE
Si on se trompe dans l'authentification, rester sur la page et afficher un message d'erreur

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#420]
Lorsqu'on se trompe dans l'authentification, il faut que la page d'authentification reste affichée avec un message d'erreur.
Pour le moment la page retourne à sa position d'origine avec l'image de présentation, et on ne voit pas d'erreur.
Le problème a été réglé pour la création d'un compte, mais pas pour l'authentification.

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
