### ISSUE TITLE
Permettre d'encoder la profession si le candidat choisit "Autre" comme Profession

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#425]
Dans l’enquête sociologique, si le candidat répond "Autre" comme profession du Père, Mère, Etudiant, Conjoint, Grand-Père, ajouter un champ texte pour qu'il puisse préciser la profession
![remplir_enquete_sociologique_state2](https://cloud.githubusercontent.com/assets/6651769/18637188/ddae743a-7e8b-11e6-9e3f-7ef4994fcb6d.png)

**Comment by verpoorten** [comment]
@glamarca Quand j'ai fait ce ticket j'ai modifié pas mal de choses pour enregistrer les données d'enquête sociologique.  Pour moi ce ticket-ci est ok, ce qui impliquerait que ton ticket #52 soit 'done' aussi.  Je te laisse juger par toi même pour éventuellement le passer en état 'DONE'

**Comment by glamarca** [comment]
@verpoorten 
Les tests de validités sur le report Activité Proffessionelle/Profession mis en place dans #52 ne fonctionnent plus (ne sont plus dans le code) (on peut mettre Acune Profession et donner une proffession par exemple).
Je vais reposer la question à @thuyhanghoang pour savoir si ça doit bien y être

**Comment by thuyhanghoang** [comment]
@glamarca j'ai testé ce ticket, il n'y a pas de problème. Mais au niveau l'interface quand l'étudiant choisit "Autre", on doit emménager différemment. Comme tu n'as de temps de discuter ça maintenant, je ferme ce ticket pour le release, je vais créer une autre ticket pour ça.
