### ISSUE TITLE
Problème onglet profil admission

### ISSUE THREAD

**Issue by philbru** [uclouvain/osis-portal#427]
**En tant que** étudiant

**Je veux** compléter mon profil

**de sorte que** les données soient sauvegardées

**lien vers la documentation** : 
- [ x ] Le bouton sauvegarde fonctionne, mais par contre les informations sont perdues sur on navigue avec les boutons précédent/suivant.

Méthologie:
si on change de signet (onglet), les données doivent être conservées
si on change de signet avec les boutons suivant/précédent, les données doivent être conservées
si on clique saur sauvegarder, les données doivent être conservées
si on clique sur logout sans sauvegarder, il serait intéressant d'être invité à sauvegarder avant
- [ x ] Si on ne met pas de commune de domicile, il y a un message d'erreur comme quoi on n'a pas renseigné le code postal.

**Comment by verpoorten** [comment]
Si #21 ok celui-ci ok

**Comment by thuyhanghoang** [comment]
Remarque dans #21
