### ISSUE TITLE
Compléter curriculum - université étrangère

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#43]
User Story

**En tant que** candidat

**Je veux** encoder les données relatives à une année d'étude universitaire antérieure (université étrangère), année diplomante ou non

**de sorte que** compléter mon dossier d'admission

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Faudra je crois ajouter
country = models.ForeignKey('reference.Country') 
dans class EducationInstitution(models.Model):

**Comment by htmfilho** [comment]
Ok. D'accord. Peux-tu le faire S'il te plaît? Merci.

**Comment by verpoorten** [comment]
Je le ferai quand on arrivera dans ce ticket

**Comment by verpoorten** [comment]
Finalement je l'ai fait dans le ticket 42

**Comment by verpoorten** [comment]
Quand je changeais qqch dans osis-portal.js la modification n'était pas immédiatement visible.  Avec l'ajout de livereload dans les settings ça fonctionne.  Voici où j'avais trouvé une explication de ce méchanisme http://stackoverflow.com/questions/15641474/django-not-reflecting-updates-to-javascript-files

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
