### ISSUE TITLE
Problème lors de la migration depuis osis d'un objet qui existe déjà dans la DB

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#441]
Par exemple, si j'ajoute un tutor du côté osis qui existe déjà dans la db du côté osis-portal j'obtient cette erreur : 

``` bash
django.db.utils.IntegrityError: ERREUR:  la valeur d'une clé dupliquée rompt la contrainte unique « base_tutor_person_id_key »
DETAIL:  La clé « (person_id)=(33383) » existe déjà.
```

Il semblerait qu'un insert est exécuté au lieu d'un update.

Peut-être faut-il supprimer la première méthode d'écoute de la queue présente dans base.apps : 

``` python
    def ready(self):
        try:
            from .models.signals import update_person_after_user_creation, \
                update_person_after_user_update, add_to_students_group
        except ImportError:
            pass
        # if following exception is thrown ; django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
        # ===> This exception says that there is an error anywhere in the implementation of method ready(self) !
        queue_listener.listen_queue(self.queue_name, insert)
        SynchronousConsumerThread(self.queue_for_migration, callbacks.insert_or_update).start()
```

**Comment by basmot** [comment]
- [ ] Suppression des écoutes de Queues non utiles
- [ ] Lancement des listeningThreads dans le wsgi.py (et non dans les apps.py) car apps.ready() peut être appelé deux fois ( http://stackoverflow.com/questions/16546652/why-does-django-run-everything-twice )
- [ ] base.OfferYearDomain doit également implémenter SerializableModel

**Comment by basmot** [comment]
@glamarca Pour moi on peut fermer cette issue. La réussite de la synchro et du transfert de données vers Osis-portal prouvent le bon fonctionnement de cette issue. Et si un objet à supprimer n'existe pas, il consume bien le message, ignore l'objet à suprimer (vu qu'il n'existe pas) et consume le message suivant.
