### ISSUE TITLE
Upload de fichier pour les projets de mémoire

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#443]
**En tant que** Etudiant

**Je veux** Upload un fichier

**de sorte que** le professeur puisse voir les documents liés à mon mémoire

**lien vers la documentation** :

**Comment by chfivet** [comment]
@matgerard ça semble bon tu peux tester pour confirmer et fermer le ticket ?

**Comment by matgerard** [comment]
Testé et ok pour l'upload d'un fichier par le student dans son projet de mémoire.
