### ISSUE TITLE
Transformer InstitutionalGradeType en Enumeration

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#447]
... et modifier la table "GradeType" pour utiliser na nouvelle énumération.

**Comment by verpoorten** [comment]
@htmfilho  @basmot  Quelles valeurs je mets dans l'enum?  
Ce que je trouve dans les fixtures? 
Bachelier
Master 60
Master 120
Master 180 ou 240
Master de sp\u00e9cialisation
Agr\u00e9gation
Certificat
CAPAES
Doctorat
 
Ce qu'on avait au préalable dans GRADE_CHOICES :GRADE_CHOICES = (
    ('BACHELOR', _('bachelor')),
    ('MASTER', _('master')),
    ('DOCTORATE', _('ph_d')),
    ('TRAINING_CERTIFICATE', _('teacher_training_certificate')),
    ('CERTIFICATE', _('certificate')))

**Comment by basmot** [comment]
@verpoorten Tu peux mettre les nouvelles valeurs (avec CAPAES, Agregation, etc.). A moins que cela ne te parrait pas suffisant pour répondre au besoin dans un cas spécifique auquel on a pas pensé?

**Comment by verpoorten** [comment]
@htmfilho Il faudrait mettre à jour dev pour que le champ institutional grade type de grade type soit garnit.
