### ISSUE TITLE
Le bouton introduire une nouvelle demande pose problème

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#448]
![ticket](https://cloud.githubusercontent.com/assets/5947635/19073326/b0efa31e-8a3a-11e6-9c22-08f1889d70a3.jpg)

**Comment by verpoorten** [comment]
@thuyhanghoang  Pour tester il faut avoir déjà introduit une demande (avec une offre), et retourner à l'adresse https://dev.studies.uclouvain.be/admission

**Comment by thuyhanghoang** [comment]
Comme demandé, j'ai essayé de créer des nouvelles demandes et retourner à la liste des demandes, il n'y a pas de problème pour ça.
