### ISSUE TITLE
Il ne faut pas empecher passer l'étape suivante s'il s'agit pas des champs neccessaire 

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#450]
Dans l'onglet Profil - Assimilations, je suis satisfaite la critère 1, même si je ne fournis pas tous des documents, il ne faut pas m'empêcher passer à l'étape suivante

**Comment by verpoorten** [comment]
Je dois vérifier avec @thuyhanghoang si le problème est tj présent

**Comment by thuyhanghoang** [comment]
testé, ok
