### ISSUE TITLE
La liste des offres ne sont pas correctes

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#451]
- Il manque beaucoup d'offre, par exemple, si je choisis Bachelier comme "Type d'étude" et choisit un domaine quelconque, je n'ai pas l'offre correspondante, il y en a jusque 1 ou 2 offres.
- La liste des offres ne doit pas contenir des 11BA, de 2MS, 2M
  ![image](https://cloud.githubusercontent.com/assets/6651769/19117631/f07f8b5e-8b19-11e6-9096-259d4e1198f7.png)

**Comment by verpoorten** [comment]
@basmot comment identifier les offres qui ne contiennent pas 11BA, de 2MS, 2M?  Sans utiliser l'acronyme de l'offre (ce qui me semblerait un peu bof comme solution)?

**Comment by basmot** [comment]
@verpoorten On va devoir synchroniser une info supplémentaire venant de EPC. Je vais créer un nouveau champs 'enrollment_enabled' dans Osis et le synchroniser. Tu pourras rajouter ce champs côté Osis-portal.

**Comment by chfivet** [comment]
@basmot Peux-tu me prévenir lorsque le champs 'enrollment_enabled' aura été ajouté dans Osis ?

Bien à toi,

**Comment by basmot** [comment]
J'ai essayé beaucoup de combinaison de type d'étude et domaine d'étude, mais il n'y a aucune offre qui apparait. Impossible donc de faire une choix d'offre.

**Comment by verpoorten** [comment]
@basmot @htmfilho @chfivet Vu que Christophe est en congé je vais prendre cela en charge.

**Comment by verpoorten** [comment]
@basmot @htmfilho @chfivet Je pense que c'est simplement parce que tous les champs 'offer_year.enrollment_enabled' en DEV sont 'false'

**Comment by basmot** [comment]
Bien vu @verpoorten, cela fonctionne bien si on change manuellement le champs enrollment_enabled. On devra attendre la synchro avec les données de Dev pour un test complet sur toutes les offres.

**Comment by chfivet** [comment]
@verpoorten @basmot C'est effectivement le champ enrollment_enabled qui est à False en Dev mais c'est fonctionnel normalement

**Comment by chfivet** [comment]
@thuyhanghoang Hello,
Peux-tu tester ce ticket et le fermer le cas échéant ?

Attention qu'il est nécessaire de cocher le boolean  Enrollment Enabled en True pour que l'Offer Year soit pris en compte et apparaisse dans le choix d'offre. Actuellement, seul ARCB2M (Architecture) est disponible pour les tests.

**Comment by thuyhanghoang** [comment]
@basmot il ne faut pas prendre le 11BA, il ne faut prendre que des offres "Programme", pas une année d'étude

**Comment by basmot** [comment]
@thuyhanghoang C'est lié aux données venant de EPC : les Offres 11BA sont inscriptibles. C'est donc normal qu'elles apparaissent dans la liste. Je pense qu'il faut corriger les données de EPC.

**Comment by thuyhanghoang** [comment]
@basmot il ne s'agit pas de problème de donnée de EPC. 11BA est une offre inscriptible mais on ne présente pas des année d'études dans la liste des offres à proposées

**Comment by basmot** [comment]
@thuyhanghoang Ok, on doit prévoir une réunion pour l'analyse d'une solution à cette problématique des 11BA. Si cette issue est OK (à part les 11BA), tu peux la fermer, et créer une nouvelle issue pour cette problématique-là.

**Comment by thuyhanghoang** [comment]
on discute du problématique de 11BA plus tard
