### ISSUE TITLE
Il y a des doublons dans la liste des domaines

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#452]
![image](https://cloud.githubusercontent.com/assets/6651769/19117775/82a21164-8b1a-11e6-9df2-15e596d1bdf4.png)

**Comment by verpoorten** [comment]
@basmot que doit-on prendre comme domain pour éviter les doublons?  Les domains sans parent?

**Comment by basmot** [comment]
@verpoorten `domain.decree = 'PAYSAGE'` et `domain.parent is not null` et `domain_type==UNIVERSITY`

**Comment by thuyhanghoang** [comment]
Il ne faut prendre que des domaines, pas des sous-domaines. Malgré que l'offre est attaché à un sous-domaine (parfois à un domaine), il faut monter pour prendre seulement des domaines

**Comment by verpoorten** [comment]
@htmfilho et @basmot Pourriez-vous discuter de la requête à faire.  

(Beto ne voulait pas que j'inscrive domain.decree ='PAYSAGE' dans la requête, mais c'est peut-être la solution attendue par Hang)

**Comment by htmfilho** [comment]
@thuyhanghoang a dit "il ne faut prendre que des domaines, pas des sous-domaines" dont, il n'a rien à voir avec le décret mais au critère `domain.parent is not null`, qui prendre les sous-domaines. Pour prendre juste les domaine il faut `domain.parent is null`, je croix.

**Comment by verpoorten** [comment]
@thuyhanghoang  @htmfilho Si je change la condition.  

    return Domain.objects.filter(decree=current_decree)\
                         .filter(type=domain_type.UNIVERSITY)\
                         .filter(parent__isnull=True)\
                         .order_by("name")
En local avec les données de actual_data.json, j'ai ceci:  

Art de bâtir et urbanisme
Art et sciences de l'art
Arts du spectacle et technique de diffusion et de communication
Arts plastiques, visuels et de l'espace
Criminologie
Danse
Histoire, histoire de l'art et archéologie
Information et communication
Langues, lettres et traductologie
Musique
Philosophie
Sciences
Sciences agronomiques et ingénierie biologique
Sciences biomédicales et pharmaceutiques
Sciences de la motricité
Sciences de la santé publique
Sciences de l'ingénieur et technologie
Sciences dentaires
Sciences économiques et de gestion
Sciences juridiques
Sciences médicales
Sciences politiques et sociales
Sciences psychologiques et de l'éducation
Sciences vétérinaires
Théâtre et arts de la parole
Théologie

Ca semble un peu léger non?

**Comment by basmot** [comment]
@verpoorten Je pense que c'est correct. La liste des domaines (sans les sous-domaines) est plus restreinte.

**Comment by htmfilho** [comment]
Salut @basmot tester en dev parce que @thuyhanghoang n'est pas là.

**Comment by basmot** [comment]
La liste des domaines est bien correcte. En revanche, plus aucune offre n'est affichée après sélection d'un domaine. Mais cela sera réglé dans une autre issue.
