### ISSUE TITLE
Le candidat ne sait sauvegarder s'il ne répond pas à tous les questions nécessaires

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#454]
Il faut que le candidat peut sauvegarder même s'il n'a pas encore répondu à tous les questions nécessaires (nationalité, résident, nationalité du diplôme, choix une offre)

**Comment by verpoorten** [comment]
Je dois vérifier avec @thuyhanghoang si le problème est tj présent

**Comment by htmfilho** [comment]
@verpoorten ,

**Comment by thuyhanghoang** [comment]
testé, ok
