### ISSUE TITLE
Remplacer Couchbase par Postgresql avec JSonField pour l'impression de feuille des notes

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#458]
Couchbase n'est plus utilisé, mais l'impression de feuille des notes dépend encore de Couchbase. Il faut utiliser JsonField + PostgreSQL pour garder le contenu Json qui vien de la queue.

**Comment by edd19** [comment]
@htmfilho 
J'attends que le ticket #459 soit terminé pour push celui-là.
