### ISSUE TITLE
Compléter curriculum - supérieur non universitaire belge

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#46]
User Story

**En tant que** candidat

**Je veux** encoder les informations relatives à une année d'étude antérieure non universitaire belge (diplomante ou non)

**de sorte que** constituer mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
@htmfilho Dans le cadre de ce ticket je me demande s'il ne faut pas envisager d'importer depuis epc les données de la table etd_eco_snu dans la table education_institution

**Comment by verpoorten** [comment]
@htmfilho on doit ajouter une notion de système d'étude dans education_institution car dans la doc je trouve ceci
Système d'étude(liste déroulante): "Promotion sociale" ou "Plein exercice". Chaque établissement on doit savoir s'il a quel(s) système d'études. Certain établissement peut avoir 2 systèmes d'étude. Si l'établissement choisi a un seul système d'étude, on ne doit pas cette question. Si le candidat choisit un établissement qui n'est pas dans la liste, il faut apparaitre cette question pour que le candidat précise le système d'étude. Le gestionaire doit repasser pour le valider.

On pourra y regarder tantôt?

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
