### ISSUE TITLE
Changer admission.Application.national_degree en 'coverage_access_degree' et transformer en Enumeration

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#478]
Valeurs possibles pour l'Enum : 
- NATIONAL
- NON_NATIONAL
- EUROPEAN_UNION
- NON_EUROPEAN_UNION

**Comment by verpoorten** [comment]
Je dois remplacer le cadre noir par le cadre orange?

![feature478](https://cloud.githubusercontent.com/assets/5947635/20003044/5f73fd84-a284-11e6-8aa9-868feb7d4875.png)

**Comment by basmot** [comment]
@verpoorten Non, cela doit rester `Oui - Non`. 
- Si l'utilisateur répond 'Oui' alors `NATIONAL`. 
- Si l'utilisateur répond 'Non', alors `NON_NATIONAL`

**Comment by thuyhanghoang** [comment]
@verpoorten @htmfilho je ne sais pas tester ce ticket sur l'énumération

**Comment by verpoorten** [comment]
J'ai vérifié en base de données que la valeur encodée était bien NATIONAL quand on répond OUI et NON_NATIONAL quand on répond NON.  Je pense donc qu'on peut fermer ce ticket
