### ISSUE TITLE
Créer un nouveau modèle admission.AdmissionCalendar

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#479]
Ce modèle va permettre de gérer les dates d'inscriptions aux offres (exceptions comprises).

Liste des champs : 
- academicYear (FK null=False)
- offer_year (FK null=True)
- european_union (Boolean - null=True)
- coverage_access_degree (Même Enum que dans base.Application - null=True)
- residence (Enum : NATIONAL, NON_NATIONAL - null=True)
- start_date (null=False)
- end_date (null=False)

**Comment by htmfilho** [comment]
Dupliqué avec le #130
