### ISSUE TITLE
Compléter curriculum - autre

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#48]
User Story

**En tant que** candidat

**Je veux** encoder des informations relatives à une année d'activité autre que des études

**de sorte que** constituer mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
