### ISSUE TITLE
Compléter curriculum - uploader des documents

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#49]
User Story

**En tant que** candidat

**Je veux** uploader des documents relatifs à mon curriculum (dans plusieurs écran)

**de sorte que** constituer mon dossier d'admission

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
