### ISSUE TITLE
Compléter diplômes et examens - uploader document

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#50]
User Story

**En tant que** candidat

**Je veux** uploader des documents relatifs à mes diplômes et examens (dans plusieurs écrans)

**de sorte que** constituer mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Dans ce ticket j'ai aussi réglé le fait que l'on puisse, dans l'onglet choix de l'offre, voir une offre précedemment sélectionnée

**Comment by verpoorten** [comment]
Lors des tests j'ai découvert que si je sélectionne un fichier avec un accent dans le nom => UnicodeEncodeError at /admission/upload/

'ascii' codec can't encode character '\xe9' in position 29: ordinal not in range(128)

**Comment by verpoorten** [comment]
glamarca doit vérifier ce qu'il se passe sur DEV #353

**Comment by verpoorten** [comment]
Done.  Mais, je pense qu'il faut attendre que les tickets #180 et #354 soient résolus avant de tester sinon il faut chipoter.  Je l'assignerai donc à un testeur quand ces tickets seront ok

**Comment by verpoorten** [comment]
Si #36, #37, #38,  #39, #40 ok ce ticket est ok

**Comment by thuyhanghoang** [comment]
@htmfilho ca ne sert rien de mettre ça en Done, il y a un problème dans uploader un document, je ne sais pas valider ce ticket

**Comment by verpoorten** [comment]
@thuyhanghoang @glamarca Pour moi c'est Done Vu qu'on est 2 à l'avoir comme assignation je ne l'ai pas mis en 'DONE'

**Comment by thuyhanghoang** [comment]
testé, ok
