### ISSUE TITLE
Pour les documents d'assimilation, on n'a plus la possibilité de supprimer un fichier pré-existant sur le popup d'upload

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#501]
![no_delete](https://cloud.githubusercontent.com/assets/5947635/20000026/c2b243ba-a275-11e6-80f8-41576596a15e.png)

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
