### ISSUE TITLE
Development de pièces jointes

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#51]
User Story

**En tant que** candidat

**Je veux** joindre à mon dossier (=uploader) toutes les pièces qui me paraissent utiles

**de sorte que** documenter mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by chfivet** [comment]
@glamarca Il semble y avoir un problème de permission pour l'upload d'un fichier sur le serveur dev.

PermissionError at /admission/upload/
[Errno 13] Permission denied: '/var/www/os.path.join(BASE_DIR, "uploads")'

J'ai retesté en local (dev) et l'upload fonctionne

**Comment by glamarca** [comment]
Le problème n'est pas un problème de permission , mais dans les settings, j'ais mis des '' autours de os.path.join(BASE_DIR, "uploads")', ce qui pose problème., et donc il prend cela comme un litéral.
En plus ce ne devrait pas être cette url qui est utilisée, mais celle définie sur le serveur.
Je vais faire la correction du settings dans ce ticket et vérifier pour l'url utilise sur le serveur.

**Comment by glamarca** [comment]
J'ai fait les modifs sur le serveur et dans le settings.
En local, tous les upload vont dans base/uploads
Je ne sais pas encore comment faire pour créer un sous dossier en utilisant MEDIA_ROOT, donc pour le moment tous les upload vont dans le même dossier.
@chfivet 
Peux-tu retester en dev (sur le serveur dev donc), je ne sais pas ou uploader un fichier!
Merci.

**Comment by chfivet** [comment]
@glamarca C'est good maintenant 
Le fichier s'envoi bien

**Comment by glamarca** [comment]
OK.
