### ISSUE TITLE
Modifier le model pour que les tables admission dont les données sont transférables dans OSIS soient : SerializableModel

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#511]
- `SerializableModel` pour les entités dans l'application "admission" + fichier de migration correspondent.
- Fichier de migration pour générer les uuids pour les tables d'amission sauf `form`, `question` et `option`.

**Comment by htmfilho** [comment]
Exemple des générations des Ids pour une liste de models: https://github.com/uclouvain/osis-portal/commit/82423d11dafb38516134751db56370957fe6f4e6
