### ISSUE TITLE
Harmoniser les icônes avec osis

### ISSUE THREAD

**Issue by matgerard** [uclouvain/osis-portal#515]
Besoin d'avoir une cohérence entre les icônes entre osis et osis-portal pour les personnes qui aideront les étudiants.

**Comment by matgerard** [comment]
Il faut laisser l'issue open tant que le PR n'est pas accepté :-)

**Comment by ldermine** [comment]
l 'issue était en doublon avec la 581 ;-)

**Comment by matgerard** [comment]
Sorry, pas vu !
