### ISSUE TITLE
L'ecran de error de problème d'activation pas conforme

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#522]
La liste de raisons d'echec n'est pas idéal. Il faut mètre seulement "Peut-être vous avez déjà activé votre compte." plus "Cliquez ici pour vous connecter ou contactez le support l'UCL." Il faut voir ce que le site d'inscription actuel offre comme support technique. C'est le service desk ou inscription@uclouvain.be?

![ecran_validation_activation](https://cloud.githubusercontent.com/assets/200272/20182557/6e20ec1a-a762-11e6-8635-723f74836967.png)

**Comment by verpoorten** [comment]
En regardant dans Portail-inscription il semblerait que ce soit sur le service desk que l'on soit redirigé en cas de problème

**Comment by thuyhanghoang** [comment]
@verpoorten @htmfilho Comment je dois faire pour avoir le problème d'activation ?

**Comment by htmfilho** [comment]
@thuyhanghoang Je ne sais pas si tu as déjà ta réponse, mais pour tester ce lui là, il faut:

1. Créer une nouvelle compte
2. Ouvrir l'email et cliquer sur le lien d'activation pour activer le compte
3. Une fois que le compte est activé, cliquer une deuxième fois sur le lien d'activation.

L'écran d’errer ci-dessus apparaîtra.

**Comment by thuyhanghoang** [comment]
testé
