### ISSUE TITLE
Ajout de la consultation des applications

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#528]
Mode readonly pour les applications soumises

- [ ] onglet choix de l'offre
- [ ] onglet prérequis
- [ ] onglet curriculum
- [x] onglet comptabilité
- [x] onglet sociologique
- [x] onglet pièces jointes

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
