### ISSUE TITLE
Améliorer la présentation du tableau des documents à uploader pour des similations

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#529]
Il ne faut pas montrer le cadre du tableau.
Il faut reculer "OU" 1 saut à droite
Il faut reculer le bouton Upload 3 sauts à droite
![image](https://cloud.githubusercontent.com/assets/6651769/20304468/a78d412a-ab30-11e6-99f0-a726ff2f60d1.png)

**Comment by verpoorten** [comment]
Comme ceci ça irait?

![529](https://cloud.githubusercontent.com/assets/5947635/22370155/46788c52-e490-11e6-91dc-174b65f83595.png)
![capture du 2017-01-27 12-57-32](https://cloud.githubusercontent.com/assets/5947635/22370158/49178076-e490-11e6-87dc-fa53759154b3.png)

**Comment by thuyhanghoang** [comment]
@verpoorten signale moi quand je peux tester en Dev. Merci!

**Comment by verpoorten** [comment]
@thuyhanghoang C'est en dev

**Comment by thuyhanghoang** [comment]
j'ai testé en Dev, pour moi l'interface est ok, on verra le texte avec l'utilisateur.
