### ISSUE TITLE
Comptabilité

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#53]
User Story

**En tant que** candidat autorisé à m'inscrire (admission OK)

**Je veux** encoder des données comptables/financières

**de sorte que** compléter mon dossier d'inscription

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Voici ce qu'on devrait je pense ajouter à application pour la comptabilité

reduction_registraton_number = models.CharField(max_length=50, blank=True, null=True)
no_UCL_scholarship = models.BooleanField(default=False)
no_UCL_scholarship_organization = models.CharField(max_length=255, blank=True, null=True)
#attestation stipulant l'absecne de dettes
no_UCL_scholarship = models.BooleanField(default=False)
sport_membership = models.BooleanField(default=False)
culture_membership  =models.BooleanField(default=False)
solidary_membership=  models.BooleanField(default=False)
bank_account_IBAN = models.CharField(max_length=255, blank=True, null=True)
bank_account_BIC = models.CharField(max_length=255, blank=True, null=True)
holder_bank_account_last_name = models.CharField(max_length=255, blank=True, null=True)
holder_bank_account_first_name = models.CharField(max_length=255, blank=True, null=True)

traduction des termes et facultatif/obligatoire à vérifier

**Comment by verpoorten** [comment]
A faire + tard 

- Faire varier le lien d'information dans le cadre affiliation sport en fonction du site de l'offre à laquelle l'étudiant s'inscrit

**Comment by verpoorten** [comment]
Actuellement l'écran est accessible via l'url .../admission/admission/application/accounting/

**Comment by htmfilho** [comment]
Faire varier le lien d'information dans le cadre affiliation sport en fonction du site de l'offre à laquelle l'étudiant s'inscrit.

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
