### ISSUE TITLE
Actualiser la liste des offres chaque fois on change le critère de recherche 

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#535]
Quand je change le type d'études ou un domaine, la liste est vide
![image](https://cloud.githubusercontent.com/assets/6651769/20351253/60aa3bfe-ac12-11e6-805d-78e33804ef4b.png)

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
