### ISSUE TITLE
Ce n'est pas la date de création, c'est la date de "Dernière mise à jour"

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#539]
![image](https://cloud.githubusercontent.com/assets/6651769/20353773/2b6ecff4-ac1c-11e6-82fb-ff87879a16d9.png)

Dans cet interface:
- Ce n'est pas la date de création, c'est la date de "Dernière mise à jour"
- Il faut trier la date la plus récente à la plus ancienne

**Comment by thuyhanghoang** [comment]
@htmfilho @verpoorten 
Je n'arrive pas de me connecter.
J'essaie de créer mon compte, il est marqué que le compte existe déjà.
![image](https://cloud.githubusercontent.com/assets/6651769/22780923/b7e8214c-eec0-11e6-99fa-2411125e10ed.png)
Je vais dans la table Applicant: je ne vois pas mon compte pour le supprimer
![image](https://cloud.githubusercontent.com/assets/6651769/22780883/92eb0508-eec0-11e6-9028-85f54589fd9d.png)

Qu'est-ce que je dois faire pour pouvoir tester????

**Comment by htmfilho** [comment]
@thuyhanghoang oui, l'utilisatrice avec l'email informé existe. Soit tu demande de changer ton mot de passe soit tu supprime l'e-mail dans la table `utilisateurs`.

![image](https://cloud.githubusercontent.com/assets/200272/22822810/2e9d4f2c-ef81-11e6-8674-bd698f927153.png)

**Comment by thuyhanghoang** [comment]
@verpoorten Leila, peux-tu me donner le lien d'accès pour voir la liste des demandes pour pouvoir tester ce ticket? Merci

**Comment by thuyhanghoang** [comment]
dev ok
