### ISSUE TITLE
Confirmer/soumettre la demande d'inscription

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#54]
User Story

**En tant que** candidat

**Je veux** confirmer et soumettre ma demande d'inscription

**de sorte que** formalise ma demande d'inscription auprès de l'UCL

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Des nouvelles du texte à ajouter ici
![54](https://cloud.githubusercontent.com/assets/5947635/20382311/a3e039d4-acab-11e6-8ed8-69cc7e511696.png)

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
