### ISSUE TITLE
Examen spécial d'admission aux études universitaires de 1er cycle de l'ingénieur (ingénieur civil)

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#544]
si le candidat veut s'inscrire à FSA1BA ou ARCH1BA. A la soumission et à la validation de l'onglet, s'il ne coche pas à "Examen spécial d'admission aux études universitaires de 1er cycle de l'ingénieur (ingénieur civil)" => ce n'est pas validé.

Lié à #113

**Comment by htmfilho** [comment]
Je ferme ce billet ouvert pour l'application d'admission n'est plus une priorité. Il faut le repenser.
