### ISSUE TITLE
Ajouter le champ pour saisir la profession du père et la mère dans l'onglet Enquete sociologique

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#547]
@glamarca à dit:

> Nom des profession trop long dans la drop_down_listes. Est-ce qu'on ne pourrait pas avoir une partie générique dans le nom de la ​profession et une partie exemple, qui ne serait affichée que comme 'tool-tip'

> Est-il nécéssaire d'ajouter chomeur et sans profession dans la liste, est-ce que '------' (vide) ne suffit pas.

> Ces professions doivent elles être syncho entre osis et osis-portal (si on ajoute une profession dans osis-portal, doit-elle être migrée vers osis)

**Comment by htmfilho** [comment]
@thuyhanghoang a la création d'un ticket, n'oublié pas de choisir l'epic correspondent. Merci.

**Comment by thuyhanghoang** [comment]
ok, merci!

**Comment by htmfilho** [comment]
Je ferme ce billet ouvert pour l'application d'admission n'est plus une priorité. Il faut le repenser.
