### ISSUE TITLE
Confirmer la soumisson d'une demande d'inscription

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#55]
User Story

**En tant que** système

**Je veux** informer (message à l'écran) le candidat que sa demande d'inscription a bien été reçue 

**de sorte que** le candidat puisse être rassuré 

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by htmfilho** [comment]
Dupliqué avec le #54
