### ISSUE TITLE
Permettre d'ouvrir et fermer un bloc d'information dans l'onglet Prérequis

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#551]
![image](https://cloud.githubusercontent.com/assets/6651769/20426819/2597a23e-ad81-11e6-8fc5-29388d5d0c89.png)

**Comment by htmfilho** [comment]
@thuyhanghoang ces champs sont obligatoires. Si on le masque, le utilisateurs ne trouveront pas où se trouve le problème de validation.

**Comment by thuyhanghoang** [comment]
quand il remplit ses études secondaires, c'est très long, de toute façon, l'étudiant doit descende très bas pour voir des erreur, il ne peut pas voir tous les erreurs toute de suite

**Comment by htmfilho** [comment]
Désolé @thuyhanghoang mais nous ne connaissons pas l'impact de ce comportement. Si nous le faisons, tu demandera certainement plus tard d'étendre la session qui a des problèmes de validation ou afficher un icone pour signaler des problème dedans. Il pourrait devenir trop coûteux. Pas possible pour la V1.
