### ISSUE TITLE
Validation du code postal belge dans l'écran de diplome secondaire belge

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#552]
Philippe demande dans le ticket #36 d'effectuer une validation du code postal belge

Comme convenu avec Bastien, on doit discuter le problèmatique d'avoir Brussel et Bruxelles, et surtout la liste des codes postaux de ces 2 villes n'est pas unique

**Comment by htmfilho** [comment]
@verpoorten tu ne peux pas le faire alors que tu ne peux pas le trouver dans la documentation. Merci.

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
