### ISSUE TITLE
Secondaire belge - modifier le fonctionnement de l'autre régime linguistique

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#555]
Suite aux remarques de Hang dans le ticket #37 voir ci-dessous:

Dans ce cas là, c'est mieux que tu mélanges tous les régimes dans la liste (il ne faut pas séparer en 2).

Pour Autre régime: il faut juste remplacer le menu déroulant par une simple texte. Et garder la logique que si "autre régime linguistique" est coché, il faut faire 3 choses: - supprimer le choix dans le menu déroulant de "Régime linguistique"; - rendre le menu déroulant grisé; - rendre la zone texte éditable. Je mettrais à jour le manuel.

![image](https://cloud.githubusercontent.com/assets/6651769/20430676/023fd968-ad96-11e6-83df-cd07699019e1.png)

**Comment by verpoorten** [comment]
@htmfilho qu'est-ce que je fais pour la bd ici .  Pour le moment dans la bd

international_diploma_language = models.ForeignKey('reference.Language', blank=True, null=True)
Mais je ne vais pas créer un enregistrement Language chaque fois que qqun introduit une nouvelle langue?

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
