### ISSUE TITLE
Envoyer email de confirmation

### ISSUE THREAD

**Issue by jpminet** [uclouvain/osis-portal#56]
User Story

**En tant que** système

**Je veux** informer par mail que la demande d'inscription du candidat a été bien reçue et lui transmettre les instructions/informations pour la suite (envoi du dossier papier)

**de sorte que** le candidat soit rassuré que sa demande a été reçue et sache quoi faire ensuite

**lien vers la documentation** :  https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/user-manual_fr.adoc#les-fonctionalit%C3%A9s

**Comment by verpoorten** [comment]
Je vais modifier l'estimate car il faut envoyer un mail qui varie en fonction de différent critères (type de demande, offre choisie, site, du type d'études) et en plus il faut y joindre un pdf qui résume les informations encodées par le candidat (voir doc/business/fichier_pdf_soumission.pdf

**Comment by verpoorten** [comment]
Je dois arrêter de travailler sur ce sujet pour le moment, mais j'ai déjà bien avancé.

- Préparation de l'acquisition des variables pour le modèle message

- Squelette partiel pour le pdf

- Beaucoup de tests

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
