### ISSUE TITLE
L'onglet profil qui n'est pas lié avec des demandes

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#565]
Sur l'interface principale https://dev.studies.uclouvain.be/admission/ il y a 2 onglets: Profil et Vos demandes d'inscription
Dans l'onglet Profil: 
- [ ] il faut enlever "Etape suivante: Choix de l'offre" à 2 endroits (en haut et en bas)
- [ ] Des informations qui ne sont pas copiées:
       - Photo d'identité
       - Pays de naissance
       - Nationalité
       - Des critères d'assimilation
       - Document d'identité
       - Pays de domicile
       - Pays de l'adresse de correspondance
       -  ....

![image](https://cloud.githubusercontent.com/assets/6651769/20475277/3c10019a-afcb-11e6-9f9f-995d99e9c622.png)

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
