### ISSUE TITLE
Synchroniser les données nécessaires du module 'Activite' de Osis vers Osis-portal

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#57]
Liste des champs à synchroniser : 
[ à déterminer ]

Lié à  uclouvain/osis#284

**Comment by glamarca** [comment]
#### Pour le catalogue de formation : 
##### Table EPC_ELE
num_ele,validite,sigle_ele,cnum,subdivision,dpt_charge,type,type_grp,les volumes horaires + coefficient ,initi_complet (fr + en) , intit_abrege (fr + en), remarque_facultaire (en + fr), quadrimestre, actif,
##### Table EPC_CAHIER_CHARGES
tout
##### Table EPC_RESUME_COURS
tout
##### Table EPC_CAMPUS
campus
##### Table EPC_LOCALISATION
localisation
##### Table EPC_PREREQUIS + OPERATEUR
Tout l'enchainement
##### Table EPC_OFFRE_PGM_TYPE
Tout l'enchainement


C'est rès loin d're complet mais ça permet de démarer.
