### ISSUE TITLE
Ajouter une colonne dans reference.GradeType pour la gestion de l'examen de maitrise en langue française

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#573]
Lié à #40.

- [x] Ajouter le champs "language_exam_required" (BooleanField, default=False)
- [ ] Modifier le code dans le formulaire de l'admission pour utiliser ce champs dans le ticket #568

**Comment by thuyhanghoang** [comment]
Pouvez-vous mettre ce champ sur cette interface? Merci!
![image](https://cloud.githubusercontent.com/assets/6651769/20798040/b56ebb84-b7dd-11e6-8eeb-c95f339b72fa.png)

**Comment by htmfilho** [comment]
@verpoorten peut-tu mettre ce ticket en priorité? Merci à l'avance.

**Comment by verpoorten** [comment]
@htmfilho Voilà qui est fait si j'ai bien compris ce que voulait Hang

**Comment by htmfilho** [comment]
Voilà @thuyhanghoang . Tu peux le tester.

**Comment by thuyhanghoang** [comment]
testé, ok
