### ISSUE TITLE
Synchroniser les données nécessaires du module 'Offre' de Osis vers Osis-portal

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#58]
Liste des champs à synchroniser : 
[ à déterminer ]

Lié à  uclouvain/osis#285

**Comment by glamarca** [comment]
#### Pour le catalogue de formation : 
###### Table EPC_OFFRE_UCLOUVAIN
offre_uclouvain_id,validite,inti_complet,intit_complet_angl,initi_abrege,durée,nbre_epreuve,credit_ects,type_offre
###### Table EPC_OFFRE
actif,sigle_gestion,langue_principale,activite_anglais,stage,memoire,horaire_particulier,
###### Table EPC_OFFRE_SIGLE
id,sigle,cycle,niveau,orientation,lettres_finales
###### Table EPC_SITE:
nom_site
###### Table EPC_LOCALISATION
localisation


C'est une première approche , c'est loin d'être complet

**Comment by htmfilho** [comment]
Ticket pour l'admission.

**Comment by basmot** [comment]
- [ ] Synchroniser toutes les tables autours/liées à Offre

**Comment by basmot** [comment]
@htmfilho @glamarca @edd19  @chfivet 
Nous devons discuter ensemble pour se mettre d'accord et avoir une stratégie dynamique/fonctionnelle pour synchroniser les données entre Osis et Osis-Portal dans les 2 sens. Par exemple, un ExternalOffer peut être créé côté Osis mais aussi côté Osis-portal. Cette situation arrive également dans Dissertation pour la création des mémoires. Pour ce genre de cas, la solution `Osis-Portal.external_id == Osis.id (et vice-versa)` ne fonctionnera pas.

**Comment by basmot** [comment]
Une solution au problème des synchronisations dans les 2 sens : 
L'utilisation d'un champs uuid, qui aura la même valeur dans Osis et dans Osis-portal.
http://django.readthedocs.io/en/latest/howto/writing-migrations.html

**Comment by htmfilho** [comment]
@glamarca Tester le ticket.

**Comment by glamarca** [comment]
- [ ] Migration des tables 'réfrences' : ajout côté osis => arrive du côté portal
- [ ] Supression du server de queue et vérification des 3 connexion max

**Comment by glamarca** [comment]
@htmfilho @basmot 
J'ai testé la migration des tables de référence, en ajoutant du côté osis, ça fonctionne.
(vous pouvez voir toutes les données de référence qui on comme nom test#58).
Par contre il y a toujours un souci avec les connexion à la queue.
Dès qu'un message est consommé, la connexion se ferme => plus de consumer enregistré sur le server rabbit.
On en reviens toujours au même problème : doit-on fermer la connexion à la fin de la consommation ?
Si je relance la connexion (en faisant un python3 manage.py shell par exemple sur le server), les messages en attentes sont bien consommés et enregistré dans la DB.

**Comment by glamarca** [comment]
Par contre pour la connexion 3x max, je ne sais pas très bien comment tester : si j'arrête le server de queue et que je relance portal , j'ai pika.exceptions.AMQPConnectionError: Connection to 10.1.19.57:5672 failed: [Errno 111] Connection refused, ce qui est logique d'avoir cette erreur et non ConnexionCLosed.
Donc il faut , je pense faire un exept de cette erreur lors de la connexion.
Avec la modif du lancement de la queue dans le wsgi (#441) , c'est là que doit se faire cet except.
Donc je met ce ticket-ci ok , car le ticket en lui-même est bon (migration des table de référence) , et je met une remarque dans le #441
