### ISSUE TITLE
Session pièce jointes supplémentaires ne correspond pas au besoin, comme décrit dans la doc

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#588]
- [x] Les pièces jointes supplémentaires sont obligatoires lorsque le type de demande est "admission". Pas obligatoires en cas d'inscription.
- [x] Les seuls types existent acceptés sont "Lettre de motivation" et "CV"
- [x] l'utilisateur peut choisir "Autre" et informer le contenu du fichier dans le champ "description". 
- [x] Le champ "description" s'affiche seulement quand l'option "Autre" est choisi.
- [x] Les autres pièces jointes uploadé dans les autres onglets ne devrons pas apparaître dans cette onglet.
- [x] La liste de fichiers doit être une table, pas un "row + col"
- [x] Il faut uploader un fichier à la fois, pas plusieurs
- [x] Il faut traduire correctement les textes afficher.

![image001](https://cloud.githubusercontent.com/assets/200272/20603760/4ad884fa-b263-11e6-9de2-4ffef0d46838.png)
a decrit....

**Comment by chfivet** [comment]
@thuyhanghoang

Hello,

Peux-tu tester ça et me dire si tout est bien en ordre ?

Bien à toi,
