### ISSUE TITLE
Modifier dans Applicant, GENDER_CHOICES et CIVIL_STATUS_CHOICES en enumerations

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#591]
Pour simplifier le code il faudrait modifier dans le modèle Applicant, GENDER_CHOICES et CIVIL_STATUS_CHOICES en enumerations.  
(Comme APPLICATION_TYPE_CHOICES dans le modèle Application)

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
