### ISSUE TITLE
Consultation: Charges d'enseignement: Liste des étudiants d'un cours

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#607]
À faire...

**Comment by verpoorten** [comment]
@htmfilho Dur de tester à fond sur le serveur, car il n'y a toujours pas de données concernant l'enrollment

**Comment by verpoorten** [comment]
Test failed car:
En comparant dev.studies et dev.epc
Pour l'enseignant Mathieu Javaux (mjavaux) il manque 1 étudiant dans la liste des étudiants du cours pour le cours LBIR1310 en 2016
Non présent dans la liste sur Osis-Portal BIR1BA/				Piette	Aurélien	54941400

Piette Aurélien n'est même pas dans les students...Mais il est dans la table person.  Problème de synchro?

**Comment by verpoorten** [comment]
@htmfilho @basmot Je pense que la différence entre les 2 listes vient du fait que dans epc on prend les inscriptions avec etd_off_etd.etat_inscr in ('1','3') et dans osis dans la synchro on je reprend que etd_off_etd.etat_inscr in ('1').  La question est de savoir laquelle est la plus correcte???

**Comment by htmfilho** [comment]
C'est juste '1'.
