### ISSUE TITLE
Assimiler Belge

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#61]
User Story

**En tant que** candidat Hors union européenne

**Je veux** faire une assimilation belge

**de sorte que** remplir mon profil.

**lien vers la documentation** : https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/demande-inscription-en-ligne.adoc

**Comment by htmfilho** [comment]
Salut @thuyhanghoang ! @abdelayadi besoin de tout le détail lié a cette demande. Il y a beaucoup de chose déjà dans la documentation, mais c'est important de rafraîchir la mémoire :-) Merci.

**Comment by htmfilho** [comment]
@abdelayadi ,
j'ai corrigé tous les problèmes dans le code de la branche #61. Je te demande de regarder mes commits dans la branche #61 pour savoir ce qui ne va pas, pour éviter que ça arrive la prochaine fois.

Il faut faire attention spéciale aux problème PEP8, bien signalé par PyCharm.

**Comment by htmfilho** [comment]
C'est une epic.
