### ISSUE TITLE
Bugfix dissertation 

### ISSUE THREAD

**Issue by matgerard** [uclouvain/osis-portal#615]
+ DoesNotExist/dissertation/dissertation_to_dir_submit/{pk} error
DissertationRole matching query does not exist.
+ tri alphabétique sujets.
+ liste de choix offer_year a restreindre lors de la création d'un mémoire (uniquement les offer_year auxquels l'étudiant est inscrit)

**Comment by htmfilho** [comment]
@matgerard deployé en qa.

**Comment by htmfilho** [comment]
@matgerard Il y a un conflit avec la branche dev.
