### ISSUE TITLE
Assimiler Belge avec Pièces-jointes

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#62]
User Story

**En tant que** candidat Hors union européenne

**Je veux** joindre les documents

**de sorte que** assimiler belge.

**lien vers la documentation** : https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/demande-inscription-en-ligne.adoc

**Comment by verpoorten** [comment]
@basmot Dans le ticket [50](https://github.com/uclouvain/osis-portal/issues/50) j'ai crée un table AdmissionDocumentFile 
class AdmissionDocumentFile(models.Model):
    applicant = models.ForeignKey('Applicant')
    document_file = models.ForeignKey('osis_common.documentFile')

Par contre, je ne suis pas sûre de savoir comment faire pour les fichiers à joindre en fonction des critères d'assimilation...Il faudrait qu'on en discute ensemble.  Possible mardi?

**Comment by basmot** [comment]
@verpoorten Pas de problème, on en discute demain.

**Comment by htmfilho** [comment]
Voilà! C'est décidé!

**Comment by htmfilho** [comment]
- Enregistrer dans les tables `applicant_assimilation_criteria` et `application_assimilation_criteria` en même temps. 

- Lors de la présentation du formulaire pour la création de une demande, utilisez les données de `applicant_assimilation_criteria` pour réutiliser les données du profil. 

- Lors de la présentation de l'application en lecture, utiliser les données de `application_assimilation_criteria`. 

- Lors de la présentation du formulaire pour l'edition d'une demande déjà soumis, utilisez les données de  `application_assimilation_criteria`.

- Le champ `additional_criteria` dans les tables `applicant_assimilation_criteria` et `application_assimilation_criteria` est utilisé pour relier le critère 5 avec un des critères 1, 2, 3 ou 4.

**Comment by verpoorten** [comment]
Par défaut les critères d'assimilation ne doivent pas oui ou non

**Comment by chfivet** [comment]
@verpoorten J'ai une erreur en local quand je récupère Dev en local depuis l'acceptation de ce Pull Request. 

L'erreur :
TypeError at /admission/profile/8/
object of type 'bool' has no len()

 /home/endloril/python/projects/osis/osis-portal/admission/views/common.py in profile
        data.update(demande_validation.get_validation_status(application, applicant, request.user))

/home/endloril/python/projects/osis/osis-portal/admission/views/demande_validation.py in get_validation_status
        if len(msgs) > 0:

**Comment by chfivet** [comment]
Le soucis est corrigé

**Comment by verpoorten** [comment]
Quand on sélectionne un critère d'assimilation le bloc contenant les documents à intégrer n'apparait pas au bon endroit???

**Comment by verpoorten** [comment]
Attendre que le ticket #415 soit résolut avant de finaliser celui-ci

**Comment by htmfilho** [comment]
@verpoorten le ticket #415 dégage ce ticket ici?

**Comment by verpoorten** [comment]
!!! **Fonctionne mais il faut pousser sur le bouton 'sauvegarder' car il semblerait que pour le moment le bouton prochaine étape ne fonctionne pas** !!! (voir ticket #461)

**Comment by thuyhanghoang** [comment]
@verpoorten @htmfilho @basmot Le liste des pays est de nouveau vide, pouvez-vous ré-établir? Merci!

**Comment by basmot** [comment]
@thuyhanghoang La table Country de la DB de Dev (Osis-portal) est bien remplie (tu peux aller voir dans l'admin).

**Comment by thuyhanghoang** [comment]
Quand je coche Non ppour 7 criteres d'assimilation et puis Sauvegarder => il y a un message d'erreur.

![image](https://cloud.githubusercontent.com/assets/6651769/19468239/967938b6-9515-11e6-8996-0fc1903f9e44.png)

**Comment by verpoorten** [comment]
Par défaut il faut que les 7 critères soient à la valeur NON (dixit thuyhanghoang)

**Comment by thuyhanghoang** [comment]
Il reste encore la validation des documents uploadé par situation. Leila a dit que c'est pour le ticket de validation.
