### ISSUE TITLE
Candidature en ligne

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#624]
A faire

**Comment by htmfilho** [comment]
Voilà @verpoorten ! Les problèmes avec les fichiers de migrations sont réglés.

**Comment by verpoorten** [comment]
@htmfilho Cool merci

**Comment by verpoorten** [comment]
@htmfilho 'done' malgré le fait que je n'ai pas put réellement tout tester sur dev.studies vu le manque des données 2017

**Comment by htmfilho** [comment]
Pas 'done' alors.

**Comment by verpoorten** [comment]
Ca doit être prêt pour lundi non?

**Comment by htmfilho** [comment]
Oui, mais si on'arrive pas a le tester donc pas possible.

**Comment by glamarca** [comment]
La permission 'can_access_attribution' doit être ajoutée au groupe Tutor, sinon personne n'a la permission!

**Comment by verpoorten** [comment]
Directement via l'admin ou autrement?
