### ISSUE TITLE
Choisir l'offre contingentée

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#63]
User Story

**En tant que** candidat

**Je veux** choisir une offre contingentée

**de sorte que** introduire une demande d'inscription à l'UCL.

**lien vers la documentation** : https://github.com/uclouvain/osis-louvain-documentation/blob/dev/doc/business/demande-inscription-en-ligne.adoc

**Comment by htmfilho** [comment]
Salut @thuyhanghoang ! @abdelayadi besoin de tout le détail lié a cette demande. Il y a beaucoup de chose déjà dans la documentation, mais c'est important de rafraîchir la mémoire :-) Merci.

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.
