### ISSUE TITLE
Les enseignants ne savent plus obtenir leurs feuilles de notes sur le portail

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#637]
En prod, je suis l'enseignant du cours LFASB1501. Sur le portail, dans mon bureau, je ne peux pas obtenir mes feuilles de notes
![image](https://cloud.githubusercontent.com/assets/6651769/21228253/66d897f0-c2dd-11e6-892e-5e8728228308.png)

**Comment by htmfilho** [comment]
Le problème avec la file d'attente a été résolu mais un autre problème a été trouvé: ​la feuille de notes n'est pas générée lorsque le professeur est affecté à plus d'un cours.

**Comment by htmfilho** [comment]
Je ne sais pas comment reproduire le problème localement. Tout fonctionne. :-(

**Comment by thuyhanghoang** [comment]
ça marche pour le moment!!!!

**Comment by mahianth** [comment]
Un enseignant (Jan De Mol) a écrit au Service Desk à 10:01 pour ce problème.

Peut-il réessayer à présent ?
Doit-il se déconnecter et se reconnecter à son bureau virtuel ?

**Comment by htmfilho** [comment]
Il peux réessayer. Dans OSIS, nous ne sauvons pas des données dans la session, donc se reconnecter ne fait aucune différence.
