### ISSUE TITLE
Création de tests pour dissertation

### ISSUE THREAD

**Issue by matgerard** [uclouvain/osis-portal#638]
Création de tests pour dissertation

**Comment by htmfilho** [comment]
Merci de créer les tests dans le contexte des tickets normaux, pas dans un ticket spécial. Les changements dans le code doivent venir avec des tests pour garantir qu'il ne casse pas les fonctionnalités existantes. Le patch récent, ça était un exemple clair. S'il y avait des tests, cela n'arriverait pas. Les nouvelle fonctionnalité viens avec les tests par défaut.

À partir du 1er janvier, toutes les pull request doivent être accompagnées de tests unitaires.
