### ISSUE TITLE
Installer couchbase en dev

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#64]
Installer la version community de CouchBase directement sur le serveur dev et qa et sur un serveur dédier en prod.

**Comment by glamarca** [comment]
- Serveur osis-db-dev installé.
Vérifier si plusieurs instances peuvent êtres lancées sur le même serveur.

**Comment by htmfilho** [comment]
Je ne comprend pas pourquoi plusieurs instances sur le même serveur.

**Comment by glamarca** [comment]
C'est ce que SIPR a demandé de tester , car c'est comme cela qu'ils installent les db sur les serveurs physique normalement. (Enfi si j'ai bien compris!)

**Comment by htmfilho** [comment]
Ils installent plusieurs instances d'Oracle sur un seul serveurs?!

**Comment by glamarca** [comment]
On oublie les différentes instances sur le même serveur , de plus ce n'est pas conseillé par couchbase.

> Il me semble qu'on avait convenu qu'on ferait un osis-db-qa et osis-db-prod dans un premier temps.
> A long terme, quand les DBA auront eu le temps de se familiariser avec CouchBase et qu'on prendra la décision (ou pas) de construire une infrastructure dédié à CouchBase, on verra bien ce qu'on fera  (plusieurs serveurs ou plusieurs instances / serveur).

> Pas de soucis pour les VM supplémentaires. Tu me tiens au courant ?

> Olivier

J'ai également demandé 2 VM pour osis-dbprod , pour pouvoir tester l'ajout d'un node
