### ISSUE TITLE
[bugfix] Ajout des uuids dans les search_fields

### ISSUE THREAD

**Issue by chfivet** [uclouvain/osis-portal#649]
Permettra de filter les éléments de la base de données sur base de l'uuid.

**Comment by chfivet** [comment]
@htmfilho Peux-tu me donner les accès Admin sur QA Potal ?
Je test ensuite

**Comment by htmfilho** [comment]
Voilà.

**Comment by chfivet** [comment]
@htmfilho C'est en ordre et testé Merci
