### ISSUE TITLE
Installer RabitMQ en dev, qa et prod

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#65]
Installer RabitMQ directement sur le serveur dev et qa et sur un serveur dédier en prod.

**Comment by glamarca** [comment]
Chaque environnement à un serveur dédié.

- Serveurs uniquements accessibles depuis UCL
- Pas de VIP publique ni DNS car uniquement communication entre serveurs ou depuis postes intra UCL

##### Dev : 
console admin : http://192.168.225.29/
api : http://192.168.225.29/api
> user guest / password guest (pour le moment)

##### QA : 
console admin : http://192.168.225.30/
api : http://192.168.225.30/api
> user et password sur demande

##### Prod : 
console admin : http://192.168.225.31/
api : http://192.168.225.31/api
> user et password sur demande


Il reste à configurer les ports d'accès.

**Comment by glamarca** [comment]
3 serveurs installés.
A tester en même temps que le merge des applications vers dev , qa et prod
