### ISSUE TITLE
Connecter à Couchbase

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#66]
Ajouter les dépendances nécessaires et développer un module de connexion.

**Comment by glamarca** [comment]
Pour infos : 
http://django-cbtools.readthedocs.org/en/latest/tutorial.html
https://github.com/smarttradeapp/django_cbtools

**Comment by htmfilho** [comment]
Très peux de utilisation de django-cbtools. Seulement 2 contributeurs, 2 forks et 3 étoiles.

**Comment by htmfilho** [comment]
http://developer.couchbase.com/documentation/server/4.0/sdks/python-2.0/introduction.html
https://pypi.python.org/pypi/couchbase
