### ISSUE TITLE
Amélioration de l'affichage des notes de l'étudiant

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#678]
- [x] Changer l'ordre de la iste des Anac de l'étudiant : la plus rédente en premier
- [x] Ajout dune index sur le champ 'registration_id' de la table StudentPerformance
- [x] Supprimer la colonne 'Inscr'
- [x] Modifier le nom de la colonne 'Crédits' en 'Crédités'
- [x] Modification de la légende
- [x] Décoler l'état de l'inscription de la note
- [x] Modifier le nom de la page 'Performance'
- [x] Paramétrage du temps de afraîchissement

**Comment by thuyhanghoang** [comment]
ok
