### ISSUE TITLE
Mise en place de l'application 'Attestation'

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#683]
- [x] Créer application `attestation`
- [x] Queue Rpc pour les status des attestations
- [x] Time-out de l'appel RPC configurable
- [x] Affichage de la liste des attestation et leurs status
![image](https://cloud.githubusercontent.com/assets/11191415/23109918/6e51307c-f71d-11e6-8dda-173a251a95ec.png)
- [x] Utilisation du webService EPC pour récupérer le PDF (URL, utilisateur et password configurable)
- [x] Pour les administrateurs, il est possible de voir les attestation en entrant un registration_id

**Comment by glamarca** [comment]
### Vue Etudiant : 
- Ajout du lien sur le dashboard
![student_dashboard](https://cloud.githubusercontent.com/assets/11191415/23111366/760e2710-f728-11e6-83d5-462d5ff419e5.png)
- Liste des attestions accessibles avec status
![student_attestation_statuses](https://cloud.githubusercontent.com/assets/11191415/23111372/7ed5e932-f728-11e6-9e30-6ba174af12bd.png)
- Téléchargement du PDF
![student_attestation_pdf](https://cloud.githubusercontent.com/assets/11191415/23111375/83019f4c-f728-11e6-862b-3e333f8cabba.png)

### Vue Admin:
- Refactoring du template 'Faculty Administrator' et ajout du lien vers l'administration des attestations
![faculty_admin_template](https://cloud.githubusercontent.com/assets/11191415/23111381/94c21310-f728-11e6-9bec-c0f8f8b0ffc9.png)
- Recherche des attestations et leurs status via le noma de l'étudiant
![admin_select_student_attestations](https://cloud.githubusercontent.com/assets/11191415/23111386/9c7f3c2c-f728-11e6-89e6-af812487b043.png)
- Liste des attestations de l'étudiant et leurs status
![admin_student_attestation_statuses](https://cloud.githubusercontent.com/assets/11191415/23111400/af8f4f46-f728-11e6-90f0-7a7a2ac46642.png)
- Téléchargement du PDF
![admin_student_attestation_donwload](https://cloud.githubusercontent.com/assets/11191415/23111409/b79412b2-f728-11e6-9090-0e2fe725363b.png)

**Comment by thuyhanghoang** [comment]
- Quand mon "Person" ne lie pas à un "Utilisateur", je clique sur "Mes attestations" dans mon dashboard, je vois ce message d'erreur:
![image](https://cloud.githubusercontent.com/assets/6651769/23339299/c01078da-fc1f-11e6-9003-375f9791d570.png)
- Je change mon login comme un étudiant avec numero de FGS:  00328700. Je clique sur "Mes attestations" sur dashboard, je vois le message "aucune attestation disponible"
![image](https://cloud.githubusercontent.com/assets/6651769/23339217/11a463b6-fc1e-11e6-8f69-9815aef3c282.png)
- Je vais dans l'interface pour tester l'attestation pour un noma donnée (09101500)
![image](https://cloud.githubusercontent.com/assets/6651769/23339263/d8810872-fc1e-11e6-9af9-948afbb0fef2.png)
je vois aussi le message "aucune attestation disponible"
![image](https://cloud.githubusercontent.com/assets/6651769/23339277/283260f0-fc1f-11e6-8304-c737f3d1c8a4.png)

**Comment by thuyhanghoang** [comment]
comme c'est deja en Prod, je crée un autre ticket pour ça #853
