### ISSUE TITLE
Harmoniser l'utilisation des templates dans osis-portal

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#684]
Apparemment, les applications n'utilisent pas le même layout. Tout le monde doit utiliser le même layout, qui est le base/templates/layout.html

**Comment by chfivet** [comment]
@htmfilho c'est un soucis propre à Dissertation ou pour toutes les applications?

**Comment by basmot** [comment]
@chfivet C'est pour toutes les applications.

**Comment by glamarca** [comment]
Remarques : 
Faire attention car les menu accessibles pour admission et dashboard (qui doit être le point d'entré des autres apps) ne sont pas les même, ni les page de login et de logout.
Il faut soit paramétriser le layout principal, soit faire un layout principal minimal, qui sera étendu par les layout principaux de admission et dashboard, et toutes les pages qui dépendent étendent ces deux layout (C'est la solution la moins couteuse)

**Comment by htmfilho** [comment]
Il n'y a plus d'admission.

**Comment by chfivet** [comment]
Le ticket peut être fermé comme Admission n'est plus là

**Comment by htmfilho** [comment]
Hum... Il faut quand même vérifié les autres modules.

**Comment by albrugnetti** [comment]
Après vérification dans les différents modules, il n'y a que le module "catalogue de formation" qui semble ne pas utiliser "base/templates/layout.html".
Les autres modules utilisent soit "dashboard_layout.html" qui hérite lui même de "base/templates/layout.html", soit  "base/templates/layout.html" 

@htmfilho Que dois-je faire pour le catalogue de formation ?

**Comment by htmfilho** [comment]
Rien. L'application 'catalog' n'est pas encore fait. Merci pour la vérification.
