### ISSUE TITLE
Ajouter la navigation vers "Inscription aux examens"

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#692]
- [x] Nouveau bloc à la page d'accueil du dashboard, qui est un lien qui pointe vers le choix de l'offre dans laquelle s'inscrire

**Comment by basmot** [comment]
Ok en Dev.

**Comment by glamarca** [comment]
Apps 'exam_enrollment' ajoutée dan settings Dev et QA, mais pas Prod.
