### ISSUE TITLE
Créer le formulaire "Inscription aux examens", accédé à partir du choix de l'offre

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#694]
- [x] Ajouter un texte informatif à l'etd : "vous êtes inscrit par défaut à tous les examens cochés ci)dessous. Vous pouvez vous désinscrire aux examens en décochant et cliquant sur 'valiser' "
- [x] Créer le template
- [x] Créer un template de JSON qui est envoyé après le choix de l'offre. 
- [x] Les messages devront être envoyés vers la queue nommée `exam_enrollment_form` (créer un client RPC)
- [x] Créer un template de JSON qui est reçu (pour la génération du formulaire)
- [x] Dans le formulaire, la colonne "inscrit" est cochée si etatExam est 'I', 'Y' ou 'P'
- [x] Les informations textes (légende) affichée en-dessous du formulaire doivent être les mêmes que dans l'app `performance`
- [x] Ajouter le lien dans "Choix de l'offre" qui pointe vers "Inscriptions au examens"

Note: par défaut avec cette opération, l'étudiant est inscrit par défaut à tous les examens, même s'il n'a pas validé le formulaire !

**Comment by htmfilho** [comment]
Comme il n'y a pas de pull request pour ce ticket je vais l'enlever de la release 0.7.0.

**Comment by htmfilho** [comment]
J'ai le mi dans la release suivante 0.8.0.

**Comment by basmot** [comment]
@htmfilho La queue `rpc_exam_enrollment_form` est bien déclarée sur RabbitMq en dev, mais il n'a aucun consumer. Or c'est EPC qui devrait consumer... C'est probablement un problème de config côté EPC. 
NB : Ce n'est pas une issue bloquante pour la release car ExamEnrollment ne sera pas déployé en prod.

**Comment by basmot** [comment]
@htmfilho Ok c'est bon, j'ai compris d'ou venait le problème. C'est corrigé.
Testé & OK en Dev.
