### ISSUE TITLE
Gérer le cas où la queue n'est pas disponible

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#697]
Que faire...
- Si le formulaire d'inscription ne peut pas être téléchargé?
Rien à faire (message d'erreur par défaut).
- Si l'étudiant a rempli le formulaire mais que la queue n'est pas disponible?
- [ ] Créer un nouveau modèle pour enregistrer le message avant de l'envoyer dans la queue
- [ ] Afficher message "votre demande d'inscription a bien été soumise"

**Comment by verpoorten** [comment]
Sera complèter via le ticket #871

**Comment by htmfilho** [comment]
@verpoorten quel partie est prêt dans ce ticket et quel partie sera complété via le #817?

**Comment by verpoorten** [comment]
@htmfilho tout est prêt vu la description de ce ticket.  Mais, vu les compléments d'informations dans le ticket 871certaines choses vont changer

**Comment by htmfilho** [comment]
D'accord. Merci.
