### ISSUE TITLE
Modifier charge d'enseignement + candidature en ligne

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#699]
- [x] Pour que la charge d'enseignement soit par défaut sur l'année academique actuelle (et non sur le prochain)
- [x] Si un enseignant a pour un même cours 2 charges : une cotitulaire et une coordinateur, il peut reconduire 0-1 ou 2 charges.  S'il en conduit une, lui laisser la possibilité de reconduire l'autre par après  

Après avoir fait les tickets epc https://github.com/uclouvain/epc/issues/1120 et https://github.com/uclouvain/epc/issues/1130
- [x] Vérifer qu'on ajoute bien les candidatures dans epc 
- [x] Vérifer qu'on modifie bien les candidatures dans epc 
- [x] Vérifer qu'on supprime bien les candidatures dans epc

**Comment by htmfilho** [comment]
Le deuxième point n'est pas nécessaire => _N'afficher que les onglets 2017-2018 et 2016-2017 (ne plus afficher 2015-2016)_. 

Il faut afficher le donnée que se trouve dans la base de donnée. Il ne faut conditionner l'affichage dans le code.
