### ISSUE TITLE
Mettre les conditions de déploiement pour la nouvelle app exam-enrollment

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#701]
Il faut permettre de déployer Osis-portal en supprimant `exam-enrollment` des installed apps dans le settings.

**Comment by basmot** [comment]
Les autrs configs dans le Settings.py ont été faites dans #692

**Comment by glamarca** [comment]
@basmot 
OK, testé sans exam_enrollment, l'application tourne.
