### ISSUE TITLE
Amélioration de la publication des Notes

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#702]
- [x] Il ne faut pas aller à la ligne quand il n y a pas de note
- [x] Afficher la date de prochaine mise à jour
- [x] Modifier la phrase lorsque il n'y a pas de note : "Vos résultats ne sont pas encore disponibles."
- [x] Rendre le champ Json "read-only" dans la table studend_performance afin d'accèlérer l'affichage de la liste.
- [x] Gérer les messages en erreur pour la publication des notes
- [x] Afficher un message si le time_out de la génération du document est atteint, en cas de surcharge.
- [x] MAJ reference osis-common : 0.11.0

**Comment by htmfilho** [comment]
Utiliser `colspan="2"` pour les `th` Jan, Juin et Sept. Mettre le trois etat d'inscription aux examens dans dans sa propre colonne.

**Comment by glamarca** [comment]
![etdportalsurchargeserveur](https://cloud.githubusercontent.com/assets/11191415/22401145/833a7274-e5c9-11e6-8ca8-210f4d4260ce.png)

![etdportalnotesnondispo](https://cloud.githubusercontent.com/assets/11191415/22401152/fa5ac66a-e5c9-11e6-9c3b-ab5ba8ccbf2f.png)

**Comment by htmfilho** [comment]
Le message me semble très technique. Afficher la date de la dernière mise à jour est suffisant. Je suggère de mettre les dates en haut de l'onglet.

**Comment by glamarca** [comment]
@htmfilho Ok pour les dates en haut, mais si après 15 s il n'y a pas de renouvellement, ce serait bien de prévenir pourquoi. (et éviter dans ce cas qu'il ne renouvelle la page inutilement). Je peux simplifier le message si il faut.

**Comment by glamarca** [comment]
![image](https://cloud.githubusercontent.com/assets/11191415/22405806/97e3a0b8-e648-11e6-9c75-7736e4777c62.png)

**Comment by htmfilho** [comment]
Bien pensé. Merci.
