### ISSUE TITLE
Modèle pour le formulaire dynamique dans le choix de l'offre de formation admission

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#71]
Il faut faire la même chose que uclouvain/osis#302 du coté portal, mais le modèle gère aussi des reponses.

![entity-relationship-diagram-portal](https://cloud.githubusercontent.com/assets/200272/14099361/1b3f29b0-f585-11e5-8f9b-ac1cece40c63.png)

**Comment by verpoorten** [comment]
@htmfilho TextField ok pour clob?

**Comment by htmfilho** [comment]
:+1:

**Comment by verpoorten** [comment]
@htmfilho  saurais-tu me donner un exemple pour un input dans la base de données telle qu'elle est décrite dans le schéma... j'ai un doute....

**Comment by htmfilho** [comment]
Peux-tu anticipé te doute? Je ne peux pas faire ça rapidement cette semaine.
