### ISSUE TITLE
Navigation vers l'écran d'accueil de internship

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#741]
- [x] Lien dans la page d'accueil (template vide) du dashboard vers l'app internship
- [x] Tester si l'utilisateur est un etd (ne peut accéder à Intership ninon)
- [x] Tester si l'app est installée

**Comment by glamarca** [comment]
@edd19 
vérifier les traductions
![image](https://cloud.githubusercontent.com/assets/11191415/23001131/ecd13858-f3e3-11e6-9041-4eb6c17e8d60.png)

**Comment by glamarca** [comment]
@htmfilho @edd19 
Normalement seul les étudiants de médecine peuvent accèder à l'application.
A voir comment faire, dans la version précedente de internship c'est basé sur la table internship_student_information.

**Comment by edd19** [comment]
@htmfilho @glamarca 
N'est-ce pas mieux de créer un nouveau ticket pour traiter de cette problématique de droit d'authorisation d'accès ?

**Comment by htmfilho** [comment]
Oui, c'est possible. Si le ticket est bon en dev, tu peux le mettre en Done.

**Comment by edd19** [comment]
@htmfilho 
J'ai tout de même fait un pull request pour ajouter les traductions.
