### ISSUE TITLE
Corrections dans Affichage de notes sur le bureau virtuel des étudiants

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#750]
- [x] Modification de l'admin de performance_result : ne mettre que l'anac dans la liste des filtre afin de ne pas ralentir l'affichage
- [x] Gérer la date d'update par défaut de manière plus fines : La plus forte affluence à lieu dans les 24h qui suivent la publication de snotes. La mise à jour par défult se fera ainsi : 
  - Dans les 24h si la note vient d'être publiée (Il risuqe peu d'y avoir de changement dans les 24h et ça permet de ne plus apeller la génération du xml au moment de la forte affluence.
  - Dans les 12h pour les notes de l'année en cours plus de 24h après la publication (ça permet de pendre en compte, entre autre, les encodage fait dans osis après la date de diffusion)
  - Dans le mois pour les Notes des années précédentes (Si besoin on republiera aux cas par cas).
- [x]  Ajouter la phrase "Ce composant reflète l'état des informations enregistrées dans les bases de données officielles de l'université au moment de leur affichage et selon des modalités de diffusion décidées par le secrétariat de votre faculté." à la page de la liste des offres
![image](https://cloud.githubusercontent.com/assets/6651769/22554525/a7606ba0-e960-11e6-9fad-950374bc00cc.png)
- [x]  Ajouter la phrase: "Cette feuille de résultats est destinée à la communication entre la faculté et les étudiants. Seule l'annexe au diplôme que l'étudiant reçoit avec celui-ci et qui reprend la liste de tous les cours suivis durant un programme d'étude et des points obtenus peut être considérée comme un transcript officiel." à la page des notes
![image](https://cloud.githubusercontent.com/assets/6651769/22554621/11f44a2c-e961-11e6-95ca-7d16ccd5caeb.png)
- [x] Ajouter la phrase: "La diffusion des résultats de la (des) session(s) de ..... n'a pas encore été autorisée par votre faculté." si l'étudiant est inscrit à la session et la diffusion de notes de cette session de son programme n'est pas encore ouverte. (..... = janvier, juin ou septembre)
- [x] Le nom de la colonne: pour le moment: Jan.*, Juin*, Sept.* => il faut enlever *, remplacer Jan. par Janv. (2 endroits: le nom de la colonne et en haut pour la moyenne)
- [x] Dans la liste des offres: la colonne Année, il faut marquer: 2015-2016 au lieu de 2015
- [x] Dans la liste des offres, pour le moment tu prends tous des inscriptions, il ne faut pas prendre tous les états d'inscription à l'offre, pas des "erreur", pas "annulation", ... Dans OSIS, ni OSIS-Portail, on a l'état d'inscription à l'offre, on n'a pas encore migré ce champ, il faut utiliser le XML que Evase envoie:
![image](https://cloud.githubusercontent.com/assets/6651769/22586663/50ad640e-e9fe-11e6-8342-4d6d068df99a.png)
```diff
- Ce point est gérer lors de la publication initiale et programmée.
- C'est EPC qui choisit les offres à publier
```

- [x] Dans la colonne "Etat d'**inscription aux cours**": si c'est X: il faut afficher Ext, si c'est T => afficher Test
- [x] Indiquer si l'etat d'inscription à une offre est en cessation

J'espère que la liste de demande est fini pour cette session. Pourque tu puisses travailler dans l'attestation :)

**Comment by glamarca** [comment]
@htmfilho 
J'inclus dans ce ticket la modification de l'admin pour le "filter".

**Comment by glamarca** [comment]
@thuyhanghoang 
Concernant la phrase "La diffusion des résultats de la (des) session(s) de janvier n'a pas encore été autorisée par votre faculté."
- Que se passe-t-il si il n'y a pas de date de diffusion.
- Que se passe-t-il quand la date de diffusion est après le passage à la session de juin (C'est à dire le 1er Février)

**Comment by glamarca** [comment]
@thuyhanghoang 
Voici les premiers changements (Ce ne sera visible en dev que quand ce sera mergé).
L'affichage de la dernière phrase demande une modif du côté EPC (ici je la montre juste, le business côté portal est fait, mais il faut ajouter l'unfo au json produit par epc).
Le ticket lié est : https://github.com/uclouvain/epc/issues/1173
![etdportallistepgms](https://cloud.githubusercontent.com/assets/11191415/22575769/2662ecaa-e9b8-11e6-812c-68351122b150.png)

![etdnotesmentionlegale](https://cloud.githubusercontent.com/assets/11191415/22575771/2af13ec0-e9b8-11e6-8e9d-5f50232cfef3.png)

**Comment by thuyhanghoang** [comment]
@glamarca as tu la réponse pour tes 2 questions au dessus?
    Que se passe-t-il si il n'y a pas de date de diffusion.
    Que se passe-t-il quand la date de diffusion est après le passage à la session de juin (C'est à dire le 1er Février)
C'est dans XML que Evase envoie, il y a un bloc pour chaque session, en fonction que si l'étudiant s'inscrit à la session ou pas, si c'est oui, il compare la date de diffusion de notes avec la date du jour

**Comment by thuyhanghoang** [comment]
@glamarca Je vais compléter d'autres points maintenant

**Comment by glamarca** [comment]
@thuyhanghoang 
Ok ja vais regarder ce qui est dans le xml pour la phrase.

**Comment by glamarca** [comment]
@thuyhanghoang 
Tu veux bien ne pas supprimer les ajouts que je mets dans la description du ticket quand tu l'update ! (Il n'y a plus les points technique, et les chackbox ont disparues) ;-)

**Comment by thuyhanghoang** [comment]
@glamarca ah désolée, car la fenêtre était toujours ouverte/édité sur mon browser. Mais comme il y a des problème dans tous les sens, je ne pouvais pas concentrer pour terminer ce ticket :(

**Comment by glamarca** [comment]
![etdportalcessation](https://cloud.githubusercontent.com/assets/11191415/22623562/a36305b6-eb5f-11e6-95ff-e6e75237ffa2.png)

![etdportal05022017](https://cloud.githubusercontent.com/assets/11191415/22623563/a93ed58c-eb5f-11e6-9175-3244aa4e1a38.png)

**Comment by thuyhanghoang** [comment]
qa ok, parfait!
