### ISSUE TITLE
Candidature en ligne - ajouter un controle d'accès en fonction des affectations des enseignants

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#785]
Actuellement l'accès à la candidature en ligne est conditionné par le type d'affectation des enseignants.  Ces infos sont des informations qui sont extraites depuis sap.
Si AB, AH,AE,AF,CU,AR,SR => ok

Par ailleurs on vérifie la présence ou non du matricule dans la table fgsuidldap

**Comment by htmfilho** [comment]
@philbru peux-tu nous aider avec ça ? Merci d'avance.
