### ISSUE TITLE
[BugFix] Validation du formulaire fonctionne en dev, mais pas en qa

### ISSUE THREAD

**Issue by verpoorten** [uclouvain/osis-portal#790]
La même action ne donne pas la même chose en dev et en qa 
DEV :
![formulaire_dev](https://cloud.githubusercontent.com/assets/5947635/22821369/0a741e38-ef7b-11e6-9bd9-eea2149f14a5.png)
QA : 
![formulaire_qa](https://cloud.githubusercontent.com/assets/5947635/22821379/160c7204-ef7b-11e6-96fa-fdef394041b8.png)

**Comment by glamarca** [comment]
@verpoorten @htmfilho 
Problème avec les données de QA : 
ERROR ['MultipleObjectsReturned: get() returned more than one TutorApplication -- it returned 3!', ' File "django/core/handlers/base.py", line 149, in get_response', ' File "django/core/handlers/base.py", line 147, in get_response', ' File "django/contrib/auth/decorators.py", line 23, in _wrapped_view', ' File "django/contrib/auth/decorators.py", line 23, in _wrapped_view', ' File "django/contrib/auth/decorators.py", line 23, in _wrapped_view', ' File "attribution/views/online_application.py", line 560, in save', ' File "attribution/views/online_application.py", line 292, in get_terminating_charges', ' File "attribution/views/online_application.py", line 94, in get_attribution_data', ' File "attribution/views/online_application.py", line 136, in get_attribution_informations', ' File "attribution/models/tutor_application.py", line 87, in find_tutor_learning_unit_year', ' File "django/db/models/manager.py", line 122, in manager_method', ' File "django/db/models/query.py", line 391, in get']
