### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one Student -- it returned 2!

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#791]
https://sentry.osis.uclouvain.be/uclouvain/osis-portal/issues/16727/

```
MultipleObjectsReturned: get() returned more than one Student -- it returned 2!
(4 additional frame(s) were not displayed)
...
  File "performance/views/main.py", line 45, in view_performance_home
    stud = student.find_by_user(request.user)
  File "base/models/student.py", line 102, in find_by_user
    return find_by_person(person)
  File "base/models/student.py", line 94, in find_by_person
    student = Student.objects.get(person=a_person)

MultipleObjectsReturned: get() returned more than one Student -- it returned 2!
```

**Comment by glamarca** [comment]
L'erreur est liée à une mauvaise synchronisation des students.
Certains utilisateurs sont lié à plusieurs objets students (et donc plusieurs registration_id).
C'est la conséquence d'offre_enrollment qui porte sur la même offre , pour le même étudiant, mais pour plusieurs registration_id.
Dans EPC, ces étudiants ont d'office une inscription non valide, et cela doit être pris en compte lors de la migration (suppression des student non valide).

**Comment by glamarca** [comment]
Lié à https://github.com/uclouvain/osis-legacy-sync/issues/375

**Comment by htmfilho** [comment]
Dupliqué par le #923
