### ISSUE TITLE
[Technique]Préparer  Osis-Portal a utiliser complètement le SSO institutionnel 

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#794]
- [ ] Suprimer la directive qui force la réauthentification sur les serveurs.
- [x] Suprimer les boutons logout de l'application.

**Comment by glamarca** [comment]
@htmfilho 
Sur Dev, je vais laisser la réauthentification obligatoire, car sinon ça va devenir compliqué de tester les deux parties de portal (vu que c'est le même Django qui gère les deux, un utilisateur loggé via shibboleth, ou via admission c'est la même chose)

Les boutons 'Logout' seront affichés ou cachés suivant l'environnement.

**Comment by htmfilho** [comment]
D'accord.

**Comment by glamarca** [comment]
@htmfilho 
J'ai fait les modifs dans le code, qui se racorderont avec les modifs sur le serveur.
Par contre il faudra faire attention lors de la mise en commun du template avec Admission, car dans le cas d'admission, il ne faut pas enlever le bouton logout (authentification Django et non shibb)

**Comment by htmfilho** [comment]
Il n'y a plus d'admission. :-/

**Comment by glamarca** [comment]
Dev OK : 
- Bouton logout absent
- Si loggé dans le portail, plus besoin de se logger dans osis-portal
