### ISSUE TITLE
S'assurer que l'application reste fonctionnelle même si l'application "attribution" n'est pas installée

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#798]
L'application est installée en Dev et QA, mais elle ne doit pas être installée en Prod pour le moment.

**Comment by glamarca** [comment]
@verpoorten 
Vérifier en DEV sans Attribution : OK.

**Comment by glamarca** [comment]
@htmfilho 
attribution en Dev et Qa mais plus en prod
