### ISSUE TITLE
Faire hériter de 'SerializableModelAdmin' toutes les classes Admin des modèles synchronisés avec Osis

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#808]
lié à : https://github.com/uclouvain/osis-common/releases/tag/0.12
- [x] Mettre à jour la ref osis-common
- [x] Faire hériter les classes Admin de SerializableModelAdmin

**Comment by basmot** [comment]
Lié à uclouvain/osis_common#123
- [ ] Mettre à jour la ref osis-common
- [ ] Faire hériter les classes Admin de SerializableModelAdmin
