### ISSUE TITLE
[Publication des Notes] Supprimer la phrase 'La publication des notes n'a pas encore été validée par votre fac'

### ISSUE THREAD

**Issue by glamarca** [uclouvain/osis-portal#811]
Actuellement les condition d'affichage de la phrase ne sont pas correctes, et demandent un changement dans les données envoyées par EPC.
Afin de ne pas troubler les étudiants, cette phrase sera temporairement supprimée, le temps que les condition d'affichage soit gérées correctement par EPC

**Comment by htmfilho** [comment]
Salut @glamarca , après la fusion de un pull request, il faut mettre le ticket dans le pipeline "In Test".

**Comment by glamarca** [comment]
@htmfilho désolé, je viens de m'en rendre compte.
