### ISSUE TITLE
Corriger le message d'erreur

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#813]
![image](https://cloud.githubusercontent.com/assets/6651769/23011592/2574436a-f422-11e6-8f97-376d54909b9b.png)
remplacer innatendue en inattendue

**Comment by matrixise** [comment]
Pourquoi cette issue n'est-elle pas closed ?

**Comment by albrugnetti** [comment]
@matrixise  C'est une bonne question... Besoin d'une validation?

**Comment by htmfilho** [comment]
@matrixise l'analyste @thuyhanghoang à créé le ticket et elle a besoin de valider sa demande. J'ai expliqué ça à toi @albrugnetti lundi passé.

**Comment by thuyhanghoang** [comment]
En Dev je n'arrive plus à produire cette erreur. En QA, j'arrive de re-produire
![image](https://cloud.githubusercontent.com/assets/6651769/23339112/72a758f6-fc1b-11e6-92f2-cbd489d56519.png)
Je n'ose pas de changer mon profils en Dev, j'en ai besoin pour tester. Je testerai plus tard ce ticket.
