### ISSUE TITLE
Inverser le nom et prénom de l'étudiant

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#824]
Sur la feuille de notes dans le bureau virtuel de l'étudiant, le prénom de l'étudiant affiché à la place du nom et inversement. Il faut le corriger
![image](https://cloud.githubusercontent.com/assets/6651769/23123021/fee87bba-f766-11e6-9c75-d76e9fa60724.png)

**Comment by glamarca** [comment]
@thuyhanghoang 
Normalement on met le Prénom avant le Nom (d'où prénom), mettre le nom en premier c'est une habitude de l'école en fait!
Donc plutôt que d'inverser , est-ce que je peux inverser les nom des colonnes?

**Comment by glamarca** [comment]
@thuyhanghoang 
Après tests , c'est bizare en mettant Prénom, Nom. Il faudrait enlever la virgule dans ce cas , mais ça reste bizare, donc  je vais faire comme tu as dit.

**Comment by thuyhanghoang** [comment]
@glamarca il faut que la colonne Nom et Prénom correspondent bien les données affichées. Au niveau de l'ordre, il faut que ce soit le même ordre que la page précédente (avec la liste des offres auxquelles l'étudiant s'inscrit).

**Comment by thuyhanghoang** [comment]
ok
