### ISSUE TITLE
Corriger lr texte sur le dashboard

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#833]
Ce n'est pas "Encodage des notes", c'est "Mes feuilles de notes"
![image](https://cloud.githubusercontent.com/assets/6651769/23204840/598ea580-f8e8-11e6-8fa5-9bbc1f4d00c7.png)

**Comment by thuyhanghoang** [comment]
@htmfilho @albrugnetti je ne sais pas si c'est lié à ce ticket ou pas, mais j'ai une espace vide après "Mes feuille de notes"
![image](https://cloud.githubusercontent.com/assets/6651769/23249718/0993dbf4-f9a6-11e6-8c10-e7253c5364ba.png)

**Comment by albrugnetti** [comment]
@htmfilho @thuyhanghoang Les deux problèmes ne sont pas liés. 
Ce dashboard est composé de deux parties : 
   - Professeur : Mes feuilles de notes, Ma charge d'enseignement, Mes candidatures
   - Etudiant : Mes notes, Mes attestations, Stage, Inscription aux examens

Après discussion avec @thuyhanghoang, je vais aligner à gauche "Mes candidatures"

**Comment by thuyhanghoang** [comment]
@albrugnetti @htmfilho ok, re-attribue moi quand c'est en Dev. Merci!

**Comment by htmfilho** [comment]
http://masonry.desandro.com/#getting-started

**Comment by albrugnetti** [comment]
@htmfilho  Using predefined width value on grid-item for better rendering

**Comment by thuyhanghoang** [comment]
dev ok
![image](https://cloud.githubusercontent.com/assets/6651769/23339136/d22e1760-fc1b-11e6-96da-dc2bbe86e92e.png)
