### ISSUE TITLE
Empêcher l'étudiant de se désinscrire à un examen obligatoire

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#835]
- [ ] Ajouter un champs `can_unenrol_to_exam` dans le JSON de test
- [ ] Utiliser ce flag pour disable le checkbox d'inscription si `can_unenrol_to_exam == False`
- [ ] Ajouter cette info à l'étudiant dans le div info (en bleu) : "Si un des choix est désactivé et coché par défaut, c'est que c'est un examen obligatoire et que vous ne pouvez par conséquent pas vous désinscrire à cet examen"

**Comment by basmot** [comment]
@verpoorten J'ai discuté avec @enizeyimana , et enfait il ne faut pas gérer les inscriptions obligatoires du côté de Osis-portal ; aparemment, les étudiants savent si c'est un examen obligatoire ou pas. Et donc, il n'y a jamais de case 'checkbox' non cochée. Si l'etd décoche un examen obligatoire, Evase traite cela côté EPC et ça n'a aucun effet sur l'inscription (il reste inscrit).
Il n'y a donc rien à faire pour cette issue... Je peux donc la fermer.

**Comment by htmfilho** [comment]
Êtes-vous absolument sûr? Un système ne doit pas supposer que l'utilisateur a une connaissance préalable, donc il ne fera pas des erreurs évidentes. Cela semble être une hypothèse fragile.

**Comment by basmot** [comment]
@htmfilho Je suis d'accord, mais : 
- Dans le formulaire actuel du bureau virtuel (sur le portail ucl), il n'y a jamais eu d'info concernant cela. Cela n'a jamais été traité du côté du portail. 
- Je n'ai aucun moyen dans Osis de détecter cette information
- Cette info d'examen ogligatoire ne se trouve pas non plus dans le XML envoyé par EPC. 

Ce serait donc une info supplémentaire qu'on proposerait à l'étudiant ? Et je dois demander à @enizeyimana ses fonctions qui permettent de dire si un examen est obligatoire ou non.

**Comment by htmfilho** [comment]
Aiaiai! Ok.

**Comment by basmot** [comment]
Bon, après rediscussion avec @enizeyimana, il reconfirme que cela n'est pas possible à gérer.
