### ISSUE TITLE
Il manque des notes des étudiants sur le bureau des enseignants

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#844]
Sur le bureau virtuel des enseignants (dashboard de osis-portail), dans "Ma charge d'enseignement", on ne voit pas les notes des étudiants.
![image](https://cloud.githubusercontent.com/assets/6651769/23296320/bc07efd6-fa74-11e6-95bc-4aec7683c2d9.png)

**Comment by verpoorten** [comment]
Je viens de faire le test.  Pour tester j'ai modifié une note à l'étudiant Andre Marina directement dans le json de la base de données.

Beto dit que les données en dev dans studentPerformance ne sont pas à jour, mais qu'elles le sont bien en prod
![capture du 2017-02-24 11-08-25](https://cloud.githubusercontent.com/assets/5947635/23299388/b98f9b7a-fa81-11e6-885d-117cd6428477.png)
