### ISSUE TITLE
Le checkbox "Imprimée" n'est pas changé d'état après que je clique sur le téléchargement

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#882]
Lié à https://github.com/uclouvain/epc/issues/1307

Si l'étudiant réussit à télécharger un document, il faut changer le l'état de ce document
![image](https://cloud.githubusercontent.com/assets/6651769/23601486/f3e29f62-024b-11e7-9218-6700e24f41c3.png)

Dans EPC, ces informations (état et date) affichent dans l'écran:
![image](https://cloud.githubusercontent.com/assets/6651769/23601945/5934d18a-024e-11e7-8e3e-37292741d476.png)

**Comment by glamarca** [comment]
@thuyhanghoang 
Toutes les modifs sont faite du côté EPC dans le ticket https://github.com/uclouvain/epc/issues/1307
Une fois le pdf télécharger, il faut recharger la page pour voir le status changé à l'écran, je ne sai spas recharger la page après le téléchargement du pdf.

**Comment by glamarca** [comment]
@htmfilho 
Je met dans le pipeline 'in test' (+ milestone) , car il n'y aura pas de changement de code du côté osis-portal, mais il faut tester dan sosis-portal.

**Comment by htmfilho** [comment]
@glamarca Peux-on le mettre en Done?

**Comment by glamarca** [comment]
@thuyhanghoang 
Je me permet de le répêter, il faut recharger la page pour voir le changement sur l'icône de téléchargement.

**Comment by glamarca** [comment]
Avant Download : 

![attestation_not_downloaded](https://cloud.githubusercontent.com/assets/11191415/24145840/521795fe-0e33-11e7-8467-e7f9fdc138af.png)

![attestation_status_inscr_cen_not_printed](https://cloud.githubusercontent.com/assets/11191415/24145845/5702b1de-0e33-11e7-8665-63772e871add.png)

Après Download : 

![attestation_staus_printed](https://cloud.githubusercontent.com/assets/11191415/24145857/64d7a486-0e33-11e7-8d7e-9d810ee69978.png)

![attestation_statuses_printed_inscr_cen](https://cloud.githubusercontent.com/assets/11191415/24145859/6b3a283a-0e33-11e7-8ce6-82cb7239021b.png)
