### ISSUE TITLE
Il faut filtrer le dashboard en fonction des droits

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#883]
Il ne faut pas montrer "Stage" si l'étudiant n'a pas le groupe "internship_students"
Il ne faut pas encore montrer "Inscription aux examens"

**Comment by basmot** [comment]
@thuyhanghoang Je pense que c'est parce que tu es admin que tu as accès à tout. Si tu t'enlèves du groupe des admin, ça devrait fonctionner.

**Comment by cvn13** [comment]
testé et ok
