### ISSUE TITLE
Supprimer l'application admission du projet

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#894]
@htmfilho commented on [Thu Mar 02 2017](https://github.com/uclouvain/osis/issues/1856)

Utiliser les liens suivant comme reference:
- http://stackoverflow.com/questions/11382734/how-to-delete-an-app-from-a-django-project
- http://stackoverflow.com/questions/3329773/django-how-to-completely-uninstall-a-django-app
- http://stackoverflow.com/questions/35745220/how-to-remove-an-app-from-a-django-projects-and-all-its-tables

**Comment by verpoorten** [comment]
Il faut que du refactoring soit fait dans dissertation #903

**Comment by htmfilho** [comment]
Je ferme ce ticket ouvert parce que l'application d'admission n'est plus une priorité. Il faut le repenser.

**Comment by verpoorten** [comment]
@htmfilho N'est-ce pas une erreur de l'avoir fermé?

**Comment by htmfilho** [comment]
C'est vrai :-) Merci.

**Comment by verpoorten** [comment]
@htmfilho Est-ce qu'il faut aussi supprimer les models qui ne sont plus utilisés suite à la disparition d'admission?

**Comment by htmfilho** [comment]
@verpoorten oui, bien sûr.
