### ISSUE TITLE
Corrections traductions

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#917]
![image](https://cloud.githubusercontent.com/assets/6651769/25273262/55ff51a0-268b-11e7-8e0d-312b93c7c29b.png)

**Comment by verpoorten** [comment]
@thuyhanghoang Tu n'es pas un vraie étudiante et tu as trop de droit.  L'affichage est probablement correct pour les étudiants

**Comment by thuyhanghoang** [comment]
@verpoorten @htmfilho pourrait-on corriger ça? Car parfois je dois faire des captures d'écran pour des utilisateurs et ce n'est pas la même choses pour moi et pour des utilisateurs.

**Comment by thuyhanghoang** [comment]
- quand je clique sur "Mes notes d'examens" dans mon dashboard, je vois encore le lien comme je passe par "administration facultaire"
![image](https://cloud.githubusercontent.com/assets/6651769/25273167/f1c6d154-268a-11e7-8e2e-04d87c35a5d1.png)
- il y a une traduction à faire quand je clique sur l'inscription aux examens
![image](https://cloud.githubusercontent.com/assets/6651769/25273262/55ff51a0-268b-11e7-8e0d-312b93c7c29b.png)

**Comment by glamarca** [comment]
@thuyhanghoang 
Le premier c'est normal, c'est parce que tu es super utilisateur.
C'est parce que c'est la même page qui est utilisée, mais le bread crumb est mis à jour suivant ton status.
Si tu te connecte seulement en etudiant, le lien sera bon

**Comment by verpoorten** [comment]
@thuyhanghoang si je mets Choix de l'offre et offer choice pour remplacer "offer_choice"  C'est ok?

**Comment by thuyhanghoang** [comment]
@glamarca quand je passe par "Administration facultaire" pour voir les notes d'un étudiant => c'est normal que je vois le chemin comme ça:  "Administration facultaire/Administration des notes d'examens/Mes notes d'examens". Mais si je veux voir mes notes à moi en cliquant sur "Mes notes d'examens", je dois voir le chemin comme l'étudiant voir. Leila a déjà corrigé les autres points, il ne reste que "Mes notes d'examen". Tous les points des enseignants sont aussi corrigés.
![image](https://cloud.githubusercontent.com/assets/6651769/25277383/b6dcf050-269e-11e7-9837-16b1d497c3bc.png)
@verpoorten Choix de l'offre et Offer choice est ok

**Comment by glamarca** [comment]
Dans ce cas il faut dupliquer les ecrans de consultation et modifier les méthodes d'affichage.
Soit @verpoorten peut le faire dans ce ticket, soit il faut faire un ticket séparé.

**Comment by verpoorten** [comment]
@thuyhanghoang Pourrais-tu tester pour la traduction?  Je ne parviens pas à simuler le fait d'être un étudiant inscrit à qq ch de valide

**Comment by thuyhanghoang** [comment]
Comme convenu, pour ce ticket, on fait uniquement la traduction
![image](https://cloud.githubusercontent.com/assets/6651769/25375633/98adf7ea-29a1-11e7-8214-66fd356b5074.png)
![image](https://cloud.githubusercontent.com/assets/6651769/25375720/f364c1b4-29a1-11e7-8dc5-3022167551d9.png)

2em problème sera dans un autre ticket, @glamarca précisera le ticket

**Comment by glamarca** [comment]
Le ticket qui reprend les modifs de chemin dans le breadcrumb est le suivant : https://github.com/uclouvain/osis-portal/issues/1045

**Comment by thuyhanghoang** [comment]
merci @glamarca !!
