### ISSUE TITLE
Des améliorations dans le formulaire de profil

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#92]
1.  erreur lorsque vous appuyez sur "Sauvegarder" sans rien faire
2.  La nationalité est le nom du pays
3. "Avez-vous déjà été inscrit à l'UCL/Saint-Louis antérieurement?" Nom de l'institution paramétrable.
4. "Numéro du registre national (1)" le numéro 1 n'est pas nécessaire.
5. "(ex: Louvain-la-Neuve louvain-la-neuve)" Applicable seulement a Louvain-la-Neuve.
6. Après avoir complété le formulaire, la validation montre qu'il y a quelque chose d'incorrect, mais il ne précise pas.
7. "Adresse de contact" -> "Adresse de correspondance"

**Comment by verpoorten** [comment]
Autres soucis découverts lors des corrections

Dépendance entre application.py et common.py.  
Affichage d'une erreur si l'utilisateur n'est pas associé à une personne
