### ISSUE TITLE
Traiter le cas de doubles nomas et corriger le message d'erreur

### ISSUE THREAD

**Issue by mahianth** [uclouvain/osis-portal#923]
Traiter le cas de doubles nomas et corriger le message d'erreur. Comme il y a de cas de doubles nomas dans EPC et cela ne sera peut-être pas corrigé, donc il faut traiter le cas dans OSIS-Portal.

![img_2640](https://cloud.githubusercontent.com/assets/14234595/23697604/ab2ff8c0-03e8-11e7-8778-decb74f8ef15.PNG)

**Comment by htmfilho** [comment]
J'ai déjà traité le `server_error_message` dans le ticket #881 .

**Comment by glamarca** [comment]
@htmfilho @basmot 
Je ne sais pas savoir du côté osis portal si un noma est en erreur ou non.
Si l'utilisateur à plusieur noma, il n'est donc pas possible d'en choisir un.
Je pense que ce problème doit être résolu dans la synchronisation, pour ne pas prendre le noma en erreur.
Sinon, si je supprime le noma en erreur dans osis-portal, il revient lors de la prochaine synchronisation.

**Comment by htmfilho** [comment]
@glamarca Tu peux afficher un message plus parlant. Par exemple: "Il y a un problème avec votre inscription. Deux NOMAS ont été détectés sur votre compte. Veuillez contacter SIC (le service des inscriptions) pour résoudre le problème."

**Comment by glamarca** [comment]
![image](https://cloud.githubusercontent.com/assets/11191415/24058381/3485ce56-0b4b-11e7-91bb-cab5e4bafb44.png)

**Comment by htmfilho** [comment]
Super!

**Comment by glamarca** [comment]
@mahianth @htmfilho 
C'est implémenté pour les 4 application student (attestation, exam_enrollment, internship, performance), l'erreur est affichée au niveau du dasbhoard

![image](https://cloud.githubusercontent.com/assets/11191415/24063098/84ef53a4-0b5e-11e7-9618-e18998405909.png)

**Comment by glamarca** [comment]
@thuyhanghoang 
Popur tester il suffit de te rajouter un student lié à ta person, et tu devrais voir le message d'erreur en essayant d'arriver sur 'Attestation', 'Internship', 'Performance' et exam enrollment.

**Comment by thuyhanghoang** [comment]
![image](https://cloud.githubusercontent.com/assets/6651769/24141464/d2144a14-0e23-11e7-9cdf-5315c3562c23.png)
dev ok

**Comment by mahianth** [comment]
Faute d'orthographe à corriger !

"Un problème **a** été" et non "Un problème _à_ été"

**Comment by glamarca** [comment]
@mahianth 
Corrigé:
![image](https://cloud.githubusercontent.com/assets/11191415/24146279/55675562-0e35-11e7-89a8-9e94d5e227b8.png)
