### ISSUE TITLE
Message d'erreur lors que je clique sur une offre pour m'inscrire à l'examen

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#924]
![image](https://cloud.githubusercontent.com/assets/6651769/23698365/93360df6-03eb-11e7-8400-85aa8e4bb870.png)

**Comment by basmot** [comment]
L'erreur n'apparait plus en Dev. (C'était lié au JSON renvoyé qui conetent un String "TEST", qui n'est pas un JSON bien formaté, et qui donc faisait planter lors du json.loads())
