### ISSUE TITLE
Feedback des inscriptions aux examens

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#933]
- Changer la libellé: Etudiant en Nom, Prénom et adapter le contenu: Hoang, Hang (comme dans la publication des notes
![image](https://cloud.githubusercontent.com/assets/6651769/23694914/d4c45214-03dc-11e7-9a0c-3c28fe6335d7.png)
![image](https://cloud.githubusercontent.com/assets/6651769/23694963/19f1f026-03dd-11e7-8263-536f59b92942.png)

**Comment by basmot** [comment]
- [ ] Ajouter la virgule dans le Nom, prénom (exemple: "Mottiaux**,** Bastien")
- [ ] Changer ce label aussi sur la page "choix de l'offre"

**Comment by basmot** [comment]
Ok en Dev. Cela ne doit pas passer par @thuyhanghoang obligatoirement, je ferme donc ce ticket.
