### ISSUE TITLE
Create a new application "assessments" and move the score encoding from the dashboard

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#942]
The score encoding paper-sheet is currently developed in the dashboard module. It breaks cohesion. To avoid that, a new application should be created and the implementation of score encoding moved to the new application.

**Comment by htmfilho** [comment]
C'est bon en dev?

**Comment by albrugnetti** [comment]
@htmfilho Ok en dev
Qui peux tester ce ticket?
