### ISSUE TITLE
Supprimer le renouvellement du formulaire toute les 24h et adapter le message d'erreur

### ISSUE THREAD

**Issue by basmot** [uclouvain/osis-portal#948]
Il faut toujours faire appel à EPC pour générer le formulaire.
En effet, les gestionnaires et étudiants ont des interactions en direct et veulent pouvoir modifier les données du formulaire en même temps dans EPC et sur le portail...

- [ ] Supprimer la deadline pour le renouvellement du formulaire
- [ ] Adapter le message d'erreur lorsqu'il est propre à l'étudiant : "Vous ne pouvez pas vous inscrire aux examens pour le moment. Veuillez contacter votre gestionnaire pour plus d'informations."

**Comment by thuyhanghoang** [comment]
Ok en dev
