### ISSUE TITLE
Choix de la langue et Renommer Performance

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#952]
@cvn13 commented on [Fri Mar 17 2017](https://github.com/uclouvain/osis/issues/1971)

(1)
**En tant que** utilisateur

**Je veux** choisir la langue d'affichage de l'écran sur OSIS-PORTAL

dans la barre horizontale de navigation, à gauche du nom d'utilisateur, placer un double lien "FR - EN".

**de sorte que** le changement de préférence de langue soit visible et en un emplacement classique.

(2) Dans l'URL de "Mes Notes", remplacer le mot "performance" par "exammarks"

![image](https://cloud.githubusercontent.com/assets/14212310/24035901/a4cdb34e-0af7-11e7-9581-a445c2210b92.png)

Rechercher si le mot "Performance" est utilisé dans un écran, et dans ce cas le remplacer partout où il apparaît (écran, menu, ...) par "Exam marks" en anglais et "Notes d'examens" en français

**Testeur**: Philippe

**Comment by verpoorten** [comment]
@htmfilho je dois vraiment changer le nom 'performance' dans l'url?

**Comment by verpoorten** [comment]
@htmfilho je dois remplacer "mes notes" par "mes notes finales" en français et "My final marks" en anglais?

**Comment by htmfilho** [comment]
@ChristineJacqmot le ticket a été en backlog parce que je posé des questions que normalement les develepeur les posent, comme @verpoorten a fait. On a besoin de les réponses avant de considérer le ticket exécutable. Je le remet en backlog et on attend les réponses. Merci.

**Comment by verpoorten** [comment]
Que pensez-vous de ceci pour le changement de langue? 
[changement_langue.mp4.zip](https://github.com/uclouvain/osis-portal/files/850417/changement_langue.mp4.zip)

**Comment by bmjmoreau** [comment]
Je m'écarte de la proposition "Final Marks - Notes finales" parce que les notes ne sont pas toujours "finales" au sens compris par l'étudiant. En effet l'étudiant peux présenter un examen 2 fois par an.

**Comment by bmjmoreau** [comment]
Le point (1) en accord avec Hang et Beto.

**Comment by bmjmoreau** [comment]
Hang me signale que le mot "performance" se trouve dans 
1) https://dev.studies.uclouvain.be/dashboard/faculty_administration/
avec le lien "Administration de performance" 
à remplacer par "Administration des notes d'examens"
2) https://dev.studies.uclouvain.be/performance/administration/select_student/
avec le titre "Performances d'un étudiant"
à remplacer par "Notes d'examens d'un étudiant"

**Comment by thuyhanghoang** [comment]
testé en Dev, ok
