### ISSUE TITLE
Erreur de suppression mon student et mes inscriptions à l'offre

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#964]
@htmfilho  Pourriez-vous corriger pour que je puisse tester? Merci!

![image](https://cloud.githubusercontent.com/assets/6651769/24239076/c2fce542-0fac-11e7-939e-8c1c18c7b6f7.png)

**Comment by htmfilho** [comment]
@thuyhanghoang peux-tu le tester s'il te plaît ? Merci.

**Comment by thuyhanghoang** [comment]
@htmfilho j'ai encore le problème
![image](https://cloud.githubusercontent.com/assets/6651769/24252555/15b9d0f2-0fde-11e7-8554-a477131c378e.png)

**Comment by htmfilho** [comment]
En fait le delete en cascade ne marche que dans la même application. S'il y a un impact dans une autre application, donc c'erreur apparaître. On peux pas faire grand chose pour le moment. Il suffit de supprimer le record dans l'autre application pour régler le problème.
