### ISSUE TITLE
(101233, 104661, 105104) Consulter une liste détaillée de tous les étudiants inscrits à mes examens QW

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#966]
@mlainez commented on [Mon Mar 13 2017](https://github.com/uclouvain/osis/issues/1933)

En tant qu’enseignant, dans mon bureau virtuel - ma charge d'enseignement, je veux pouvoir consulter une liste détaillée de tous mes étudiants inscrits aux examens.

## Liste des attributs demandés
Voir le ticket uclouvain/epc#1360 (service web pour télécharger le fichier).
Voir ticket uclouvain/epc#1335 (pas bloquant, me cela ajout d'une colonne à la liste Excel existante)

## Remarques supplémentaires

Format : exportable et manipulable (fichier XLS)
Période de disponibilité: dès que les listes sont stabilisées (juste à la fin des désincriptions) -> fin période officielle affichage des notes. Gérer dans `academic_calendar`.

## Liste Excel disponible sur EPC 

Un tel fichier XLS est produit dans EPC (section statistiques) pour les gestionnaires. Si on part de cette liste (même vue pour les enseignants que pour les gestionnaires).

Accès à la liste : 
- EPC-Parcours, Menu principal, pavé "Liste et statistiques", cliquer sur "Listes & Stats insc. cours/exam"
- section "Un ou quelques cours", colonne "De toutes les facultés", 2è lien "Liste insc exam"
- introduire le code du cours (par exemple LLSMS 2006) 
- cliquer sur [+]
- cliquer sur [Rechercher facultés], 
- cliquer sur [Produire la liste d'inscriptions]

**Comment by bmjmoreau** [comment]
Je me demande quel est le lien entre ce ticket et le "score encoding" ?

**Comment by htmfilho** [comment]
Effectivement, ce n'est pas lié a l'encodage des notes, mais c'est utile pour les prof. avant les examens. En pratique, on va changer les écrans de la change de l'enseignant (domain: attribution) dans osis-portal.

**Comment by verpoorten** [comment]
@htmfilho @bmjmoreau On doit afficher la liste à l'écran? Il y a 35 colonnes???? pas facile...

**Comment by bmjmoreau** [comment]
Heu...  non, il ne s'agit que de télécharger une liste Excel.

**Comment by verpoorten** [comment]
@bmjmoreau on crée automatiquement la liste pour tous les cours du prof ou il peut choisir?

**Comment by bmjmoreau** [comment]
Pour "un ou quelques cours" dont il donnera le(s) code(s). Voir plus haut

    EPC-Parcours, Menu principal, pavé "Liste et statistiques", cliquer sur "Listes & Stats insc. cours/exam"
    section "Un ou quelques cours", colonne "De toutes les facultés", 2è lien "Liste insc exam"
    introduire le code du cours (par exemple LLSMS 2006)
    cliquer sur [+]
    cliquer sur [Rechercher facultés],
    cliquer sur [Produire la liste d'inscriptions]

**Comment by verpoorten** [comment]
Ok, je ne savais pas si on devait suivre le même concept.  Merci

**Comment by verpoorten** [comment]
ce n'est pas uniquement pour les  cours de l'enseignant connecté?

**Comment by bmjmoreau** [comment]
Moui, mais bon l'idée est de reprendre une liste existante ...
Il y a bien une liste des cours d'un prof mais le gars va souvent recevoir des choses qui sont de l'autre quadri ...

**Comment by bmjmoreau** [comment]
Y vont pas aimer recevoir trop à la fois je pense.

**Comment by verpoorten** [comment]
@bmjmoreau Je voyais plutot qqch comme ceci par exemple
![capture du 2017-04-14 15-32-01](https://cloud.githubusercontent.com/assets/5947635/25044623/e40b0034-2127-11e7-88b3-9b99d141b5fa.png)

**Comment by verpoorten** [comment]
Il semblerait que ce ticket ait été mergé avec le ticket 917???

**Comment by htmfilho** [comment]
C'est bon en dev?

**Comment by verpoorten** [comment]
@htmfilho Non car une partie des fichiers ne se trouvaient pas en dev????Je viens de faire une pull requets

**Comment by verpoorten** [comment]
@glamarca Pourrais-tu m'aider en vérifiant les configurations du serveur.  Je n'obtiens jamais d'xls.
@htmfilho La liste des cours affichées en trop longue.  Alors qu'en local ça fonctionne correctement.....

**Comment by verpoorten** [comment]
@htmfilho problème 1 : vu que je ne sais pas pourquoi la communication de ne fait pas avec EPC et que Gaetan n'est pas là pour vérifier la config sur les serveurs ....je pense que ce ticket ne sera pas prêt aujourd'hui. Problème 2: la liste des cours affichées est trop longue est-ce un problème avec mon profil?  L'idéal serait qu'un prof puisse éventuellement tester en DEV pour voir ce que cela donne.

**Comment by mahianth** [comment]
@verpoorten 
Pour le problème 2 : tu peux demander à Marc Lainez de tester, il est prof.

**Comment by htmfilho** [comment]
Encore 2 petites chose à améliorer:

- [ ] Le bouton "Produire XLS" devra s’afficher seulement quand il y a des cours à sélectionner. 
- [ ] Quand il n'y a pas de record, il faut afficher un message d’avertissement à la place de une table vide.
