### ISSUE TITLE
Corriger les fautes d'orthographe dans un message

### ISSUE THREAD

**Issue by mahianth** [uclouvain/osis-portal#967]
Corriger les fautes d'orthographe dans le message ci-dessous (caractères ajoutés et mis en gras) : 

Une erreur ina**t**tendue s'est produite
Nous avons été automatiquement informé**s** du problème. N'hésitez pas à nous aider en contactant le Service Desk et en décrivant l'opération effectuée de manière plus détaillée.

**Comment by matgerard** [comment]
Impossible de tester en dev car ce message d'erreur n'arrive qu'en prod.
J'ai vérifié les changements effectués et tout est ok.
