### ISSUE TITLE
Changer le texte dans la publication de notes

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#968]
![image](https://cloud.githubusercontent.com/assets/6651769/24256034/6d87a04e-0fe7-11e7-913d-ab8e4ee5fa70.png)
"La diffusion des résultats de la session de juin n'a pas encore été autorisée par votre faculté."
=> "La diffusion des notes de la session de juin n'a pas encore été autorisée par votre faculté." #

**Comment by enizeyimana** [comment]
il y a aussi une faute d'orthographe : éutidiants

________________________________
De : Hang Hoang <notifications@github.com>
Envoyé : jeudi 23 mars 2017 16:58
À : uclouvain/osis-portal
Cc : Subscribed
Objet : [uclouvain/osis-portal] Changer le texte dans la publication de notes (#968)


[image]<https://cloud.githubusercontent.com/assets/6651769/24256034/6d87a04e-0fe7-11e7-913d-ab8e4ee5fa70.png>
"La diffusion des résultats de la session de juin n'a pas encore été autorisée par votre faculté."
=> "La période de diffusion des notes de la session de juin n'est pas encore ouverte."

-

**Comment by glamarca** [comment]
@thuyhanghoang 
Si le verrou est mis juste pour un étudiant, la phrase que tu proposes n'est pas juste alors.
C'est soit une question de date , soit une décision de faculté, donc la phrase originale est plus juste.
Non?

**Comment by thuyhanghoang** [comment]
@glamarca voila, j'ai changé la phrase. Merci!

**Comment by thuyhanghoang** [comment]
ok, merci @glamarca
