### ISSUE TITLE
(102092) Optimiser la performance de la consultation des étudiants dans la charge de l'enseignant

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-portal#969]
**En tant que** enseignant, **je trouve** la consultation des étudiants d'une unité d’enseignement très lent et par fois un erreur se produit. Donc, 

La cause de l'erreur c'est un timeout, donc il faut optimiser la consultation pour éviter le timeout.

Fonction `show_students` dans `osis-portal/attribution/views/tutor_charge.py`.

**Comment by verpoorten** [comment]
@mahianth Tu aurais un exemple de prof?

**Comment by htmfilho** [comment]
C'est l'url qui j'ai t'envoyé via Slack.

**Comment by mahianth** [comment]
Voici, @verpoorten , en plus de Slack : 
Sandrine Mulkers, FGS 00021997, le cours LANGL1330.

**Comment by verpoorten** [comment]
Pour une liste de 1152 étudiants, il y a du progrès je suis passée de 20 sec à 8
et de 120 requêtes à 43
Ms c'est pas encore top :{
