### ISSUE TITLE
Admission - pas de valeur pour la zone Pays de naissance et Nationalité

### ISSUE THREAD

**Issue by cvn13** [uclouvain/osis-portal#98]
User Story

**En tant que** candidat

**Je veux** compléter mon profil et il n'y a pas de valeur dans la liste Pays de naissance et Nationalité et il n'est pas possible de le remplir manuellement.

**de sorte que** [quelque raison].

**lien vers la documentation** :

**Comment by cvn13** [comment]
A la sauvegarde -

MultiValueDictKeyError at /admission/profile/
"'birth_country'"
Request Method:	POST
Request URL:	https://dev.studies.uclouvain.be/admission/profile/
Django Version:	1.9
Exception Type:	MultiValueDictKeyError
Exception Value:	
"'birth_country'"
Exception Location:	/home/osis/VENV/lib/python3.4/site-packages/django/utils/datastructures.py in __getitem__, line 85
Python Executable:	/usr/bin/python3
Python Version:	3.4.2
Python Path:	
['/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/usr/lib/python3.4/lib-dynload',
 '/usr/local/lib/python3.4/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/home/osis/VENV/lib/python3.4/site-packages',
 '/home/osis/www/html/osis_portal/frontoffice/..',
 '/home/osis/www/html/osis_portal/frontoffice/../frontoffice']
Server time:	lun, 11 Avr 2016 10:46:20 +0000
Traceback Switch to copy-and-paste view

/home/osis/VENV/lib/python3.4/site-packages/django/utils/datastructures.py in __getitem__
            list_ = super(MultiValueDict, self).__getitem__(key) ...
▶ Local vars
During handling of the above exception ('birth_country'), another exception occurred:
/home/osis/VENV/lib/python3.4/site-packages/django/core/handlers/base.py in get_response
                    response = self.process_exception_by_middleware(e, request) ...
▶ Local vars
/home/osis/VENV/lib/python3.4/site-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/home/osis/www/html/osis_portal/frontoffice/../admission/views/common.py in profile
        if request.POST['birth_country']: ...
▶ Local vars
/home/osis/VENV/lib/python3.4/site-packages/django/utils/datastructures.py in __getitem__
            raise MultiValueDictKeyError(repr(key)) ...
▶ Local vars

**Comment by htmfilho** [comment]
Les tables de référence ne disposent pas des données nécessaires pour rendre les formulaires d'admission. Je vais ajouter quelques données pour débloquer les tests.
