### ISSUE TITLE
(101233, 104661, 105104, 105839) En tant qu'enseignant, je veux pouvoir télécharger la liste des étudiants d'un cours en xls

### ISSUE THREAD

**Issue by mlainez** [uclouvain/osis-portal#987]
Il était possible dans l'ancien bureau virtuel enseignant, de télécharger une liste des étudiants inscrits à un cours. Ce n'est plus le cas à l'heure actuelle.

J'utilise ces fichiers pour automatiser l'inscription des étudiants à des outils nécessaires au projet via des script qui lisent ce fichier en entrée.

**Comment by ChristineJacqmot** [comment]
OK mais la fonctionnalité doit être limitée à l'enseignant du cours. Dans l'ancien bureau, tout le monde pouvait obtenir le fichier des inscriptions pour  n'importe quel cours. C'est contraire au respect de la vie privée.

**Comment by mahianth** [comment]
Incident LDSD 105104 : 

-----Message d'origine-----
De : Julien Hendrickx [mailto:julien.hendrickx@uclouvain.be] 
Envoyé : jeudi 27 avril 2017 13:37
À : 8282@uclouvain.be
Objet : exportation liste d'étudiant

Bonjour,

Je voudrais vous faire part de mon grand mécontentement (et de ma surprise) par rapport au fait qu’il n’y ait plus moyen d’exporter une liste d’étudiants inscrits à un cours au format excel. Ces listes étaient pratiques pour l’organisation du cours, des tests, et pour noter les travaux intermédiaires. Je suis maintenant obligé de recourir à des copier-coller manuels, ce qui est potentiellement source d’erreurs.
Je vous prie de rétablir cette situation au plus vite

Julien Hendrickx

**Comment by mahianth** [comment]
Quand cela sera-t-il réimplémenté dans le bureau du professeur ?

**Comment by basmot** [comment]
@mahianth : 
@verpoorten travaille actuellement sur le #966, qui permettra au prof de produire la liste des inscrits aux examens sur Osis-portal. Dans ce fichier xls, on a également les infos des inscriptions aux cours (verifié avec @bmjmoreau). Donc le #966 devrait répondre aux besoins de celui-ci. 
Ce ticket est en cours de test. Si les tests passent, la liste devrait être dispo à partir de la semaine prochaine sur Osis-portal. En attente de validation.

**Comment by htmfilho** [comment]
@basmot ce n'est pas la même chose. C'est la liste des inscriptions aux cours, pas la liste des inscriptions aux examens.

**Comment by htmfilho** [comment]
@mlainez peux-tu nous envoyer par email un exemple de fichier excel qui répond à ta demande?

**Comment by basmot** [comment]
@htmfilho Oui mais dans la liste des inscriptions aux examens, on a également la liste des inscriptions aux cours. Donc 'liste inscriptions examens' == 'liste inscriptions cours + infos relatives aux examens'. 
Les fichiers sont les mêmes, sauf qu'il y a des colonnes en plus.

**Comment by verpoorten** [comment]
@basmot Le ticket [#1072](https://github.com/uclouvain/osis-portal/issues/1072) n'est-il pas la conclusion de ce problème?

**Comment by basmot** [comment]
@verpoorten Si en effet, bien vu, je ferme donc ce ticket (corrigé dans #1072).
