### ISSUE TITLE
Assurer que l'inscription aux examens des programmes sans cycle, sans niveau fonctionne

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#990]
Le code des programmes sont découpé avec une espace entre sigle et le reste. On doit supprimer l'espace. Il faut assurer que l'inscription aux examens fonctionne.

**Comment by htmfilho** [comment]
C'est ticket est lié à uclouvain/osis-legacy-sync#400. En principe, Il n'y a rien à faire du coté osis, mais il faut mettre ce ticket `In test` quand le ticket de legacy-sync est terminé.

**Comment by basmot** [comment]
Ok en Dev pour les inscriptions aux examens.
@thuyhanghoang Peux-tu confirmer que tout est ok?

**Comment by thuyhanghoang** [comment]
J'ai testé des étudiants en IS, FC, 3DP, 11BA, MS/.. c'est ok
Il y a un problème d'un étudiant particulier pour son inscription aux examens, je vais voir avec Evase
