### ISSUE TITLE
Mettre le fond d'écran Dev, QA de OSIS-Portail

### ISSUE THREAD

**Issue by thuyhanghoang** [uclouvain/osis-portal#993]
Dans OSIS-Portail, mettre le fond d'écran de Dev et QA comme dans OSIS
![image](https://cloud.githubusercontent.com/assets/6651769/24656237/f94e72d4-1941-11e7-9be1-e85044765828.png)

**Comment by chfivet** [comment]
@glamarca

Hola, j'ai ajouté une variable dans settings, il faudra l'ajouter dans le serveur Dev et QA pour Osis-Portal. 
Il s'agit de Environment qui existe déjà côté Osis.

En te remerciant ;-)

PS : Je ne savais pas si tu devais être mis au coruant quand on touche au fichiers settings

**Comment by glamarca** [comment]
@chfivet 
Tu as dupliqué une fonction qui existe déjà : 
```python
def common_context_processor(request):
    return {'installed_apps': settings.INSTALLED_APPS, 'debug': settings.DEBUG, 'logout_button': settings.LOGOUT_BUTTON}
```
De plus tu as copié/collé le settings depuis osis sans enlever ce qui n'était pas nécéssaire : sentry_dns

Il faut supprimer le context processor que tu as créer et ajouter la variable ENVIRONMENT dans le common_context_processor

**Comment by chfivet** [comment]
Effectivement, je corrige ça de suite

**Comment by chfivet** [comment]
@glamarca C'est corrigé

**Comment by chfivet** [comment]
C'est en ordre pour Dev
